Repository kyma-project/cli, pull requests merged in 2019-06, with the labels that each got.

#103 Archive the artifacts only for release
  Makefile
Labels: area/cli

#107 Enable releasing using goreleaser
  .goreleaser.yml
  Makefile
Labels: area/cli

#108 Fix release configuration
  .goreleaser.yml
  Makefile
Labels: area/cli

#110 Add origin remote for goreleaser
  Makefile
Labels: area/cli

#118 Add kyma version env var
  .goreleaser.yml
  Gopkg.lock
  Gopkg.toml
  Makefile
  internal/installer/installer.go
  pkg/kyma/cmd/install/cmd.go
  pkg/kyma/cmd/install/opts.go
Labels: area/cli

#122 Release 1.2.0-rc2
  .goreleaser.yml
  Makefile
  pkg/kyma/cmd/install/cmd.go
  pkg/kyma/cmd/provision/minikube/cmd.go
Labels: area/cli

#126 Release 1.2.0
  .goreleaser.yml
  Makefile
Labels: area/cli

#128 Add windows release
  .goreleaser.yml
Labels: area/cli

#129 Configure goreleaser to release for windows as well
  .goreleaser.yml
Labels: area/cli

#127 Add installation instructions
  README.md
Labels: area/cli, area/documentation

#130 Add installation instructions
  README.md
Labels: area/cli, area/documentation

#132 Improve installation commands
  README.md
Labels: area/cli, area/documentation

#141 Release 1.2.1
  .goreleaser.yml
  Makefile
  pkg/kyma/cmd/install/cmd.go
  pkg/kyma/cmd/uninstall/cmd.go
Labels: area/cli

#148 Include Compass Gateway domain for Minikube provisioning
  pkg/kyma/cmd/provision/minikube/cmd.go
Labels: area/cli, enhancement
