Repository kyma-project/cli, pull requests merged in 2019-07, with the labels that each got.

#135 Add documentation for install and version commands
  pkg/kyma/cmd/install/cmd.go
  pkg/kyma/cmd/version/version.go
  pkg/kyma/docs/install.md
  pkg/kyma/docs/version.md
Labels: area/cli, area/documentation

#160 Fix provisioning minikube on linux
  pkg/kyma/cmd/provision/minikube/hosts_others.go
Labels: area/cli, bug

#186 Update stale bot settings to exclude epics
  .github/stale.yml
Labels: area/community

#191 Fix CLI readme
  README.md
Labels: area/documentation
