Repository kyma-project/cli, pull requests merged in 2019-11, with the labels that each got.

#286 Decouple installation logic from command
  cmd/kyma/install/cmd.go
  cmd/kyma/install/cmd_test.go
  cmd/kyma/install/hosts_others.go
  cmd/kyma/install/hosts_windows.go
  cmd/kyma/install/opts.go
  cmd/kyma/provision/minikube/cmd.go
  cmd/kyma/test/list/cmd.go
  cmd/kyma/test/run/cmd.go
  cmd/kyma/uninstall/cmd.go
  go.mod
  internal/cli/command.go
  internal/cli/options.go
  internal/kube/client.go
  internal/kube/config.go
  internal/kubectl/kubectl.go
  pkg/installation/installation.go
  pkg/installation/installation_test.go
  pkg/installation/opts.go
  pkg/installation/utils.go
  pkg/step/factory.go
  pkg/step/glyphs.go
  pkg/step/mocks/step.go
  pkg/step/simple.go
  pkg/step/spinner.go
  pkg/step/step.go
Labels: area/cli, area/installation

#298 Check and generate docs for updated provision command
  README.md
  cmd/kyma/completion/completion.go
  cmd/kyma/console/cmd.go
  cmd/kyma/install/cmd.go
  cmd/kyma/kyma.go
  cmd/kyma/provision/cmd.go
  cmd/kyma/provision/gardener/cmd.go
  cmd/kyma/provision/gcp/cmd.go
  cmd/kyma/provision/minikube/cmd.go
  cmd/kyma/test/cmd.go
  cmd/kyma/test/definitions/cmd.go
  cmd/kyma/test/delete/cmd.go
  cmd/kyma/test/list/cmd.go
  cmd/kyma/test/run/cmd.go
  cmd/kyma/test/status/cmd.go
  cmd/kyma/uninstall/cmd.go
  cmd/kyma/version/version.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_completion.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_gardener.md
  docs/gen-docs/kyma_provision_gcp.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_uninstall.md
  docs/gen-docs/kyma_version.md
Labels: area/cli, area/documentation

#296 Add watch option for `kyma test run` command
  cmd/kyma/test/definitions/cmd_test.go
  cmd/kyma/test/delete/cmd_test.go
  cmd/kyma/test/run/cmd.go
  cmd/kyma/test/run/cmd_test.go
  cmd/kyma/test/run/opts.go
  cmd/kyma/test/status/cmd_test.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_completion.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_gardener.md
  docs/gen-docs/kyma_provision_gcp.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_uninstall.md
  docs/gen-docs/kyma_version.md
  go.mod
  go.sum
  pkg/api/octopus/client.go
  pkg/api/octopus/mock.go
Labels: area/cli, area/documentation, enhancement

#297 Add functionality for fetching logs from test suite
  cmd/kyma/kyma.go
  cmd/kyma/test/common.go
  cmd/kyma/test/common_test.go
  cmd/kyma/test/logs/cmd.go
  cmd/kyma/test/logs/opts.go
  cmd/kyma/test/status/cmd.go
  cmd/kyma/test/status/cmd_test.go
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_logs.md
  internal/logs/fetcher.go
  internal/logs/fetcher_test.go
Labels: area/ci, area/documentation, enhancement

#300 Add functionality for generating JUnit XML report
  cmd/kyma/test/status/cmd.go
  cmd/kyma/test/status/opts.go
  docs/gen-docs/kyma_test_status.md
  go.mod
  internal/junitxml/automock/logs_fetcher.go
  internal/junitxml/dto.go
  internal/junitxml/report.go
  internal/junitxml/report_test.go
  internal/junitxml/testdata/TestWriteJUnitXMLReport.golden.xml
  internal/junitxml/testdata/TestWriteJUnitXMLReport.input.yaml
Labels: area/cli, area/documentation, enhancement

#308 Add upload-stable target
  Makefile
Labels: area/cli

#314 Improve command documentation
  cmd/kyma/install/cmd.go
  cmd/kyma/provision/gardener/cmd.go
  cmd/kyma/provision/gcp/cmd.go
  cmd/kyma/test/run/cmd.go
  cmd/kyma/test/status/cmd.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_completion.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_gardener.md
  docs/gen-docs/kyma_provision_gcp.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_logs.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_uninstall.md
  docs/gen-docs/kyma_version.md
Labels: area/cli, area/documentation

#315 Add links to generated command docs
  README.md
Labels: area/cli, area/documentation

#323 Release Kyma CLI 1.8.0
  .goreleaser.yml
  Makefile
Labels: area/community
