Repository kyma-project/cli, pull requests merged in 2019-08, with the labels that each got.

#203 Separate builds for different platforms
  Makefile
Labels: area/cli, enhancement

#200 Change add-ons domain name to addons
  Gopkg.lock
  Gopkg.toml
  Makefile
  cmd/kyma/provision/minikube/cmd.go
Labels: area/installation

#210 Fix golint version
  Gopkg.lock
  Gopkg.toml
  Makefile
Labels: area/ci, bug, priority/critical

#212 Increase decoupling between provisioning and installation
  Gopkg.lock
  cmd/kyma/install/cfg_darwin.go
  cmd/kyma/install/cfg_others.go
  cmd/kyma/install/cfg_windows.go
  cmd/kyma/install/cmd.go
  cmd/kyma/install/hosts_others.go
  cmd/kyma/install/hosts_windows.go
  cmd/kyma/install/opts.go
  cmd/kyma/provision/minikube/cfg_darwin.go
  cmd/kyma/provision/minikube/cfg_others.go
  cmd/kyma/provision/minikube/cfg_windows.go
  cmd/kyma/provision/minikube/cmd.go
  cmd/kyma/provision/minikube/opts.go
  internal/kube/client.go
  internal/kube/kube.go
Labels: area/cli

#216 Add yes/no prompt
  cmd/kyma/provision/minikube/cmd.go
  internal/step/mocks/step.go
  internal/step/simple.go
  internal/step/spinner.go
  internal/step/step.go
Labels: area/cli

#217 Retry when installation status is empty
  cmd/kyma/install/cmd.go
Labels: area/cli

#219 Add console command
  Gopkg.lock
  cmd/kyma/console/cmd.go
  cmd/kyma/console/opts.go
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  cmd/kyma/provision/minikube/cmd.go
  cmd/kyma/provision/minikube/opts.go
Labels: area/cli
