Repository kyma-project/cli, pull requests merged in 2019-05, with the labels that each got.

#77 updated minikube and kubectl version
  internal/kubectl/kubectl.go
  internal/minikube/minikube.go
Labels: area/cli, area/installation

#78 update to kyma 1.1
  Gopkg.toml
  pkg/kyma/cmd/install/cmd.go
  pkg/kyma/cmd/provision/minikube/cmd.go
Labels: area/cli

#91 Kyma CLI inline documentation review
  README.md
  internal/kubectl/kubectl.go
  internal/minikube/minikube.go
  pkg/kyma/cmd/install/cmd.go
  pkg/kyma/cmd/provision/minikube/cmd.go
  pkg/kyma/cmd/uninstall/cmd.go
Labels: area/documentation
