Repository kyma-project/cli, pull requests merged in 2019-10, with the labels that each got.

#246 Add missing TWs to codeowners
  CODEOWNERS
Labels: area/documentation

#268 Fix adding missing host from kyma-integration Namespace to /etc/hosts
  cmd/kyma/install/cmd.go
Labels: area/cli, bug

#260 Remove toggle from CLI documentation
  cmd/kyma/completion/completion.go
  cmd/kyma/console/cmd.go
  cmd/kyma/install/cmd.go
  cmd/kyma/provision/minikube/cmd.go
  cmd/kyma/test/run/cmd.go
  cmd/kyma/test/status/cmd.go
  cmd/kyma/uninstall/cmd.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_completion.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_uninstall.md
  docs/gen-docs/kyma_version.md
Labels: area/cli, area/documentation

#274 Bugfix for CLI docu
  cmd/kyma/provision/minikube/cmd.go
Labels: area/cli, area/documentation

#277 Fix the -c flag bug
  cmd/kyma/kyma.go
  cmd/kyma/test/run/cmd.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_completion.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_uninstall.md
  docs/gen-docs/kyma_version.md
Labels: area/cli, area/documentation

#281 Fix flag names
  cmd/kyma/test/run/cmd.go
  docs/gen-docs/kyma_test_run.md
Labels: area/cli, area/documentation

#181 Add shell completion for zsh
  cmd/kyma/completion/completion.go
Labels: area/cli

#285 Change default k8s version to a supported one on GCP
  cmd/kyma/provision/gcp/cmd.go
  cmd/kyma/provision/gcp/cmd_test.go
Labels: area/cli
