Repository kyma-project/cli, pull requests merged in 2020-02, with the labels that each got.

#364 Add support to latest gardner shoot apis
  cmd/kyma/provision/gardener/cmd.go
  cmd/kyma/provision/gardener/cmd_test.go
  cmd/kyma/provision/gardener/opts.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_completion.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_azure.md
  docs/gen-docs/kyma_provision_gardener.md
  docs/gen-docs/kyma_provision_gcp.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_logs.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_version.md
  go.mod
  go.sum
Labels: area/ci

#366 Introduce CI flag
  cmd/kyma/install/cmd.go
  cmd/kyma/kyma.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_completion.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_azure.md
  docs/gen-docs/kyma_provision_gardener.md
  docs/gen-docs/kyma_provision_gcp.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_logs.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_version.md
  internal/cli/options.go
  pkg/installation/installation.go
  pkg/installation/opts.go
Labels: area/ci, area/cli

#365 Upgrade default kubernetes version for minikube and GCP
  cmd/kyma/provision/gcp/cmd.go
  cmd/kyma/provision/gcp/cmd_test.go
  cmd/kyma/provision/minikube/cmd.go
  docs/gen-docs/kyma_provision_gcp.md
Labels: area/ci, enhancement

#383 Remove check on helm-certs-job
  pkg/installation/installation.go
Labels: bug, priority/critical

#382 Add graceful shutdown to kyma cli
  cmd/main.go
Labels: area/cli, bug

#387 Fix error printing in case of timeout
  pkg/installation/installation.go
  pkg/installation/utils.go
Labels: area/cli, bug

#388 Using io.Copy instead of ioutil.ReadAll
  pkg/installation/installation.go
Labels: area/cli, area/security

#390 Update go mod to latest hydroform
  go.mod
  go.sum
Labels: area/cli, bug
