Repository kyma-project/cli, pull requests merged in 2020-11, with the labels that each got.

#641 Fix the TW alias in the documentation issue template
  .github/ISSUE_TEMPLATE/documentation-improvement.md
Labels: area/documentation, bug

#642 Warn if a region is chosen
  cmd/kyma/provision/gardener/aws/cmd.go
  cmd/kyma/provision/gardener/gcp/cmd.go
  cmd/kyma/provision/gke/cmd.go
Labels: area/cli

#636 Remove k3d from prerequisites
  docs/08-02-cli-in-serverless.md
Labels: area/cli, area/documentation, area/serverless

#638 Enrich installation guide
  docs/03-02-examples.md
  internal/testdata/overrides.yaml
  pkg/installation/utils_test.go
Labels: area/cli, area/documentation

#645 Add --docker-ports flag in order to expose custom ports when running with docker VM driver
  cmd/kyma/provision/minikube/cmd.go
  cmd/kyma/provision/minikube/cmd_test.go
  cmd/kyma/provision/minikube/opts.go
  docs/gen-docs/kyma_provision_minikube.md
Labels: area/cli

#644 Fix: Git function creation fails due to missing GitRepository CR
  cmd/kyma/apply/function/function.go
  cmd/kyma/apply/function/function_test.go
  cmd/kyma/apply/function/opts.go
  docs/gen-docs/kyma_apply_function.md
  go.mod
  go.sum
Labels: area/serverless, bug

#649 Add more description for the CI flag
  cmd/kyma/kyma.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_apply.md
  docs/gen-docs/kyma_apply_function.md
  docs/gen-docs/kyma_completion.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_create.md
  docs/gen-docs/kyma_create_system.md
  docs/gen-docs/kyma_init.md
  docs/gen-docs/kyma_init_function.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_aks.md
  docs/gen-docs/kyma_provision_gardener.md
  docs/gen-docs/kyma_provision_gardener_aws.md
  docs/gen-docs/kyma_provision_gardener_az.md
  docs/gen-docs/kyma_provision_gardener_gcp.md
  docs/gen-docs/kyma_provision_gke.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_sync.md
  docs/gen-docs/kyma_sync_function.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_logs.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_upgrade.md
  docs/gen-docs/kyma_version.md
Labels: area/cli, area/documentation

#653 Purge removed commands from the documentation
  docs/gen-docs/kyma_template.md
  docs/gen-docs/kyma_template_function.md
Labels: area/serverless

#650 Consistent flag naming
  cmd/kyma/install/cmd.go
  cmd/kyma/install/cmd_test.go
  cmd/kyma/provision/minikube/cmd.go
  cmd/kyma/provision/minikube/cmd_test.go
  cmd/kyma/upgrade/cmd.go
  cmd/kyma/upgrade/cmd_test.go
  docs/03-02-examples.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_upgrade.md
  pkg/installation/installation.go
  pkg/installation/installation_test.go
Labels: area/cli

#658 Add profile flag
  cmd/kyma/install/cmd.go
  cmd/kyma/install/opts.go
  cmd/kyma/upgrade/cmd.go
  cmd/kyma/upgrade/opts.go
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_upgrade.md
  go.mod
  go.sum
  pkg/installation/installation.go
  pkg/installation/opts.go
  pkg/installation/utils.go
  pkg/installation/utils_test.go
Labels: area/cli, area/installation

#660 Master source flag
  Makefile
  README.md
  cmd/kyma/install/cmd.go
  cmd/kyma/upgrade/cmd.go
  docs/03-01-use-kyma-cli.md
  docs/03-02-examples.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_upgrade.md
  pkg/installation/installation.go
  pkg/installation/installation_test.go
  pkg/installation/opts.go
  pkg/installation/utils.go
  pkg/installation/utils_test.go
Labels: area/cli
