Repository kyma-project/cli, pull requests merged in 2020-09, with the labels that each got.

#567 Allowing non-interactive upgrade
  pkg/installation/upgrade.go
Labels: area/cli

#572 Add the documentation issue template
  .github/ISSUE_TEMPLATE/documentation-improvement.md
Labels: area/documentation, enhancement

#568 Fix behaviour when previous installation state is empty
  pkg/installation/installation.go
  pkg/installation/installation_test.go
  pkg/installation/upgrade.go
Labels: area/cli, bug

#575 Add create system command
  cmd/kyma/create/create.go
  cmd/kyma/create/create_test.go
  cmd/kyma/create/system/opts.go
  cmd/kyma/create/system/system.go
  cmd/kyma/create/system/system_test.go
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  cmd/kyma/test/logs/cmd.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_create.md
  docs/gen-docs/kyma_create_system.md
  go.mod
  go.sum
  internal/kube/client.go
  internal/kube/client_test.go
  internal/kube/kube.go
  internal/kube/mocks/KymaKube.go
Labels: area/cli

#566 Support minikube docker driver
  cmd/kyma/provision/minikube/cmd.go
  docs/gen-docs/kyma_provision_minikube.md
Labels: area/cli

#583 Adding more configurations for Minikube provisioning
  cmd/kyma/provision/minikube/cmd.go
Labels: area/cli

#591 Improve CLI docs
  cmd/kyma/provision/aks/cmd.go
  docs/01-01-overview.md
  docs/03-01-use-kyma-cli.md
  docs/gen-docs/kyma_provision_aks.md
Labels: area/cli

#596 Migrate to k8s API & go client v0.18 & new Kyma API
  cmd/kyma/console/cmd.go
  cmd/kyma/create/system/system.go
  cmd/kyma/provision/minikube/cmd.go
  cmd/kyma/version/cmd.go
  go.mod
  go.sum
  internal/hosts/domains.go
  internal/kube/client.go
  internal/kube/client_test.go
  internal/kube/kube.go
  internal/kube/mocks/KymaKube.go
  internal/logs/fetcher.go
  internal/logs/fetcher_test.go
  internal/trust/trust_darwin.go
  internal/trust/trust_linux.go
  internal/trust/trust_windows.go
  pkg/api/octopus/client.go
  pkg/installation/cluster.go
  pkg/installation/installation.go
  pkg/installation/installation_test.go
  pkg/installation/upgrade_test.go
  pkg/step/spinner.go
Labels: area/cli

#598 CLI accepts PR numbers from Kyma as a source
  cmd/kyma/install/cmd.go
  docs/gen-docs/kyma_install.md
  pkg/installation/installation.go
  pkg/installation/installation_test.go
  pkg/installation/opts.go
  pkg/installation/upgrade_test.go
  pkg/installation/utils.go
  pkg/installation/utils_test.go
Labels: area/cli
