Repository kyma-project/cli, pull requests merged in 2020-06, with the labels that each got.

#467 Move console to separate chart
  cmd/kyma/console/cmd.go
  internal/junitxml/testdata/TestWriteJUnitXMLReport/Test_Suite_Failed.golden.xml
  internal/junitxml/testdata/TestWriteJUnitXMLReport/Test_Suite_Failed.input.yaml
  pkg/installation/installation.go
Labels: enhancement

#471 Skip tiller if not exist
  pkg/installation/installation.go
  pkg/installation/installation_test.go
  pkg/installation/utils.go
Labels: area/cli

#472 Idempotent installation process - re-attach
  cmd/kyma/install/cmd.go
  pkg/installation/installation.go
Labels: area/cli, enhancement

#474 Add components flag
  cmd/kyma/install/cmd.go
  cmd/kyma/install/opts.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_completion.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_aks.md
  docs/gen-docs/kyma_provision_gardener.md
  docs/gen-docs/kyma_provision_gardener_aws.md
  docs/gen-docs/kyma_provision_gardener_az.md
  docs/gen-docs/kyma_provision_gardener_gcp.md
  docs/gen-docs/kyma_provision_gke.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_logs.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_version.md
  go.mod
  go.sum
  internal/testdata/components.yaml
  internal/testdata/installationCR.yaml
  internal/testdata/overrides.yaml
  pkg/installation/installation.go
  pkg/installation/installation_test.go
  pkg/installation/opts.go
  pkg/installation/service.go
  pkg/installation/utils.go
  pkg/installation/utils_test.go
Labels: area/cli

#478 Add commit hash source option
  cmd/kyma/install/cmd.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_completion.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_aks.md
  docs/gen-docs/kyma_provision_gardener.md
  docs/gen-docs/kyma_provision_gardener_aws.md
  docs/gen-docs/kyma_provision_gardener_az.md
  docs/gen-docs/kyma_provision_gardener_gcp.md
  docs/gen-docs/kyma_provision_gke.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_logs.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_version.md
  pkg/installation/installation.go
  pkg/installation/utils.go
Labels: area/cli, enhancement

#482 Update provision command
  README.md
Labels: area/documentation
