Repository kyma-project/cli, pull requests merged in 2020-05, with the labels that each got.

#451 refactored custom domain handling
  cmd/kyma/install/cmd.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_completion.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_aks.md
  docs/gen-docs/kyma_provision_gardener.md
  docs/gen-docs/kyma_provision_gardener_aws.md
  docs/gen-docs/kyma_provision_gardener_az.md
  docs/gen-docs/kyma_provision_gardener_gcp.md
  docs/gen-docs/kyma_provision_gke.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_logs.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_version.md
  pkg/installation/installation.go
  pkg/installation/opts.go
  pkg/installation/utils.go
Labels: area/cli

#453 Improve timeout message
  internal/minikube/minikube.go
Labels: area/cli

#458 Fix logic to set custom domain
  pkg/installation/utils.go
Labels: area/cli

#459 Use changelog-generator for release notes
  .github/package.json
  .gitignore
  Makefile
  hack/release.sh
Labels: area/cli

#457 Updating CLI Homebrew formula after release
  README.md
Labels: area/cli, area/documentation

#461 Add Windows install documentation using Chocolatey
  README.md
Labels: area/cli

#462 Upgrade crypto dependency
  go.mod
  go.sum
Labels: area/security
