Repository kyma-project/cli, pull requests merged in 2020-10, with the labels that each got.

#605 update gke provisioning to k8s 1.16
  cmd/kyma/provision/gke/cmd.go
  cmd/kyma/provision/gke/cmd_test.go
  docs/gen-docs/kyma_provision_gke.md
Labels: area/cli

#604 Add compatibility documentation
  docs/01-01-overview.md
  docs/internal/compatibility-template.md
Labels: area/documentation

#609 treat errors as failure in junit output
  internal/junitxml/report.go
Labels: area/cli

#606 Function cmd
  cmd/kyma/apply/apply.go
  cmd/kyma/apply/apply_test.go
  cmd/kyma/apply/function/function.go
  cmd/kyma/apply/function/function_test.go
  cmd/kyma/apply/function/opts.go
  cmd/kyma/init/function/function.go
  cmd/kyma/init/function/function_test.go
  cmd/kyma/init/function/opts.go
  cmd/kyma/init/init.go
  cmd/kyma/init/init_test.go
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_apply.md
  docs/gen-docs/kyma_apply_function.md
  docs/gen-docs/kyma_init.md
  docs/gen-docs/kyma_init_function.md
  docs/gen-docs/kyma_template.md
  docs/gen-docs/kyma_template_function.md
  go.mod
  go.sum
Labels: hacktoberfest

#621 Refactor upgrade command
  pkg/installation/upgrade.go
Labels: area/cli, enhancement

#623 Expose kubernetes version for Minikube
  cmd/kyma/provision/minikube/cmd.go
  cmd/kyma/provision/minikube/opts.go
  docs/gen-docs/kyma_provision_minikube.md
Labels: area/cli

#625 Always print the url in console command
  cmd/kyma/console/cmd.go
Labels: area/cli

#627 New default namespace for the init function command
  cmd/kyma/init/function/function.go
  cmd/kyma/init/function/function_test.go
  cmd/kyma/init/function/opts.go
  docs/gen-docs/kyma_init_function.md
Labels: area/serverless, hacktoberfest-accepted

#628 Fix --source detects certain commit as a release
  pkg/installation/installation.go
Labels: area/cli

#618 Add sync function command
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  cmd/kyma/sync/function/function.go
  cmd/kyma/sync/function/function_test.go
  cmd/kyma/sync/function/opts.go
  cmd/kyma/sync/sync.go
  cmd/kyma/sync/sync_test.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_sync.md
  docs/gen-docs/kyma_sync_function.md
  go.mod
  go.sum
Labels: area/cli, enhancement, hacktoberfest-accepted

#632 Change semver dependency for strict validation
  go.mod
  go.sum
  internal/minikube/minikube.go
  pkg/installation/upgrade.go
  pkg/installation/utils.go
  pkg/installation/utils_test.go
Labels: area/cli

#633 Synchronise command adjustment
  cmd/kyma/sync/function/function.go
  cmd/kyma/sync/function/function_test.go
  cmd/kyma/sync/function/opts.go
  docs/gen-docs/kyma_sync_function.md
Labels: area/cli

#631 Add a CLI tutorial for Functions
  docs/08-02-cli-in-serverless.md
Labels: area/documentation, area/serverless
