Repository kyma-project/cli, pull requests merged in 2020-01, with the labels that each got.

#350 Fix panic when the test suite is still running
  internal/junitxml/report.go
  internal/junitxml/report_test.go
  internal/junitxml/testdata/TestWriteJUnitXMLReport/TestSuite_is_still_running_but_timeout_occur.golden.xml
  internal/junitxml/testdata/TestWriteJUnitXMLReport/TestSuite_is_still_running_but_timeout_occur.input.yaml
  internal/junitxml/testdata/TestWriteJUnitXMLReport/Test_Suite_Failed.golden.xml
  internal/junitxml/testdata/TestWriteJUnitXMLReport/Test_Suite_Failed.input.yaml
Labels: area/cli, bug

#351 Update version of minikube
  internal/minikube/minikube.go
Labels: area/installation, enhancement

#356 Enable stale bot for epics
  .github/stale.yml
Labels: area/community

#358 Remove uninstall command
  README.md
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  cmd/kyma/provision/azure/cmd.go
  cmd/kyma/test/status/cmd.go
  cmd/kyma/uninstall/cmd.go
  cmd/kyma/uninstall/cmd_test.go
  cmd/kyma/uninstall/opts.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_completion.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_azure.md
  docs/gen-docs/kyma_provision_gardener.md
  docs/gen-docs/kyma_provision_gcp.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_logs.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_uninstall.md
  docs/gen-docs/kyma_version.md
  pkg/installation/installation.go
Labels: area/cli

#360 Increased default concurrency of test execution
  cmd/kyma/test/run/cmd.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_completion.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_azure.md
  docs/gen-docs/kyma_provision_gardener.md
  docs/gen-docs/kyma_provision_gcp.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_logs.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_version.md
Labels: area/cli
