Repository kyma-project/cli, pull requests merged in 2021-08, with the labels that each got.

#948 Bump hydroform
  go.mod
  go.sum
Labels: area/serverless, bug, lgtm, size/XS

#951 Migrate alpha commands to stable
  cmd/kyma/console/cmd.go
  cmd/kyma/delete/cmd.go
  cmd/kyma/delete/opts.go
  cmd/kyma/deploy/cmd.go
  cmd/kyma/deploy/cmd_test.go
  cmd/kyma/deploy/compatibility.go
  cmd/kyma/deploy/compatibility_test.go
  cmd/kyma/deploy/opts.go
  cmd/kyma/deploy/opts_test.go
  cmd/kyma/install/cmd.go
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  cmd/kyma/provision/k3d/cmd.go
  cmd/kyma/provision/k3d/cmd_test.go
  cmd/kyma/provision/k3d/opts.go
  cmd/kyma/provision/minikube/cmd.go
  cmd/kyma/test/cmd.go
  cmd/kyma/test/definitions/cmd.go
  cmd/kyma/test/delete/cmd.go
  cmd/kyma/test/list/cmd.go
  cmd/kyma/test/logs/cmd.go
  cmd/kyma/test/run/cmd.go
  cmd/kyma/test/status/cmd.go
  cmd/kyma/upgrade/cmd.go
  cmd/kyma/version/cmd.go
  cmd/kyma/version/cmd_test.go
  cmd/kyma/version/opts.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_delete.md
  docs/gen-docs/kyma_deploy.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_k3d.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_logs.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_upgrade.md
  docs/gen-docs/kyma_version.md
  internal/clusterinfo/clusterinfo.go
  internal/k3d/cluster.go
  internal/k3d/k3d.go
  internal/k3d/k3d_test.go
  internal/k3d/mock/cluster_create.txt
  internal/k3d/mock/cluster_delete.txt
  internal/k3d/mock/cluster_list.txt
  internal/k3d/mock/cluster_list_empty.json
  internal/k3d/mock/cluster_list_exists.json
  internal/k3d/mock/k3d
  internal/k3d/mock/version.txt
  internal/k3d/mock/version_incompmajor.txt
  internal/k3d/mock/version_incompminor.txt
  internal/trust/trust.go
  internal/trust/trust_darwin.go
  internal/trust/trust_linux.go
  internal/trust/trust_windows.go
Labels: lgtm, size/XXL

#955 remove alpha folder and docs
  cmd/kyma/alpha/cmd.go
  cmd/kyma/alpha/delete/cmd.go
  cmd/kyma/alpha/delete/opts.go
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/cmd_test.go
  cmd/kyma/alpha/deploy/compatibility.go
  cmd/kyma/alpha/deploy/compatibility_test.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/alpha/deploy/opts_test.go
  cmd/kyma/alpha/provision/cmd.go
  cmd/kyma/alpha/provision/k3s/cmd.go
  cmd/kyma/alpha/provision/k3s/cmd_test.go
  cmd/kyma/alpha/provision/k3s/opts.go
  cmd/kyma/alpha/version/cmd.go
  cmd/kyma/alpha/version/cmd_test.go
  cmd/kyma/alpha/version/opts.go
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_alpha.md
  docs/gen-docs/kyma_alpha_delete.md
  docs/gen-docs/kyma_alpha_deploy.md
  docs/gen-docs/kyma_alpha_provision.md
  docs/gen-docs/kyma_alpha_provision_k3s.md
  docs/gen-docs/kyma_alpha_version.md
  internal/trust/trust.go
  internal/trust/trust_darwin.go
  internal/trust/trust_linux.go
  internal/trust/trust_windows.go
Labels: lgtm, size/XXL

#957 Remove kazydek & superojla from CODEOWNERS
  CODEOWNERS
Labels: area/documentation, area/community, size/XS, lgtm

#959 Upgrade hydroform/function dependency
  go.mod
  go.sum
Labels: area/serverless, size/XS, lgtm

#960 Upgrade hydroform/function dependency
  go.mod
  go.sum
Labels: area/serverless, size/XS, lgtm

#961 Document field `source.credentialsType` in the config.yaml
  docs/03-04-function-configuration-file.md
Labels: area/documentation, area/serverless, size/XS, lgtm

#947 Update Kyma version to 1.24.3
  .goreleaser.yml
  Makefile
Labels: size/XS, lgtm

#963 Upgrade hydroform/function dependency
  go.mod
  go.sum
Labels: area/serverless, size/XS, lgtm

#965 Don't fail if override file is not present
  cmd/kyma/deploy/cmd.go
  go.mod
  go.sum
Labels: size/S, lgtm

#966 Upgrade hydroform/function dependency
  go.mod
  go.sum
Labels: size/XS, lgtm

#962 Enable ServiceAccountIssuerDiscovery feature gate in Minikube when K8S version >= 1.18
  cmd/kyma/provision/minikube/cmd.go
Labels: size/S, lgtm
