Repository kyma-project/cli, pull requests merged in 2021-11, with the labels that each got.

#1062 make k3d registry port configurable via a flag
  cmd/kyma/alpha/provision/k3d/cmd.go
  cmd/kyma/alpha/provision/k3d/opts.go
  cmd/kyma/deploy/cmd.go
  docs/gen-docs/kyma_alpha_provision_k3d.md
  internal/k3d/k3d.go
  internal/k3d/k3d_test.go
Labels: size/S, lgtm

#1069 update default values for garden linux
  cmd/kyma/provision/gardener/aws/cmd_test.go
  cmd/kyma/provision/gardener/aws/template.go
  cmd/kyma/provision/gardener/az/cmd_test.go
  cmd/kyma/provision/gardener/az/template.go
  cmd/kyma/provision/gardener/gcp/cmd_test.go
  cmd/kyma/provision/gardener/gcp/template.go
Labels: size/S, lgtm

#1070 dashboard cmd: open current cluster automatically
  cmd/kyma/dashboard/cmd.go
  pkg/docker/docker.go
  pkg/docker/docker_test.go
Labels: area/cli, size/M, lgtm

#1071 Update reconciler image tag
  cmd/kyma/deploy/cmd.go
  go.mod
  go.sum
Labels: size/XS, lgtm

#1072 Fix import hosts command
  cmd/kyma/import/hosts/cmd.go
  internal/hosts/cfg_darwin.go
  internal/hosts/cfg_others.go
  internal/hosts/domains.go
  internal/hosts/hosts_others.go
  internal/hosts/hosts_windows.go
Labels: size/L, lgtm

#1076 Update reconciler Version
  go.mod
  go.sum
Labels: size/XS, lgtm

#1077 dashboard cmd: allow running busola container without mounting kubeconfig
  cmd/kyma/dashboard/cmd.go
Labels: area/cli, size/M, lgtm

#1073 dashboard cmd: print only error logs in non-verbose mode
  cmd/kyma/dashboard/cmd.go
  cmd/kyma/dashboard/opts.go
  docs/gen-docs/kyma_dashboard.md
Labels: area/cli, size/S, lgtm

#1079 Update reconciler version
  go.mod
  go.sum
Labels: size/XS, lgtm

#1078 alpha provision k3d: use k3d v5.1.0
  cmd/kyma/alpha/provision/k3d/cmd.go
  cmd/kyma/alpha/provision/k3d/opts.go
  docs/gen-docs/kyma_alpha_provision_k3d.md
  internal/k3d/k3d.go
  internal/k3d/k3d_test.go
Labels: size/M, lgtm

#1081 Replace provision k3d with alpha implementation
  cmd/kyma/provision/k3d/cmd.go
  cmd/kyma/provision/k3d/opts.go
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_k3d.md
Labels: size/L, lgtm

#1082 Revert "Replace provision k3d with alpha implementation (#1081)"
  cmd/kyma/provision/k3d/cmd.go
  cmd/kyma/provision/k3d/opts.go
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_k3d.md
Labels: size/L, lgtm

#1083 rebase to latest reconciler image
  go.mod
  go.sum
  internal/deploy/deploy.go
  internal/deploy/deploy_test.go
  internal/logs/fetcher_test.go
Labels: size/XL, lgtm

#1084 Update Kyma version to 1.24.8
  .goreleaser.yml
  Makefile
Labels: size/XS, lgtm

#1085 dashboard cmd: improve the warning message when kubeconfig is invalid
  cmd/kyma/dashboard/cmd.go
Labels: area/cli, size/XS, lgtm

#1086 rebase to latest reconciler
  go.mod
  go.sum
Labels: size/L, lgtm

#1089 Implement fish and powershell completion
  cmd/kyma/completion/cmd.go
  docs/gen-docs/kyma_completion.md
Labels: enhancement, size/M, lgtm

#1091 rebase to latest recon
  go.mod
  go.sum
Labels: size/XS, lgtm

#1090 Resolve Checkmarx vulnerabilities - download istioctl
  internal/deploy/istioctl/istio.go
Labels: size/M, lgtm

#1094 Update to the latest reconciler
  cmd/kyma/deploy/cmd.go
  go.mod
  go.sum
Labels: size/M, lgtm

#1093 Resolve low checkmarx issues
  internal/cli/finalizers.go
  internal/cli/finalizers_test.go
  internal/junitxml/report.go
Labels: size/M, lgtm

#1087 Add ability to override default k3d registry settings
  internal/deploy/values/builder.go
  internal/deploy/values/testdata/registry-overrides.yaml
  internal/deploy/values/values.go
  internal/deploy/values/values_test.go
Labels: size/M, lgtm

#1096 adjust dashboard cmd container log level
  cmd/kyma/dashboard/cmd.go
Labels: area/cli, size/XS, lgtm

#1100 Revert "alpha provision k3d: use k3d v5.1.0 (#1078)"
  cmd/kyma/alpha/provision/k3d/cmd.go
  cmd/kyma/alpha/provision/k3d/opts.go
  docs/gen-docs/kyma_alpha_provision_k3d.md
  internal/k3d/k3d.go
  internal/k3d/k3d_test.go
Labels: size/M, lgtm

#1099 Allow publishing unstable builds to a different GCS bucket
  Makefile
Labels: area/cli, size/S, lgtm

#1101 Update the latest reconciler
  go.mod
  go.sum
  internal/deploy/component/list.go
Labels: size/S, lgtm

#1102 fixed windows binaries
  Makefile
  README.md
Labels: area/cli, size/XS, lgtm

#1095 Move alpha provision k3d impl to stable cmd
  cmd/kyma/provision/k3d/cmd.go
  cmd/kyma/provision/k3d/opts.go
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_k3d.md
Labels: size/L, lgtm

#1103 remove alpha provision command
  cmd/kyma/alpha/cmd.go
  cmd/kyma/alpha/provision/cmd.go
  cmd/kyma/alpha/provision/k3d/cmd.go
  cmd/kyma/alpha/provision/k3d/cmd_test.go
  cmd/kyma/alpha/provision/k3d/opts.go
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  cmd/kyma/provision/k3d/cmd.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_alpha.md
  docs/gen-docs/kyma_alpha_provision.md
  docs/gen-docs/kyma_alpha_provision_k3d.md
  docs/gen-docs/kyma_provision_k3d.md
Labels: size/L, lgtm

#1104 Bump reconciler to the latest
  go.mod
  go.sum
Labels: size/XS, lgtm
