Repository kyma-project/cli, pull requests merged in 2021-04, with the labels that each got.

#841 Migrate master to main
  .goreleaser.yml
  Makefile
  README.md
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/compatibility_test.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/init/function/function.go
  cmd/kyma/init/function/function_test.go
  cmd/kyma/install/cmd.go
  cmd/kyma/upgrade/cmd.go
  docs/03-01-use-kyma-cli.md
  docs/03-02-examples.md
  docs/03-03-examples-alpha.md
  docs/08-02-cli-in-serverless.md
  docs/gen-docs/kyma_alpha_deploy.md
  docs/gen-docs/kyma_init_function.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_upgrade.md
  go.mod
  go.sum
  internal/k3s/cluster.go
  pkg/installation/installation.go
  pkg/installation/installation_test.go
  pkg/installation/opts.go
  pkg/installation/utils.go
  pkg/installation/utils_test.go
Labels: area/ci

#847 Deploy single component
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/cmd_test.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/alpha/deploy/opts_test.go
  docs/gen-docs/kyma_alpha_deploy.md
  go.mod
  go.sum
Labels: area/cli, area/installation

#845 add --force flag for docker driver
  cmd/kyma/provision/minikube/cmd.go
Labels: area/cli

#853 Fix certificate import
  cmd/kyma/alpha/deploy/cmd.go
  internal/trust/mocks/certifier.go
  internal/trust/trust.go
  internal/trust/trust_darwin.go
  internal/trust/trust_linux.go
  internal/trust/trust_windows.go
Labels: area/cli

#856 K3d further parameters
  cmd/kyma/alpha/provision/k3s/cmd.go
  cmd/kyma/alpha/provision/k3s/opts.go
  docs/gen-docs/kyma_alpha_provision_k3s.md
  internal/k3s/k3s.go
  internal/k3s/k3s_test.go
  internal/k3s/mock/k3d
Labels: area/cli, area/installation

#838 Allow to define api rules as part of function manifest
  cmd/kyma/apply/function/function.go
  cmd/kyma/init/function/opts.go
  go.mod
  go.sum
Labels: area/serverless

#849 Adapt (inline-)doc regards to new Hydroform branch-install-feature
  cmd/kyma/alpha/deploy/cmd.go
  docs/gen-docs/kyma_alpha_deploy.md
Labels: area/cli

#872 Fix `source.sourcePath` defaulting for config.yaml
  cmd/kyma/apply/function/function.go
Labels: area/serverless

#870 Improve defaulting of sourcePath in the function config
  cmd/kyma/init/function/opts.go
Labels: area/cli, area/serverless

#875 Typo: launch.json, not lunch.json
  docs/08-03-debug-function.md
Labels: lgtm

#878 Bump parallel-install version
  go.mod
  go.sum
Labels: lgtm, size/XS

#857 Add config.yaml definition
  docs/03-04-function-configuration-file.md
  docs/08-02-cli-in-serverless.md
Labels: area/documentation, lgtm, size/L

#879 Upgrade Hydroform
  go.mod
  go.sum
Labels: area/cli, lgtm, size/XS

#881 Upgrade deps to latest versions where possible
  go.mod
  go.sum
Labels: lgtm, size/M

#874 Change default workspace for deployment
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  docs/gen-docs/kyma_alpha_deploy.md
Labels: area/cli, area/installation, lgtm, size/S

#884 Remove hardcoded default values for flags
  cmd/kyma/alpha/delete/cmd.go
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/provision/k3s/cmd.go
  docs/gen-docs/kyma_alpha_delete.md
  docs/gen-docs/kyma_alpha_deploy.md
  docs/gen-docs/kyma_alpha_provision_k3s.md
Labels: area/cli, lgtm, size/M
