Repository kyma-project/cli, pull requests merged in 2021-09, with the labels that each got.

#968 Change kyma_version to 1.24.5
  .goreleaser.yml
  Makefile
Labels: size/XS, lgtm

#970 Permission for deleting existing files when downloading Kyma sources
  cmd/kyma/deploy/cmd.go
  internal/files/files.go
Labels: bug, area/cli, lgtm

#971 Split the string based on space
  cmd/kyma/provision/k3d/cmd.go
Labels: size/S, lgtm

#972 Alpha deploy reconciler
  cmd/kyma/alpha/cmd.go
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/apply/apply_test.go
  cmd/kyma/create/create_test.go
  cmd/kyma/init/init_test.go
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  cmd/kyma/run/run_test.go
  cmd/kyma/sync/sync_test.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_alpha.md
  docs/gen-docs/kyma_alpha_deploy.md
  go.mod
  go.sum
  internal/coredns/coredns.go
  internal/gardener/gardener.go
  internal/k3d/utils.go
  internal/logs/fetcher_test.go
  internal/overrides/interceptors.go
  internal/overrides/interceptors_test.go
  internal/overrides/overrides.go
  internal/overrides/overrides_test.go
  internal/overrides/provider.go
  internal/overrides/testdata/deployment-global-overrides-for-remote-cluster.yaml
  internal/overrides/testdata/deployment-global-overrides.yaml
  internal/overrides/testdata/deployment-overrides-intercepted-result.yaml
  internal/overrides/testdata/deployment-overrides-intercepted.yaml
  internal/overrides/testdata/deployment-overrides-result.yaml
  internal/overrides/testdata/deployment-overrides1.yaml
  internal/overrides/testdata/deployment-overrides2.json
Labels: area/cli, size/XXL, lgtm

#974 Bump reconciler dependency
  cmd/kyma/alpha/deploy/cmd.go
  go.mod
  go.sum
  internal/overrides/overrides.go
  internal/overrides/overrides_test.go
Labels: area/cli, size/M, lgtm

#978 Upgrade the `hydroform/function` deps
  go.mod
  go.sum
Labels: area/serverless, size/XS, lgtm

#975 Upgrade the `hydroform/function` deps
  go.mod
  go.sum
Labels: area/serverless, size/XS, lgtm

#979 Add flags for components to be passed as file or as string
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  docs/gen-docs/kyma_alpha_deploy.md
  go.mod
  go.sum
  internal/component/componentlist.go
  internal/component/componentlist_test.go
  internal/component/test/data/componentlist.json
  internal/component/test/data/componentlist.yaml
Labels: size/L, lgtm

#983 Alpha deploy override flags
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/alpha/deploy/opts_test.go
  cmd/kyma/alpha/deploy/testdata/dummy.txt
  cmd/kyma/alpha/deploy/testdata/fake.crt
  cmd/kyma/alpha/deploy/testdata/fake.key
  cmd/kyma/alpha/deploy/testdata/valid-overrides-1.yaml
  cmd/kyma/alpha/deploy/testdata/valid-overrides-2.yaml
  cmd/kyma/alpha/deploy/testdata/values.yaml
  cmd/kyma/alpha/deploy/tmp/valid-overrides-1.yaml
  cmd/kyma/alpha/deploy/values.go
  cmd/kyma/alpha/deploy/values_test.go
  docs/gen-docs/kyma_alpha_deploy.md
  go.mod
  internal/component/componentlist.go
  internal/component/componentlist_test.go
  internal/coredns/coredns.go
  internal/overrides/interceptors_test.go
  internal/overrides/overrides.go
  internal/overrides/overrides_test.go
  internal/resolve/resolve.go
  internal/resolve/resolve_test.go
Labels: size/XL, lgtm

#985 Enable flag validation in alpha deploy
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/testdata/corrupted-overrides.yaml
  cmd/kyma/alpha/deploy/values_test.go
Labels: size/S, lgtm

#986 Add support to pass component as URL and fix a bug
  cmd/kyma/alpha/deploy/cmd.go
  internal/component/componentlist.go
  internal/component/componentlist_test.go
  internal/component/testdata/componentlist.json
  internal/component/testdata/componentlist.yaml
Labels: size/M, lgtm

#987 Update Kyma version to 1.24.6
  .goreleaser.yml
  Makefile
Labels: size/XS, lgtm

#988 Bump reconciler dependency
  cmd/kyma/alpha/deploy/cmd.go
  go.mod
  go.sum
Labels: size/L, lgtm

#991 Change default exposed ports to 80 and 443
  cmd/kyma/provision/k3d/cmd.go
  docs/gen-docs/kyma_provision_k3d.md
Labels: size/S, lgtm

#990 add Caution note
  docs/03-03-examples-alpha.md
Labels: area/documentation, size/XS, lgtm

#989 Support passing source and workspace flag
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/alpha/deploy/opts_test.go
  docs/gen-docs/kyma_alpha_deploy.md
  go.mod
  go.sum
Labels: size/L, lgtm

#994 added dashboard URL summary for kyma deploy command
  cmd/kyma/deploy/cmd.go
  internal/nice/summary.go
Labels: size/M, lgtm

#992 Decouple Kyma version for install/upgrade command and deploy command
  .goreleaser.yml
  Makefile
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/deploy/cmd.go
  cmd/kyma/deploy/opts.go
  cmd/kyma/install/cmd.go
  cmd/kyma/install/opts.go
  cmd/kyma/upgrade/cmd.go
  cmd/kyma/upgrade/cmd_test.go
  cmd/kyma/upgrade/opts.go
  docs/gen-docs/kyma_alpha_deploy.md
  pkg/installation/opts.go
  pkg/installation/patchversion.go
  pkg/installation/patchversion_test.go
Labels: area/cli, size/L, lgtm

#993 Alpha deploy console output
  cmd/kyma/alpha/deploy/cmd.go
  go.mod
  go.sum
  internal/cli/logs.go
Labels: size/L, lgtm

#996 Download istioctl and export to EnvVar
  cmd/kyma/alpha/deploy/cmd.go
  internal/istio/istio.go
  internal/istio/istio_test.go
  internal/istio/testdata/Chart.yaml
  internal/istio/testdata/corruptedChart.yaml
  internal/istio/testdata/istio_mock.tar
  internal/istio/testdata/istio_mock.tar.gz
Labels: size/XL, lgtm

#998 Set default kyma versions in config pkg
  .goreleaser.yml
  Makefile
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/install/cmd.go
  cmd/kyma/upgrade/cmd.go
  cmd/kyma/upgrade/cmd_test.go
  docs/gen-docs/kyma_alpha_deploy.md
  internal/config/config.go
  pkg/installation/opts.go
Labels: area/cli, size/M, lgtm

#997 Add version flag
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/cmd_test.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/deploy/cmd.go
  cmd/kyma/version/cmd.go
  cmd/kyma/version/cmd_test.go
  go.mod
  internal/version/compatibility.go
  internal/version/compatibility_test.go
  internal/version/version.go
  internal/version/version_test.go
  pkg/installation/installation.go
Labels: size/XXL, lgtm

#995 Undeploy command
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  cmd/kyma/undeploy/cmd.go
  cmd/kyma/undeploy/opts.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_undeploy.md
  go.mod
  internal/kube/client.go
  internal/kube/config.go
Labels: size/L, lgtm
