Repository kyma-project/cli, pull requests merged in 2021-06, with the labels that each got.

#910 Update version to 1.23.0
  .goreleaser.yml
  Makefile
Labels: lgtm, size/XS

#909 Set fixed k3s image version
  cmd/kyma/alpha/provision/k3s/cmd.go
  cmd/kyma/alpha/provision/k3s/opts.go
  docs/gen-docs/kyma_alpha_provision_k3s.md
  internal/k3s/k3s.go
  internal/k3s/k3s_test.go
  internal/k3s/mock/k3d
Labels: lgtm, size/M

#912 Added three new Code Owners
  CODEOWNERS
  OWNERS
Labels: lgtm, size/XS

#911 Upgrade parallel-install with improvements
  go.mod
  go.sum
Labels: lgtm, size/XS

#913 updating kubernetes versions for provisioning commands
  cmd/kyma/provision/gardener/aws/cmd.go
  cmd/kyma/provision/gardener/aws/cmd_test.go
  cmd/kyma/provision/gardener/az/cmd.go
  cmd/kyma/provision/gardener/az/cmd_test.go
  cmd/kyma/provision/gardener/gcp/cmd.go
  cmd/kyma/provision/gardener/gcp/cmd_test.go
  cmd/kyma/provision/gke/cmd.go
  cmd/kyma/provision/gke/cmd_test.go
  docs/gen-docs/kyma_provision_gardener_aws.md
  docs/gen-docs/kyma_provision_gardener_az.md
  docs/gen-docs/kyma_provision_gardener_gcp.md
  docs/gen-docs/kyma_provision_gke.md
Labels: area/cli, lgtm, size/S

#916 Bump parallel-install version
  cmd/kyma/alpha/delete/cmd.go
  cmd/kyma/alpha/deploy/cmd.go
  go.mod
  go.sum
Labels: lgtm, size/S

#917 Bump parallel-install version for uninstallation improvements
  go.mod
  go.sum
Labels: lgtm, size/XS

#919 Bump parallel-install dependency
  go.mod
  go.sum
Labels: lgtm, size/XS

#920 Bump parallel-install dependency
  go.mod
  go.sum
Labels: lgtm, size/XS

#926 bump hydroform/paraller-install version
  go.mod
  go.sum
Labels: lgtm, size/XS

#927 Check for kyma v1 installation in alpha deploy
  cmd/kyma/alpha/deploy/cmd.go
Labels: lgtm, size/S

#928 Bump hydroform parallel-install dependency
  go.mod
  go.sum
Labels: lgtm, size/XS

#929 Kyma release 1.24.0-rc1 - update version
  .goreleaser.yml
  Makefile
Labels: lgtm, size/XS
