Repository kyma-project/cli, pull requests merged in 2021-07, with the labels that each got.

#932 Upgrade HydroformVersion
  go.mod
  go.sum
Labels: lgtm, size/M

#933 Bump Kyma version to 1.24.0-rc2
  .goreleaser.yml
  Makefile
Labels: lgtm, size/XS

#922 Silence deprecation warnings
  cmd/kyma/alpha/deploy/cmd.go
  pkg/installation/installation.go
Labels: lgtm, size/M

#935 Remove old verbose parameter from hydroform deployment
  cmd/kyma/alpha/deploy/cmd.go
  go.mod
  go.sum
Labels: lgtm, size/XS

#936 Update Kyma version to 1.24.0
  .goreleaser.yml
  Makefile
Labels: lgtm, size/XS

#923 Add Python39 runtime support to functions
  cmd/kyma/init/function/function.go
  cmd/kyma/run/function/function.go
  docs/03-04-function-configuration-file.md
  docs/gen-docs/kyma_init_function.md
  go.mod
  go.sum
Labels: lgtm, size/S

#940 Update hydroform/function dependencies
  go.mod
  go.sum
Labels: area/serverless, lgtm, size/XS

#942 K3S: bump version to 1.20.7
  cmd/kyma/alpha/provision/k3s/cmd.go
  docs/gen-docs/kyma_alpha_provision_k3s.md
  internal/k3s/k3s_test.go
  internal/k3s/mock/k3d
Labels: lgtm, size/S

#943 Add flag for custom port mapping in K3D
  cmd/kyma/alpha/provision/k3s/cmd.go
  cmd/kyma/alpha/provision/k3s/cmd_test.go
  cmd/kyma/alpha/provision/k3s/opts.go
  docs/gen-docs/kyma_alpha_provision_k3s.md
  docs/gen-docs/kyma_provision_minikube.md
  internal/k3s/k3s.go
  internal/k3s/k3s_test.go
  internal/k3s/mock/k3d
Labels: lgtm, size/L

#944 rephrase location flag for aks and gke
  cmd/kyma/provision/aks/cmd.go
  cmd/kyma/provision/gke/cmd.go
  docs/gen-docs/kyma_provision_aks.md
  docs/gen-docs/kyma_provision_gke.md
Labels: area/documentation, lgtm, size/XS

#946 remove doc, is obsolete with k2-0
  docs/03-03-examples-alpha.md
Labels: area/documentation, lgtm, size/L

#949 dont use existing values from helm by default
  cmd/kyma/alpha/deploy/cmd.go
  docs/gen-docs/kyma_alpha_deploy.md
Labels: lgtm, size/XS
