Repository kyma-project/cli, pull requests merged in 2021-02, with the labels that each got.

#745 Add attempts flag for provision commands
  cmd/kyma/provision/aks/cmd.go
  cmd/kyma/provision/aks/cmd_test.go
  cmd/kyma/provision/aks/opts.go
  cmd/kyma/provision/gardener/aws/cmd.go
  cmd/kyma/provision/gardener/aws/cmd_test.go
  cmd/kyma/provision/gardener/aws/opts.go
  cmd/kyma/provision/gardener/az/cmd.go
  cmd/kyma/provision/gardener/az/cmd_test.go
  cmd/kyma/provision/gardener/az/opts.go
  cmd/kyma/provision/gardener/gcp/cmd.go
  cmd/kyma/provision/gardener/gcp/cmd_test.go
  cmd/kyma/provision/gardener/gcp/opts.go
  cmd/kyma/provision/gke/cmd.go
  cmd/kyma/provision/gke/cmd_test.go
  cmd/kyma/provision/gke/opts.go
  docs/gen-docs/kyma_provision_aks.md
  docs/gen-docs/kyma_provision_gardener_aws.md
  docs/gen-docs/kyma_provision_gardener_az.md
  docs/gen-docs/kyma_provision_gardener_gcp.md
  docs/gen-docs/kyma_provision_gke.md
Labels: area/cli

#753 Fixing missing logs in prow jobs
  cmd/kyma/test/logs/cmd.go
Labels: area/cli, bug

#761 Add info about profiles to the CLI docs
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/install/cmd.go
  cmd/kyma/upgrade/cmd.go
  docs/gen-docs/kyma_alpha_deploy.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_upgrade.md
Labels: area/documentation, enhancement

#763 Manage global overrides in hydroform
  cmd/kyma/alpha/delete/cmd.go
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/alpha/deploy/opts_test.go
  docs/gen-docs/kyma_alpha_delete.md
  docs/gen-docs/kyma_alpha_deploy.md
  go.mod
  go.sum
  internal/cli/logs.go
  pkg/git/git_test.go
  pkg/step/log.go
Labels: area/cli, area/installation

#765 Mask overrides in logs + fix error when dex is missing
  cmd/kyma/alpha/deploy/cmd.go
  go.mod
  go.sum
Labels: area/cli, area/installation

#766 Support remote locations for override-files and component-list
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/alpha/deploy/opts_test.go
  docs/gen-docs/kyma_alpha_deploy.md
  internal/download/download.go
  internal/download/download_test.go
  pkg/installation/utils.go
Labels: area/cli, area/installation

#767 Bump hydroform lib
  cmd/kyma/alpha/delete/cmd.go
  cmd/kyma/alpha/deploy/cmd.go
  go.mod
  go.sum
Labels: area/cli, area/documentation

#774 Use --disble instead of --no-deploy (deprecated)
  internal/k3s/k3s.go
  internal/k3s/mock/k3d
Labels: area/cli, area/installation

#772 Try to resolve local kyma source directory when using --source=local
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
Labels: area/cli, area/installation

#717 Run functions locally
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  cmd/kyma/run/function/function.go
  cmd/kyma/run/function/function_test.go
  cmd/kyma/run/function/opts.go
  cmd/kyma/run/run.go
  cmd/kyma/run/run_test.go
  cmd/main.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_run.md
  docs/gen-docs/kyma_run_function.md
  go.mod
  go.sum
  internal/cli/finalizers.go
  internal/cli/finalizers_test.go
  internal/cli/options.go
Labels: area/serverless, enhancement

#781 Send error updates
  go.mod
  go.sum
  pkg/asyncui/asyncui.go
Labels: area/cli, area/documentation
