Repository kyma-project/cli, pull requests merged in 2021-05, with the labels that each got.

#885 Enriched CLI help for alpha deploy command
  cmd/kyma/alpha/deploy/cmd.go
  docs/gen-docs/kyma_alpha_deploy.md
Labels: area/cli, lgtm, size/L

#880 Change master to main (leftovers)
  docs/03-04-function-configuration-file.md
Labels: lgtm, size/XS

#888 fix command completion
  cmd/kyma/completion/cmd.go
Labels: lgtm, size/XS

#886 Change kyma_version to 1.22.0
  .goreleaser.yml
  Makefile
Labels: lgtm, size/XS

#890 Uninstall Kyma namespaces
  cmd/kyma/alpha/delete/cmd.go
  go.mod
  go.sum
Labels: lgtm, size/M

#891 Use k3d registry for serverless functions
  go.mod
  go.sum
  internal/k3s/k3s.go
  internal/k3s/mock/k3d
Labels: lgtm, size/S

#887 Add terraform debug option and abstract provision template
  cmd/kyma/provision/aks/cmd.go
  cmd/kyma/provision/aks/cmd_test.go
  cmd/kyma/provision/aks/template.go
  cmd/kyma/provision/gardener/aws/cmd.go
  cmd/kyma/provision/gardener/aws/cmd_test.go
  cmd/kyma/provision/gardener/aws/template.go
  cmd/kyma/provision/gardener/az/cmd.go
  cmd/kyma/provision/gardener/az/cmd_test.go
  cmd/kyma/provision/gardener/az/template.go
  cmd/kyma/provision/gardener/gcp/cmd.go
  cmd/kyma/provision/gardener/gcp/cmd_test.go
  cmd/kyma/provision/gardener/gcp/template.go
  cmd/kyma/provision/gke/cmd.go
  cmd/kyma/provision/gke/cmd_test.go
  cmd/kyma/provision/gke/template.go
  cmd/kyma/provision/run_template.go
  go.mod
  go.sum
Labels: lgtm, size/XXL

#895 Bump hydroform dependency to include further cr removals
  go.mod
  go.sum
Labels: lgtm, size/XS

#883 Allow #836 CLI patch releases
  Makefile
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/install/cmd.go
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision_minikube.md
  hack/verify-generated-docs.sh
  pkg/installation/patchversion.go
  pkg/installation/patchversion_test.go
Labels: lgtm, size/L

#894 Support comma separated list for override values
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/cmd_test.go
  docs/gen-docs/kyma_alpha_deploy.md
Labels: lgtm, size/M

#902 Circumvent kyma version backtracking for releases
  .goreleaser.yml
  Makefile
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/install/cmd.go
  cmd/kyma/install/opts.go
  pkg/installation/patchversion.go
Labels: lgtm, size/M

#901 Add file for kyma2 specific overrides
  cmd/kyma/alpha/deploy/cmd.go
Labels: lgtm, size/XS

#898 Upgrade hydroform/function dependencies
  go.mod
  go.sum
Labels: area/serverless, bug, lgtm, size/XS

#900 Release - set version to 1.23.0-rc2
  .goreleaser.yml
  Makefile
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/install/cmd.go
  cmd/kyma/install/opts.go
  pkg/installation/patchversion.go
Labels: lgtm, size/M

#905 Add hint about hosts file if local.kyma.dev not resolvable
  cmd/kyma/alpha/deploy/cmd.go
  internal/hosts/domains.go
Labels: lgtm, size/M

#906 Upgrade hydroform with deploy/delete improvements
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  go.mod
  go.sum
Labels: lgtm, size/M
