Repository kyma-project/cli, pull requests merged in 2021-10, with the labels that each got.

#1000 Remove Alpha Flavour
  cmd/kyma/alpha/cmd.go
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/cmd_test.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/alpha/deploy/opts_test.go
  cmd/kyma/delete/cmd.go
  cmd/kyma/delete/opts.go
  cmd/kyma/deploy/cmd.go
  cmd/kyma/deploy/cmd_test.go
  cmd/kyma/deploy/compatibility.go
  cmd/kyma/deploy/compatibility_test.go
  cmd/kyma/deploy/opts.go
  cmd/kyma/deploy/opts_test.go
  cmd/kyma/deploy/testdata/corrupted-overrides.yaml
  cmd/kyma/deploy/testdata/dummy.txt
  cmd/kyma/deploy/testdata/fake.crt
  cmd/kyma/deploy/testdata/fake.key
  cmd/kyma/deploy/testdata/valid-overrides-1.yaml
  cmd/kyma/deploy/testdata/valid-overrides-2.yaml
  cmd/kyma/deploy/testdata/values.yaml
  cmd/kyma/deploy/tmp/valid-overrides-1.yaml
  cmd/kyma/deploy/values.go
  cmd/kyma/deploy/values_test.go
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_alpha.md
  docs/gen-docs/kyma_alpha_deploy.md
  docs/gen-docs/kyma_delete.md
  docs/gen-docs/kyma_deploy.md
  go.mod
  go.sum
  pkg/asyncui/asyncui.go
  pkg/asyncui/asyncui_test.go
Labels: size/XXL, lgtm

#1002 Bump reconciler dependency
  go.mod
  go.sum
Labels: size/XS, lgtm

#1003 Add lindnerby to code owners
  CODEOWNERS
Labels: size/XS, lgtm

#1004 Less user interaction in deploy cmd
  cmd/kyma/deploy/cmd.go
  cmd/kyma/deploy/cmd_test.go
Labels: area/cli, size/L, lgtm

#1005 Change version cmd output
  cmd/kyma/version/cmd.go
Labels: area/cli, size/XS, lgtm

#999 Add dashboard command
  cmd/kyma/dashboard/cmd.go
  cmd/kyma/dashboard/opts.go
  cmd/kyma/dashboard/opts_test.go
  cmd/kyma/deploy/cmd.go
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_dashboard.md
  go.mod
  pkg/docker/docker.go
  pkg/docker/docker_test.go
  pkg/docker/mocks/Client.go
Labels: area/cli, size/XL, lgtm

#1007 Improve error handling of workspace fetching
  cmd/kyma/deploy/cmd.go
Labels: size/XS, lgtm

#1011 remove parallel-install dependency
  go.mod
  go.sum
  internal/k3d/utils.go
  internal/values/interceptors_test.go
  pkg/installation/utils.go
Labels: size/M, lgtm

#1012 Rename k3s to k3d in the cmd output
  cmd/kyma/provision/k3d/cmd.go
Labels: size/XS, lgtm

#1010 removing ingress.domainName
  internal/values/builder_test.go
  internal/values/interceptors_test.go
  internal/values/testdata/deployment-global-values-for-remote-cluster.yaml
  internal/values/testdata/deployment-global-values.yaml
  internal/values/values.go
  internal/values/values_test.go
Labels: size/M, lgtm

#1013 Add waiting for kyma-system namespace deletion
  cmd/kyma/deploy/cmd.go
  cmd/kyma/deploy/cmd_test.go
  cmd/kyma/undeploy/cmd.go
Labels: area/cli, size/L, lgtm

#1009 Validate source flag for install and deploy if using kyma versions
  cmd/kyma/deploy/cmd.go
  cmd/kyma/deploy/opts.go
  cmd/kyma/install/cmd.go
  cmd/kyma/install/opts.go
  internal/version/version.go
Labels: area/cli, size/M, lgtm

#1015 Bump recon deps
  go.mod
  go.sum
Labels: size/XS, lgtm

#1021 Temporarily comment out the lastest available main hash test
  pkg/installation/utils_test.go
Labels: size/S, lgtm

#1014 Remove import certs from deploy time
  cmd/kyma/deploy/cmd.go
Labels: size/XS, lgtm
