Repository kyma-project/cli, pull requests merged in 2021-12, with the labels that each got.

#1106 Bump reconciler
  go.mod
  go.sum
Labels: size/S, lgtm

#1107 Bump reconciler to latest commit
  go.mod
  go.sum
Labels: size/XS, lgtm

#1105 Root access error message as per OS
  cmd/kyma/import/certs/cmd.go
  cmd/kyma/import/hosts/cmd.go
  internal/hosts/hosts_others.go
  internal/root/root_others.go
  internal/root/root_windows.go
  internal/trust/trust_darwin.go
  internal/trust/trust_linux.go
  internal/trust/trust_windows.go
Labels: size/M, lgtm

#1108 Remove k3d dead code
  cmd/kyma/provision/k3d/cmd.go
  internal/k3d/k3d.go
  internal/k3d/k3d_test.go
Labels: area/cli, size/L, lgtm

#1110 Upgrade to reconciler lib 2021-12-02 feb4fbd78a3
  go.mod
  go.sum
Labels: size/XS, lgtm

#1113 Fix injecting envs to the function run locally
  cmd/kyma/run/function/function.go
Labels: bug, area/serverless, size/XS, lgtm

#1114 Update Kyma version to 2.0.0
  internal/config/config.go
Labels: size/XS, lgtm

#1115 Update docs
  docs/gen-docs/kyma_deploy.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_upgrade.md
Labels: size/XS, lgtm

#1119 Use relative links to md files
  cmd/gendocs/gendocs.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_apply.md
  docs/gen-docs/kyma_apply_function.md
  docs/gen-docs/kyma_completion.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_create.md
  docs/gen-docs/kyma_create_system.md
  docs/gen-docs/kyma_dashboard.md
  docs/gen-docs/kyma_deploy.md
  docs/gen-docs/kyma_import.md
  docs/gen-docs/kyma_import_certs.md
  docs/gen-docs/kyma_import_hosts.md
  docs/gen-docs/kyma_init.md
  docs/gen-docs/kyma_init_function.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_aks.md
  docs/gen-docs/kyma_provision_gardener.md
  docs/gen-docs/kyma_provision_gardener_aws.md
  docs/gen-docs/kyma_provision_gardener_az.md
  docs/gen-docs/kyma_provision_gardener_gcp.md
  docs/gen-docs/kyma_provision_gke.md
  docs/gen-docs/kyma_provision_k3d.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_run.md
  docs/gen-docs/kyma_run_function.md
  docs/gen-docs/kyma_sync.md
  docs/gen-docs/kyma_sync_function.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_logs.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_undeploy.md
  docs/gen-docs/kyma_upgrade.md
  docs/gen-docs/kyma_version.md
Labels: size/L, lgtm

#1121 add unstable build download link to README.md
  README.md
Labels: size/S, lgtm

#1109 Add support for reconciler delete feature
  cmd/kyma/deploy/cmd.go
  cmd/kyma/deploy/opts.go
  cmd/kyma/deploy/opts_test.go
  cmd/kyma/undeploy/cmd.go
  cmd/kyma/undeploy/opts.go
  docs/gen-docs/kyma_undeploy.md
  go.mod
  go.sum
  internal/deploy/component/list.go
  internal/deploy/deploy.go
  internal/deploy/deploy_test.go
  internal/deploy/workspace.go
  internal/deploy/workspace_test.go
  internal/nice/summary.go
Labels: size/XL, lgtm

#1124 Upgrade to latest reconciler-lib 943e0e86f997f8d4604
  go.mod
  go.sum
Labels: lgtm

#1125 provision k3d: print hint in 'permission denied to allocate ports' scenario
  cmd/kyma/provision/k3d/cmd.go
Labels: size/XS, lgtm

#1126 Bump reconciler
  go.mod
  go.sum
Labels: size/XS, lgtm

#1129 Bump Reconciler to the latest version
  go.mod
  go.sum
Labels: area/cli, size/XS, lgtm
