Repository kyma-project/cli, pull requests merged in 2021-03, with the labels that each got.

#779 Rename Options to Flags
  cmd/gendocs/gendocs.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_alpha.md
  docs/gen-docs/kyma_alpha_delete.md
  docs/gen-docs/kyma_alpha_deploy.md
  docs/gen-docs/kyma_alpha_provision.md
  docs/gen-docs/kyma_alpha_provision_k3s.md
  docs/gen-docs/kyma_alpha_version.md
  docs/gen-docs/kyma_apply.md
  docs/gen-docs/kyma_apply_function.md
  docs/gen-docs/kyma_completion.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_create.md
  docs/gen-docs/kyma_create_system.md
  docs/gen-docs/kyma_init.md
  docs/gen-docs/kyma_init_function.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_aks.md
  docs/gen-docs/kyma_provision_gardener.md
  docs/gen-docs/kyma_provision_gardener_aws.md
  docs/gen-docs/kyma_provision_gardener_az.md
  docs/gen-docs/kyma_provision_gardener_gcp.md
  docs/gen-docs/kyma_provision_gke.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_run.md
  docs/gen-docs/kyma_run_function.md
  docs/gen-docs/kyma_sync.md
  docs/gen-docs/kyma_sync_function.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_logs.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  docs/gen-docs/kyma_upgrade.md
  docs/gen-docs/kyma_version.md
Labels: area/cli, area/documentation

#785 Bump gardenlinux version
  cmd/kyma/provision/gardener/aws/cmd.go
  cmd/kyma/provision/gardener/aws/cmd_test.go
  cmd/kyma/provision/gardener/az/cmd.go
  cmd/kyma/provision/gardener/az/cmd_test.go
  cmd/kyma/provision/gardener/gcp/cmd.go
  cmd/kyma/provision/gardener/gcp/cmd_test.go
Labels: area/ci, test-failing

#789 Fix failing test: TestFinalizer_SetupCloseHandler
  internal/cli/finalizers_test.go
Labels: area/serverless, test-failing

#760 Hot deployment function code
  cmd/kyma/run/function/function.go
  cmd/kyma/run/function/function_test.go
  cmd/kyma/run/function/opts.go
  docs/08-03-debug-function.md
  docs/10-01-sudden-container-failure.md
  docs/10-02-debugger-in-strange-location.md
  docs/gen-docs/kyma_run_function.md
  go.mod
  go.sum
Labels: area/serverless

#764 Alpha cli usage examples
  docs/03-03-examples-alpha.md
Labels: area/cli, area/documentation, area/installation

#799 Print steps for deploying prerequisite components
  go.mod
  go.sum
  pkg/asyncui/asyncui.go
Labels: area/cli, area/installation

#775 Add auto generated name for function
  cmd/kyma/init/function/function.go
  cmd/kyma/init/function/function_test.go
  cmd/kyma/init/function/opts.go
  docs/gen-docs/kyma_init_function.md
  go.mod
  go.sum
Labels: area/serverless

#806 Adapt function CLI to new event mesh
  cmd/kyma/apply/function/function.go
  go.mod
  go.sum
Labels: area/serverless

#812 Use downloader from installer library
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  docs/gen-docs/kyma_alpha_deploy.md
  go.mod
  go.sum
  internal/download/download.go
  internal/download/download_test.go
  pkg/deploy/clonesources.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/installation/utils.go
Labels: area/cli, area/installation

#829 Fix docs preview
  .kyma-project-io/build-preview.sh
Labels: WIP
