Repository kyma-project/cli, pull requests merged in 2022-10, with the labels that each got.

#1406 fix makefile auth
  Makefile
Labels: size/XS, lgtm

#1398 Gke cni overrides
  internal/clusterinfo/clusterinfo.go
  internal/clusterinfo/clusterinfo_test.go
  internal/clusterinfo/gke.go
  internal/deploy/values/builder.go
  internal/deploy/values/values.go
  internal/deploy/values/values_test.go
Labels: size/L, lgtm

#1407 Bump reconciler deps to fix kyma undeploy
  go.mod
  go.sum
Labels: size/XS, lgtm

#1405 Bump Helm version to 3.9.4
  go.mod
  go.sum
Labels: size/XS, lgtm

#1408 Complete first fully functional deploy cmd
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  docs/gen-docs/kyma_alpha_deploy.md
  internal/deploy/bootstrap.go
  internal/deploy/bootstrap_test.go
  internal/deploy/kyma.go
  internal/deploy/operator.go
  internal/kube/client.go
  internal/kube/client_test.go
  internal/kube/kube.go
  internal/kube/mocks/KymaKube.go
  internal/kustomize/kustomize.go
  internal/kustomize/kustomize_test.go
  internal/nice/summary.go
  pkg/errs/multierror.go
  pkg/errs/multierror_test.go
  pkg/module/template.go
  template.yaml
Labels: size/XL, lgtm

#1379 Feature/cr validation
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/opts.go
  docs/gen-docs/kyma_alpha_create_module.md
  go.mod
  go.sum
  internal/envtest/envtest.go
  internal/kube/client.go
  pkg/module/validation.go
  pkg/module/validation_test.go
Labels: area/cli, area/installation, size/XL, lgtm

#1411 Remove init module cmd
  cmd/kyma/alpha/alpha.go
  cmd/kyma/alpha/init/init.go
  cmd/kyma/alpha/init/module/module.go
  cmd/kyma/alpha/init/module/opts.go
  docs/gen-docs/kyma_alpha.md
  docs/gen-docs/kyma_alpha_init.md
  docs/gen-docs/kyma_alpha_init_module.md
  pkg/module/scaffold/builder.go
  pkg/module/scaffold/init.go
  pkg/module/scaffold/resources/README.md
  pkg/module/scaffold/resources/config.yaml
  pkg/module/scaffold/resources/default.yaml
Labels: size/L, lgtm

#1414 Sanitize envtest version
  internal/envtest/envtest.go
Labels: size/M, lgtm

#1415 Update default K8s version in the "kyma provision" command
  cmd/kyma/provision/cmd.go
  cmd/kyma/provision/gardener/aws/cmd.go
  cmd/kyma/provision/gardener/aws/cmd_test.go
  cmd/kyma/provision/gardener/az/cmd.go
  cmd/kyma/provision/gardener/az/cmd_test.go
  cmd/kyma/provision/gardener/gcp/cmd.go
  cmd/kyma/provision/gardener/gcp/cmd_test.go
  cmd/kyma/provision/k3d/cmd.go
  docs/gen-docs/kyma_provision_gardener_aws.md
  docs/gen-docs/kyma_provision_gardener_az.md
  docs/gen-docs/kyma_provision_gardener_gcp.md
  docs/gen-docs/kyma_provision_k3d.md
  internal/clusterinfo/clusterinfo_test.go
Labels: size/M, lgtm

#1418 CVE-2022-32149, update hydroform and reconciler dependencies
  go.mod
  go.sum
Labels: size/S, lgtm

#1419 Bumped reconciler
  go.mod
  go.sum
Labels: size/XS, lgtm

#1421 Prepare release 2.8
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1424 Remove extra arguments
  cmd/kyma/deploy/cmd.go
Labels: size/XS, lgtm

#1420 create mod: native support kubebuilder projects
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/opts.go
  cmd/kyma/alpha/deploy/cmd.go
  docs/gen-docs/kyma_alpha_create_module.md
  go.mod
  go.sum
  internal/config/config.go
  internal/envtest/envtest.go
  internal/kustomize/kustomize.go
  pkg/module/kubebuilder/chart.go
  pkg/module/kubebuilder/project.go
  pkg/module/kubebuilder/project_test.go
  pkg/module/layer.go
  pkg/module/resources.go
  pkg/module/template.go
  pkg/module/validation.go
  template.yaml
Labels: size/XL, lgtm

#1426 Start relese 2.8.1
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1425 Feature/managed cluster deploy warning
  cmd/kyma/deploy/cmd.go
  cmd/kyma/undeploy/cmd.go
  internal/cli/managed.go
  internal/clusterinfo/clusterinfo.go
Labels: area/cli, area/installation, size/M, lgtm

#1417 remove deprecated nodejs12
  cmd/kyma/init/function/function.go
  cmd/kyma/run/function/function.go
  docs/gen-docs/kyma_init_function.md
  go.mod
  go.sum
Labels: size/S, lgtm

#1429 updated codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#1430 If CI mode enabled, disable DetectManagedEnvironmentCheck
  cmd/kyma/deploy/cmd.go
  cmd/kyma/undeploy/cmd.go
  internal/root/root.go
Labels: size/S, lgtm
