Repository kyma-project/cli, pull requests merged in 2022-03, with the labels that each got.

#1195 Deps upgrade
  go.mod
  go.sum
Labels: size/M, lgtm

#1196 dasboard cmd: don't change network mode to 'host' if using WSL
  cmd/kyma/dashboard/cmd.go
Labels: size/S, lgtm

#1191 Update stale.yml
  .github/stale.yml
Labels: size/XS, lgtm

#1197 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#1202 migrate from CODEOWNERS to OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: size/M, lgtm

#1192 Implement dry-run mode
  cmd/kyma/deploy/cmd.go
  cmd/kyma/deploy/opts.go
  docs/gen-docs/kyma_deploy.md
  go.mod
  go.sum
  internal/deploy/deploy.go
  internal/deploy/workspace.go
Labels: size/L, lgtm

#1207 chore: adopt state to be in progress for run in reconciler
  go.mod
  go.sum
  internal/deploy/deploy.go
  internal/deploy/deploy_test.go
Labels: size/M, lgtm

#1211 Bump reconciler with fix to Istio upgrade on 1.12
  go.mod
  go.sum
Labels: size/S, lgtm

#1212 Remove @shorim and @alexandra-simeonova from codeowners file
  CODEOWNERS
Labels: size/XS, lgtm

#1203 adjust OWNERS
  .kyma-project-io/build-preview.sh
  .kyma-project-io/docs-commands-cag.yaml
  .kyma-project-io/docs-overview-cag.yaml
  OWNERS
  OWNERS_ALIASES
  docs/OWNERS
Labels: size/L, lgtm

#1201 Refactor Istio-configuration Helm chart
  internal/deploy/istioctl/istio.go
  internal/deploy/istioctl/testdata/Chart.yaml
  internal/deploy/istioctl/testdata/corruptedChart.yaml
Labels: size/XS, lgtm, area/service-mesh

#1213 Revert "Refactor Istio-configuration Helm chart"
  internal/deploy/istioctl/istio.go
  internal/deploy/istioctl/testdata/Chart.yaml
  internal/deploy/istioctl/testdata/corruptedChart.yaml
Labels: size/XS, lgtm

#1214 Set the Istio Chart path
  internal/deploy/istioctl/istio.go
  internal/deploy/istioctl/istio_test.go
  internal/deploy/istioctl/testdata/default/resources/istio/Chart.yaml
  internal/deploy/istioctl/testdata/new/resources/istio-configuration/Chart.yaml
  internal/deploy/istioctl/testdata/new/resources/istio/Chart.yaml
  internal/deploy/istioctl/testdata/old/resources/istio-configuration/Chart.yaml
Labels: size/M, lgtm

#1216 Bump CLI with Istio reconciler changes
  go.mod
  go.sum
Labels: size/XS, lgtm

#1200 Add serverless JSON schema generation
  cmd/kyma/get/get.go
  cmd/kyma/get/schema/ops.go
  cmd/kyma/get/schema/schema.go
  cmd/kyma/get/schema/schema_test.go
  cmd/kyma/get/schema/schema_testxit
  cmd/kyma/init/function/function.go
  cmd/kyma/init/function/function_test.go
  cmd/kyma/init/function/opts.go
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_get.md
  docs/gen-docs/kyma_get_schema.md
  docs/gen-docs/kyma_init_function.md
  go.mod
  go.sum
  pkg/serverless/schema_file.go
  pkg/vscode/workspace.go
  pkg/vscode/workspace_test.go
Labels: area/cli, area/serverless, size/L, lgtm

#1219 refactor: remove terraform from the CLI
  cmd/kyma/kyma.go
  cmd/kyma/provision/aks/cmd.go
  cmd/kyma/provision/aks/cmd_test.go
  cmd/kyma/provision/aks/opts.go
  cmd/kyma/provision/aks/template.go
  cmd/kyma/provision/gardener/aws/cmd.go
  cmd/kyma/provision/gardener/aws/cmd_test.go
  cmd/kyma/provision/gardener/aws/opts.go
  cmd/kyma/provision/gardener/aws/template.go
  cmd/kyma/provision/gardener/az/cmd.go
  cmd/kyma/provision/gardener/az/cmd_test.go
  cmd/kyma/provision/gardener/az/opts.go
  cmd/kyma/provision/gardener/az/template.go
  cmd/kyma/provision/gardener/gcp/cmd.go
  cmd/kyma/provision/gardener/gcp/cmd_test.go
  cmd/kyma/provision/gardener/gcp/opts.go
  cmd/kyma/provision/gardener/gcp/template.go
  cmd/kyma/provision/gke/cmd.go
  cmd/kyma/provision/gke/cmd_test.go
  cmd/kyma/provision/gke/opts.go
  cmd/kyma/provision/gke/template.go
  cmd/kyma/undeploy/cmd.go
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_aks.md
  docs/gen-docs/kyma_provision_gardener_aws.md
  docs/gen-docs/kyma_provision_gardener_az.md
  docs/gen-docs/kyma_provision_gardener_gcp.md
  docs/gen-docs/kyma_provision_gke.md
  docs/gen-docs/kyma_undeploy.md
  go.mod
  go.sum
Labels: area/documentation, size/XXL, lgtm

#1218 Extend dry-run description
  cmd/kyma/deploy/cmd.go
  docs/gen-docs/kyma_deploy.md
Labels: area/documentation, size/XS, lgtm

#1217 chmod +x to istoctl, more debug infos, minor improvements
  cmd/kyma/deploy/cmd.go
  cmd/kyma/provision/minikube/cfg_darwin.go
  cmd/kyma/provision/minikube/cfg_others.go
  cmd/kyma/provision/minikube/cfg_windows.go
  cmd/kyma/undeploy/cmd.go
  go.mod
  go.sum
  internal/deploy/istioctl/istio.go
  internal/deploy/istioctl/istio_test.go
  internal/hosts/cfg_windows.go
  internal/hosts/hosts_windows.go
  internal/root/root_others.go
  internal/root/root_windows.go
  internal/trust/trust_darwin.go
  internal/trust/trust_linux.go
  internal/trust/trust_windows.go
Labels: size/M, lgtm, release blocker

#1222 set kyma version
  docs/gen-docs/kyma_deploy.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_upgrade.md
  internal/config/config.go
Labels: area/documentation, size/S, lgtm

#1224 Update golang linter
  cmd/kyma/create/system/system.go
  cmd/kyma/deploy/cmd.go
  cmd/kyma/import/certs/cmd.go
  cmd/kyma/undeploy/cmd.go
  hack/verify-lint.sh
Labels: size/S, lgtm

#1223 Upgrade the `hydroform/function` deps
  go.mod
  go.sum
Labels: area/serverless, size/XS, lgtm

#1226 Update gardener to latest release from provision
  go.mod
  go.sum
Labels: size/S, lgtm

#1227 cherry-pick: Update golang linter
  cmd/kyma/create/system/system.go
  cmd/kyma/deploy/cmd.go
  cmd/kyma/import/certs/cmd.go
  cmd/kyma/undeploy/cmd.go
  hack/verify-lint.sh
Labels: area/documentation, size/S, lgtm

#1225 update to kyma 2.1.1
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: area/documentation, size/XS, lgtm
