Repository kyma-project/cli, pull requests merged in 2022-09, with the labels that each got.

#1357 rename kyma-operator => lifecycle-manager
  pkg/module/template.go
Labels: size/XS, lgtm

#1371 Bump reconciler
  go.mod
  go.sum
Labels: size/XS, lgtm

#1370 Integrate Kustomize
  cmd/kyma/alpha/alpha.go
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/alpha/deploy/opts_test.go
  docs/gen-docs/kyma_alpha.md
  docs/gen-docs/kyma_alpha_deploy.md
  internal/channels/merge.go
  internal/cli/exec.go
  internal/cli/exec_test.go
  internal/config/config.go
  internal/deploy/operator.go
  internal/deploy/workspace.go
  internal/deploy/workspace_test.go
  internal/k3d/mocks/cmd_runner.go
  internal/k3d/mocks/path_looker.go
  internal/kube/client.go
  internal/kube/kube.go
  internal/kube/mocks/KymaKube.go
  internal/kustomize/kustomize.go
  internal/nice/summary.go
  pkg/docker/mocks/Client.go
Labels: size/XL, lgtm

#1372 Bump reconciler with support of Istio sidecar pod labels
  go.mod
  go.sum
Labels: size/XS, lgtm

#1374 Add anoipm as codeowner
  CODEOWNERS
Labels: size/XS, lgtm

#1377 Bump istio to 1.14.4
  go.mod
  go.sum
Labels: size/XS, lgtm

#1382 Fix linter
  cmd/kyma/alpha/create/create.go
  cmd/kyma/alpha/init/init.go
  cmd/kyma/alpha/init/module/opts.go
  cmd/kyma/alpha/unpack/module/module.go
  cmd/kyma/alpha/unpack/module/opts.go
  cmd/kyma/alpha/unpack/unpack.go
  cmd/kyma/alpha/verify/module/module.go
  cmd/kyma/alpha/verify/module/opts.go
  cmd/kyma/alpha/verify/verify.go
  cmd/kyma/apply/apply.go
  cmd/kyma/apply/function/function.go
  cmd/kyma/apply/function/opts.go
  cmd/kyma/create/create.go
  cmd/kyma/create/system/opts.go
  cmd/kyma/create/system/system.go
  cmd/kyma/dashboard/cmd.go
  cmd/kyma/dashboard/opts.go
  cmd/kyma/deploy/opts.go
  cmd/kyma/get/get.go
  cmd/kyma/get/schema/schema.go
  cmd/kyma/import/cmd.go
  cmd/kyma/import/hosts/cmd.go
  cmd/kyma/init/function/function.go
  cmd/kyma/init/function/opts.go
  cmd/kyma/init/init.go
  cmd/kyma/kyma.go
  cmd/kyma/provision/cmd.go
  cmd/kyma/provision/gardener/aws/opts.go
  cmd/kyma/provision/gardener/az/cmd.go
  cmd/kyma/provision/gardener/az/opts.go
  cmd/kyma/provision/gardener/cmd.go
  cmd/kyma/provision/gardener/gcp/cmd.go
  cmd/kyma/provision/gardener/gcp/opts.go
  cmd/kyma/provision/k3d/cmd.go
  cmd/kyma/provision/k3d/opts.go
  cmd/kyma/run/function/function.go
  cmd/kyma/run/function/opts.go
  cmd/kyma/run/run.go
  cmd/kyma/sync/function/function.go
  cmd/kyma/sync/function/opts.go
  cmd/kyma/sync/sync.go
  cmd/kyma/undeploy/opts.go
  cmd/kyma/version/cmd.go
  cmd/kyma/version/opts.go
  hack/verify-lint.sh
  internal/cli/logs.go
  internal/cli/options.go
  internal/clusterinfo/clusterinfo.go
  internal/k3d/cluster.go
  internal/k3d/k3d.go
  internal/k3d/registry.go
  internal/version/version.go
  pkg/docker/docker.go
  pkg/step/factory.go
Labels: area/ci, size/L, lgtm

#1384 Start release 2.7.
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1386 Switch to goreleaser changelogs
  .goreleaser.yml
  hack/release.sh
Labels: size/M, lgtm

#1387 Switch to goreleaser changelogs (#1386)
  .goreleaser.yml
  hack/release.sh
Labels: size/M, lgtm

#1383 Add value for istio specifying k3d as deployment
  internal/deploy/values/builder.go
  internal/deploy/values/values.go
  internal/deploy/values/values_test.go
Labels: size/M, lgtm

#1388 Support istio 1-15-0
  go.mod
  go.sum
Labels: size/XS, lgtm

#1391 Bump reconciler image
  go.mod
  go.sum
Labels: size/XS, lgtm

#1392 Add GCloud authentication
  Makefile
Labels: size/XS, lgtm

#1394 Fix GCloud authentication
  Makefile
Labels: size/XS, lgtm

#1395 Fix post-kyma-cli job
  Makefile
Labels: size/XS, lgtm

#1397 GCloud auth: use correct if
  Makefile
Labels: size/XS, lgtm

#1399 change logic of Makefile
  Makefile
Labels: size/XS, lgtm

#1400 add ifdef to gcp-authenticate
  Makefile
Labels: size/XS, lgtm

#1401 fix makefile auth - hacky solution
  Makefile
Labels: size/XS, lgtm
