Repository kyma-project/cli, pull requests merged in 2022-02, with the labels that each got.

#1170 bumped reconciler to latest
  go.mod
  go.sum
  internal/deploy/deploy.go
Labels: size/XS, lgtm

#1169 Clean up CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#1171 Publish unstable binaries only when UNSTABLE=true
  Makefile
Labels: area/cli, size/XS, lgtm

#1172 Bump Reconciler dependency to include Istio reconciler changes
  go.mod
  go.sum
Labels: size/XS, lgtm

#1174 bump reconciler
  go.mod
  go.sum
  pkg/installation/installation_test.go
  pkg/installation/utils_test.go
Labels: size/S, lgtm

#1176 Bump Reconciler dependency to include Istio reconciler changes
  go.mod
  go.sum
Labels: area/cli, size/XS, lgtm

#1047 Remove python38
  cmd/kyma/init/function/function.go
  cmd/kyma/init/function/function_test.go
  docs/gen-docs/kyma_init_function.md
  go.mod
  go.sum
Labels: size/S, lgtm

#1179 bump reconciler dependency
  go.mod
  go.sum
Labels: size/XS, lgtm

#1181 undeply: detect source kyma version from cluster
  cmd/kyma/undeploy/cmd.go
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_undeploy.md
  go.mod
  go.sum
  internal/version/version.go
Labels: size/M, lgtm

#1183 Bump reconciler
  go.mod
  go.sum
Labels: size/XS, lgtm

#1184 Backport reconciler updates
  go.mod
  go.sum
  internal/deploy/deploy.go
  pkg/installation/installation_test.go
  pkg/installation/utils_test.go
Labels: size/S, lgtm

#1185 Update default k8s
  cmd/kyma/provision/aks/cmd.go
  cmd/kyma/provision/aks/cmd_test.go
  cmd/kyma/provision/gardener/aws/cmd.go
  cmd/kyma/provision/gardener/aws/cmd_test.go
  cmd/kyma/provision/gardener/az/cmd.go
  cmd/kyma/provision/gardener/az/cmd_test.go
  cmd/kyma/provision/gardener/gcp/cmd.go
  cmd/kyma/provision/gardener/gcp/cmd_test.go
  cmd/kyma/provision/gke/cmd.go
  cmd/kyma/provision/gke/cmd_test.go
  cmd/kyma/provision/k3d/cmd.go
  docs/gen-docs/kyma_provision_aks.md
  docs/gen-docs/kyma_provision_gardener_aws.md
  docs/gen-docs/kyma_provision_gardener_az.md
  docs/gen-docs/kyma_provision_gardener_gcp.md
  docs/gen-docs/kyma_provision_gke.md
  docs/gen-docs/kyma_provision_k3d.md
Labels: size/M, lgtm

#1186 Updated default version for install command
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_upgrade.md
  internal/config/config.go
  pkg/installation/installation_test.go
  pkg/installation/utils_test.go
Labels: size/S, lgtm

#1187 Bump reconciler to get fix in delete race condition
  go.mod
  go.sum
Labels: size/XS, lgtm

#1190 Bump Reconciler dependency to include Istio reconciler changes
  go.mod
  go.sum
Labels: size/XS, lgtm

#1188 Add support for external components
  cmd/kyma/deploy/cmd.go
  docs/gen-docs/kyma_deploy.md
  internal/deploy/component/list.go
  internal/deploy/component/list_test.go
  internal/deploy/component/testdata/components.json
  internal/deploy/component/testdata/components.yaml
  internal/deploy/component/testdata/components.yml
Labels: size/L, lgtm

#1194 bump reconciler to include functionalities required for istio 1.12.x
  go.mod
  go.sum
Labels: size/XS, lgtm
