Repository kyma-project/cli, pull requests merged in 2022-12, with the labels that each got.

#1469 Bump hydroform/function
  go.mod
  go.sum
Labels: area/security, area/serverless, size/S, lgtm

#1471 Update reconciler image
  go.mod
  go.sum
Labels: size/S, lgtm

#1468 Open the dashboard at the end of deployment
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/dashboard/cmd.go
  internal/deploy/kyma.go
  internal/os/os.go
  pkg/dashboard/dashboard.go
  pkg/docker/docker.go
Labels: size/L, lgtm

#1476 Release 2.9 cherry-pick: adapt to recent changes in operators
  CODEOWNERS
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/deploy/cmd.go
  docs/gen-docs/kyma_alpha_create_module.md
  docs/gen-docs/kyma_alpha_deploy.md
  internal/deploy/bootstrap.go
  internal/deploy/kyma.go
Labels: size/S, lgtm

#1479 Bump reconciler with fix for panic in Istio reconciler
  go.mod
  go.sum
Labels: size/XS, lgtm

#1482 Bump reconciler with Istio 1.16
  go.mod
  go.sum
Labels: size/XS, lgtm

#1481 add validation for channel
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/opts.go
Labels: size/S, lgtm

#1455 Fix coredns patching for modular kyma on k3d
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/deploy/cmd.go
  internal/coredns/coredns.go
Labels: size/M, lgtm

#1478 Fix panic on gathering repository metadata
  cmd/kyma/alpha/create/module/module.go
  docs/gen-docs/kyma_alpha_create_module.md
  pkg/module/build.go
  pkg/module/git/source.go
  pkg/module/oci/ref.go
Labels: size/L, lgtm

#1484 Add nataliasitko to codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#1485 fix-dashboard: mount kubeconfig to wrong path
  pkg/dashboard/dashboard.go
Labels: size/XS, lgtm

#1486 Release 2.9 Cherry-Pick: Bump helm.sh/helm/v3 to v3.10.3
  go.mod
  go.sum
Labels: size/XS, lgtm

#1488 chore: bump DefaultKyma2Version to 2.9.3
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1490 Fix timeout issues in tests
  internal/kube/client.go
  internal/kube/client_test.go
Labels: size/XS, lgtm

#1493 Update K8s api to get compatible with latest reconciler lib
  go.mod
  go.sum
Labels: size/L, lgtm
