Repository kyma-project/cli, pull requests merged in 2022-06, with the labels that each got.

#1274 Add kaniko force flag for k3d clusters
  internal/deploy/values/builder.go
  internal/deploy/values/values.go
  internal/deploy/values/values_test.go
Labels: size/M, lgtm

#1268 Add error filtering fr provision
  cmd/kyma/provision/gardener/aws/template.go
  cmd/kyma/provision/gardener/az/template.go
  cmd/kyma/provision/gardener/gcp/template.go
  cmd/kyma/provision/run_template.go
Labels: size/M, lgtm

#1275 Vulnerability Hotfix for release 2.1
  go.mod
  go.sum
Labels: size/XS, lgtm

#1277 Vulnerability Hotfix for main
  go.mod
  go.sum
Labels: size/XS, lgtm

#1276 Vulnerability Hotfix for release 2.2
  go.mod
  go.sum
Labels: size/XS, lgtm

#1279 add nil check for error objects
  cmd/kyma/provision/gardener/aws/template.go
  cmd/kyma/provision/gardener/az/template.go
  cmd/kyma/provision/gardener/gcp/template.go
Labels: size/XS, lgtm

#1280 remove orphaned kyma1 setting
  internal/config/config.go
Labels: size/XS, lgtm

#1281 Update version to 2.3.0
  internal/config/config.go
Labels: size/XS, lgtm

#1283 Release 2.3
  docs/gen-docs/kyma_deploy.md
Labels: size/XS, lgtm

#1272 Add nodejs16 to allowed runtimes
  cmd/kyma/init/function/function.go
  cmd/kyma/run/function/function.go
  docs/gen-docs/kyma_init_function.md
  go.mod
  go.sum
Labels: size/S, lgtm

#1286 Upgrade Hydroform Dependency
  go.mod
  go.sum
Labels: size/S, lgtm

#1282 Bump hydroform function
  go.mod
  go.sum
Labels: size/XS, lgtm

#1290 Upgrade Hydroform to mitigate sec vuls.
  go.mod
  go.sum
Labels: size/S, lgtm

#1293 Replace containerd with latest to fix CVE
  go.mod
  go.sum
Labels: size/M, lgtm

#1294 Bump reconciler to version with istio 1.14.1
  go.mod
  go.sum
Labels: size/S, lgtm

#1295 Bump hydroform/function
  go.mod
  go.sum
Labels: size/XS, lgtm

#1297 Bump apply command
  go.mod
  go.sum
Labels: size/XS, lgtm

#1299 Bump function module to resolve CVE-2022-1996
  go.mod
  go.sum
Labels: size/M, lgtm
