Repository kyma-project/cli, pull requests merged in 2022-08, with the labels that each got.

#1331 Bump reconciler with Istio Proxy Reset post action
  go.mod
  go.sum
Labels: size/XS, lgtm

#1333 Fix the CLI release script
  hack/release.sh
Labels: kind/bug, area/cli, size/XS, lgtm

#1322 Layering engine for kyma modules
  cmd/kyma/alpha/create/module/module.go
  pkg/module/def.go
  pkg/module/resources.go
  pkg/module/test/test-module/charts/dummy/Chart.yaml
  pkg/module/test/test-module/charts/test-chart/Chart.yaml
  pkg/module/test/test-module/charts/test-chart/values.yaml
  pkg/module/test/test-module/crds/crds.yaml
Labels: area/cli, size/L, lgtm

#1338 Remove crds, profiles and channels from the module layout
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/init/module/module.go
  docs/gen-docs/kyma_alpha_create.md
  docs/gen-docs/kyma_alpha_create_module.md
  docs/gen-docs/kyma_alpha_init_module.md
  pkg/module/oci/ref.go
  pkg/module/resources.go
  pkg/module/scaffold/init.go
  pkg/module/test/test-module/crds/crds.yaml
  pkg/module/validation.go
Labels: size/L, lgtm

#1340 Fix inconsistent hashes on tar blobs
  cmd/kyma/apply/apply_test.go
  cmd/kyma/create/create_test.go
  cmd/kyma/deploy/cmd.go
  cmd/kyma/deploy/cmd_test.go
  cmd/kyma/import/certs/cmd.go
  cmd/kyma/init/init_test.go
  cmd/kyma/kyma_test.go
  cmd/kyma/provision/run_template.go
  cmd/kyma/run/run_test.go
  cmd/kyma/sync/sync_test.go
  cmd/kyma/undeploy/cmd.go
  internal/deploy/component/list.go
  internal/deploy/istioctl/istio.go
  internal/deploy/istioctl/istio_test.go
  internal/deploy/values/builder.go
  internal/deploy/values/builder_test.go
  internal/deploy/values/values.go
  pkg/docker/docker_test.go
  pkg/module/blob/blob.go
  pkg/module/oci/cache.go
  pkg/module/oci/client.go
  pkg/module/oci/manifest_v1_conversion.go
  pkg/module/signatures/digester.go
Labels: kind/bug, area/cli, size/L, lgtm

#1341 Bump reconciler with Istio patch old MutatingWebhook
  go.mod
  go.sum
Labels: size/XS, lgtm

#1334 Add module template generation
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/opts.go
  cmd/kyma/alpha/sign/module/module.go
  cmd/kyma/alpha/sign/module/opts.go
  cmd/kyma/alpha/sign/sign.go
  docs/gen-docs/kyma_alpha_create_module.md
  pkg/module/template.go
  pkg/module/test/test-module/default.yaml
Labels: area/cli, size/L, lgtm

#1343 bump reconciler with labeling namespaces and updated reset proxy
  go.mod
  go.sum
Labels: size/L, lgtm

#1344 Fix Whitesource vulnerabilities
  go.mod
  go.sum
Labels: size/M, lgtm

#1345 Make user/password credentials work for gcloud registry
  pkg/module/oci/client.go
Labels: area/cli, size/S, lgtm

#1346 Fix sec vuln rel 2.6
  Makefile
  go.mod
  go.sum
Labels: size/XL, lgtm

#1348 Fix sec vuln rel 2.6 part II
  go.mod
  go.sum
Labels: size/XS, lgtm

#1349 Bump reconciler
  go.mod
  go.sum
Labels: size/XS, lgtm

#1351 Bump reconciler to support istio 1.14.3
  go.mod
  go.sum
Labels: size/XS, lgtm

#1355 Bump Hydroform API to latest version
  go.mod
  go.sum
Labels: size/XS, lgtm

#1356 Bumped reconciler
  go.mod
  go.sum
Labels: size/XS, lgtm

#1358 Use Kyma 2.6 sources as default
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1362 Bump reconciler
  go.mod
  go.sum
Labels: size/XS, lgtm

#1363 Release 2.6.1
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1369 Release 2.6.2
  go.mod
  go.sum
Labels: size/XS, lgtm
