Repository kyma-project/cli, pull requests merged in 2022-05, with the labels that each got.

#1261 Use only one YAML version
  cmd/kyma/apply/function/function.go
  cmd/kyma/create/system/system.go
  cmd/kyma/run/function/function.go
  cmd/kyma/version/cmd.go
  go.mod
  go.sum
  internal/deploy/istioctl/istio.go
Labels: size/S, lgtm

#1258 Muting unnecessary logs when using output flag in CLI
  cmd/kyma/apply/function/function.go
  pkg/step/factory.go
  pkg/step/muted.go
Labels: size/M, lgtm

#1262 set default kyma version to 2.2.0
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1263 Migrate hydroform modules out of incubator
  cmd/kyma/apply/function/function.go
  cmd/kyma/apply/function/opts.go
  cmd/kyma/get/get.go
  cmd/kyma/get/schema/schema_test.go
  cmd/kyma/init/function/function.go
  cmd/kyma/init/function/opts.go
  cmd/kyma/provision/gardener/aws/cmd_test.go
  cmd/kyma/provision/gardener/aws/template.go
  cmd/kyma/provision/gardener/az/cmd_test.go
  cmd/kyma/provision/gardener/az/template.go
  cmd/kyma/provision/gardener/gcp/cmd_test.go
  cmd/kyma/provision/gardener/gcp/template.go
  cmd/kyma/provision/run_template.go
  cmd/kyma/run/function/function.go
  cmd/kyma/run/function/opts.go
  cmd/kyma/sync/function/function.go
  go.mod
  go.sum
  pkg/docker/docker.go
  pkg/serverless/schema_file.go
  pkg/vscode/workspace.go
  pkg/vscode/workspace_test.go
Labels: size/M, lgtm

#1264 Bump reconciler in kyma-cli
  go.mod
  go.sum
Labels: size/M, lgtm

#1265 version: add retry to get the cluster kyma version
  cmd/kyma/version/cmd.go
  cmd/kyma/version/opts.go
  docs/gen-docs/kyma_version.md
Labels: size/S, lgtm

#1266 Bump hydroform function package
  go.mod
  go.sum
Labels: size/XS, lgtm

#1270 Bump hf to latest fixing sec issues
  go.mod
  go.sum
Labels: size/S, lgtm

#1271 Remove minikube leftovers
  internal/minikube/minikube.go
  pkg/docker/docker.go
  pkg/docker/docker_test.go
Labels: size/L, lgtm

#1273 update minimal cluster setting and update garden linux version
  cmd/kyma/provision/gardener/aws/cmd.go
  cmd/kyma/provision/gardener/aws/cmd_test.go
  cmd/kyma/provision/gardener/aws/template.go
  cmd/kyma/provision/gardener/az/cmd.go
  cmd/kyma/provision/gardener/az/cmd_test.go
  cmd/kyma/provision/gardener/az/template.go
  cmd/kyma/provision/gardener/gcp/cmd.go
  cmd/kyma/provision/gardener/gcp/cmd_test.go
  cmd/kyma/provision/gardener/gcp/template.go
  docs/gen-docs/kyma_provision_gardener_aws.md
  docs/gen-docs/kyma_provision_gardener_az.md
  docs/gen-docs/kyma_provision_gardener_gcp.md
Labels: size/M, lgtm
