Repository kyma-project/cli, pull requests merged in 2022-01, with the labels that each got.

#1131 undeploy: setup istioctl before undeploy
  cmd/kyma/deploy/cmd.go
  cmd/kyma/undeploy/cmd.go
  internal/deploy/istioctl/istio.go
  internal/deploy/workspace_test.go
Labels: size/M, lgtm

#1132 Bump reconciler to the latest
  go.mod
  go.sum
Labels: size/XS, lgtm

#1133 dashboard cmd: support local clusters on linux
  cmd/kyma/dashboard/cmd.go
  pkg/docker/docker.go
Labels: size/S, lgtm

#1136 Bump reconciler
  go.mod
  go.sum
Labels: size/XS, lgtm

#1139 update kyma version to 2.0.2
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1140 update default kyma1 version to 1.24.9
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_upgrade.md
  internal/config/config.go
Labels: size/XS, lgtm

#1141 Update default kyma1 version to 1.24.9
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_upgrade.md
  internal/config/config.go
Labels: size/XS, lgtm

#1142 increase the remote reader timeout
  internal/resolve/resolve.go
Labels: size/XS, lgtm

#1144 update default kyma version to 2.0.3
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1145 Add grego952 as a documentation CODEOWNER in CLI
  CODEOWNERS
Labels: area/documentation, area/community, size/XS, lgtm

#1149 add jellyfish to CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#1148 fix CLI version for non-release is always 'stable'
  Makefile
Labels: size/S, lgtm

#1150 Remove test subcommand and octopus dependencies
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  cmd/kyma/test/cmd.go
  cmd/kyma/test/common.go
  cmd/kyma/test/common_test.go
  cmd/kyma/test/definitions/cmd.go
  cmd/kyma/test/definitions/cmd_test.go
  cmd/kyma/test/definitions/opts.go
  cmd/kyma/test/delete/cmd.go
  cmd/kyma/test/delete/cmd_test.go
  cmd/kyma/test/delete/opts.go
  cmd/kyma/test/list/cmd.go
  cmd/kyma/test/list/opts.go
  cmd/kyma/test/logs/cmd.go
  cmd/kyma/test/logs/opts.go
  cmd/kyma/test/run/cmd.go
  cmd/kyma/test/run/cmd_test.go
  cmd/kyma/test/run/opts.go
  cmd/kyma/test/status/cmd.go
  cmd/kyma/test/status/cmd_test.go
  cmd/kyma/test/status/opts.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_logs.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  go.mod
  go.sum
  internal/junitxml/dto.go
  internal/junitxml/mocks/logsFetcher.go
  internal/junitxml/report.go
  internal/junitxml/report_test.go
  internal/junitxml/testdata/TestWriteJUnitXMLReport/TestSuite_is_still_running_but_timeout_occur.golden.xml
  internal/junitxml/testdata/TestWriteJUnitXMLReport/TestSuite_is_still_running_but_timeout_occur.input.yaml
  internal/junitxml/testdata/TestWriteJUnitXMLReport/Test_Suite_Failed.golden.xml
  internal/junitxml/testdata/TestWriteJUnitXMLReport/Test_Suite_Failed.input.yaml
  internal/kube/client.go
  internal/kube/kube.go
  internal/kube/mocks/KymaKube.go
  internal/logs/fetcher.go
  internal/logs/fetcher_test.go
  pkg/api/octopus/client.go
  pkg/api/octopus/mock.go
Labels: area/cli, size/XXL, lgtm

#1143 bump reconciler to latest version
  go.mod
  go.sum
Labels: size/L, lgtm

#1154 Cherry-Pick: Remove test subcommand and octopus dependencies
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  cmd/kyma/test/cmd.go
  cmd/kyma/test/common.go
  cmd/kyma/test/common_test.go
  cmd/kyma/test/definitions/cmd.go
  cmd/kyma/test/definitions/cmd_test.go
  cmd/kyma/test/definitions/opts.go
  cmd/kyma/test/delete/cmd.go
  cmd/kyma/test/delete/cmd_test.go
  cmd/kyma/test/delete/opts.go
  cmd/kyma/test/list/cmd.go
  cmd/kyma/test/list/opts.go
  cmd/kyma/test/logs/cmd.go
  cmd/kyma/test/logs/opts.go
  cmd/kyma/test/run/cmd.go
  cmd/kyma/test/run/cmd_test.go
  cmd/kyma/test/run/opts.go
  cmd/kyma/test/status/cmd.go
  cmd/kyma/test/status/cmd_test.go
  cmd/kyma/test/status/opts.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_test.md
  docs/gen-docs/kyma_test_definitions.md
  docs/gen-docs/kyma_test_delete.md
  docs/gen-docs/kyma_test_list.md
  docs/gen-docs/kyma_test_logs.md
  docs/gen-docs/kyma_test_run.md
  docs/gen-docs/kyma_test_status.md
  go.mod
  go.sum
  internal/junitxml/dto.go
  internal/junitxml/mocks/logsFetcher.go
  internal/junitxml/report.go
  internal/junitxml/report_test.go
  internal/junitxml/testdata/TestWriteJUnitXMLReport/TestSuite_is_still_running_but_timeout_occur.golden.xml
  internal/junitxml/testdata/TestWriteJUnitXMLReport/TestSuite_is_still_running_but_timeout_occur.input.yaml
  internal/junitxml/testdata/TestWriteJUnitXMLReport/Test_Suite_Failed.golden.xml
  internal/junitxml/testdata/TestWriteJUnitXMLReport/Test_Suite_Failed.input.yaml
  internal/kube/client.go
  internal/kube/kube.go
  internal/kube/mocks/KymaKube.go
  internal/logs/fetcher.go
  internal/logs/fetcher_test.go
  pkg/api/octopus/client.go
  pkg/api/octopus/mock.go
Labels: size/XXL, lgtm

#1157 Cherry Pick: update to latest reconciler (#1143)
  go.mod
  go.sum
Labels: size/L, lgtm

#1155 Adapt `kyma help` output for removed test command
  cmd/kyma/kyma.go
  docs/gen-docs/kyma.md
Labels: size/XS, lgtm

#1156 Adapt `kyma help` output for removed test command
  cmd/kyma/kyma.go
  docs/gen-docs/kyma.md
Labels: size/XS, lgtm

#1158 Integrate reconciler delete strategy and add flag
  cmd/kyma/undeploy/cmd.go
  cmd/kyma/undeploy/opts.go
  docs/gen-docs/kyma_undeploy.md
  go.mod
  go.sum
  internal/deploy/deploy.go
Labels: size/S, lgtm

#1161 Add cleaner and other fixes for reconciler to CLI
  go.mod
  go.sum
Labels: size/XS, lgtm

#1164 adapt-cli-runtimebuilder-to-reconciler
  go.mod
  go.sum
  internal/deploy/deploy.go
Labels: size/S, lgtm

#1160 Deprecate nodejs12
  cmd/kyma/init/function/function.go
  docs/gen-docs/kyma_init_function.md
  docs/gen-docs/kyma_provision_minikube.md
  pkg/step/log.go
  pkg/step/simple.go
  pkg/step/spinner.go
  pkg/step/step.go
Labels: size/M, lgtm

#1167 Ensure non-zero exit code on timeout
  cmd/kyma/deploy/cmd.go
Labels: size/XS, lgtm
