Repository kyma-project/cli, pull requests merged in 2022-11, with the labels that each got.

#1431 Allow to share docker registry between local k3d clusters
  cmd/kyma/provision/k3d/cmd.go
  internal/k3d/k3d.go
Labels: size/M, lgtm

#1434 Update reconciler and it's dependencies
  go.mod
  go.sum
Labels: area/cli, size/L, lgtm

#1437 Release 2.8.2
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1439 chore: upgrade and bump dependencies
  go.mod
  go.sum
Labels: size/L, lgtm

#1435 Update CLI to the newest function CRD
  cmd/kyma/apply/function/function.go
  go.mod
  go.sum
Labels: area/serverless, size/S, lgtm

#1438 Feature/improved insecure detection
  cmd/kyma/alpha/create/module/module.go
Labels: size/M, lgtm

#1440 Bump hydroform/function
  go.mod
  go.sum
Labels: size/S, lgtm

#1436 Improve create module command
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/opts.go
  cmd/kyma/alpha/sign/module/module.go
  docs/gen-docs/kyma_alpha_create_module.md
  go.mod
  pkg/module/build.go
  pkg/module/def.go
  pkg/module/git/source.go
  pkg/module/kubebuilder/chart.go
  pkg/module/kubebuilder/project.go
  pkg/module/resources.go
Labels: size/XL, lgtm

#1441 Bump hydroform/function
  go.mod
  go.sum
Labels: size/S, lgtm

#1444 Bump reconciler with Istio user configuration
  go.mod
  go.sum
Labels: size/L, lgtm

#1447 Remove skhalash from CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#1445 Fix default registry management
  cmd/kyma/provision/k3d/cmd.go
  internal/k3d/k3d.go
Labels: area/cli, size/L, lgtm

#1449 fix: adjust lifecycle manager operator path
  cmd/kyma/alpha/deploy/cmd.go
  docs/gen-docs/kyma_alpha_deploy.md
  internal/deploy/bootstrap.go
Labels: size/S, lgtm

#1448 Function synchronise fix
  cmd/kyma/apply/function/function.go
  cmd/kyma/init/function/opts.go
  go.mod
  go.sum
Labels: kind/bug, area/serverless, size/S, lgtm, release blocker

#1450 Remove /.kyma-project-io/ from CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#1451 Use Kyma Dashboard image instead of a Busola one
  cmd/kyma/dashboard/cmd.go
  docs/gen-docs/kyma_dashboard.md
Labels: size/XS, lgtm

#1452 Release 2.8.3
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1453 remove Maja from codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#1457 Start release 2.9
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1456 add IwonaLanger to CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#1461 Release 2.8.4
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1463 Release 2.9.1
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1464 chore: update channels
  cmd/kyma/alpha/create/module/module.go
  docs/gen-docs/kyma_alpha_create_module.md
  internal/deploy/kyma.go
Labels: size/XS, lgtm

#1459 refactor: remove module-manager 'operator' folder
  cmd/kyma/alpha/deploy/cmd.go
  docs/gen-docs/kyma_alpha_deploy.md
  internal/deploy/bootstrap.go
Labels: size/S, lgtm

#1465 Use URL and Version from Components file
  internal/deploy/deploy.go
  internal/deploy/deploy_test.go
Labels: kind/bug, size/S, lgtm, area/reconciler

#1466 Bump reconciler with Istio CNI support
  go.mod
  go.sum
Labels: size/M, lgtm

#1467 Bump reconciler with renamed Istio CNI ConfigMap
  go.mod
  go.sum
Labels: size/XS, lgtm
