Repository kyma-project/cli, pull requests merged in 2022-04, with the labels that each got.

#1229 Remove CODEOWNERS from repo
  .github/stale.yml
  CODEOWNERS
  docs/OWNERS
Labels: area/documentation, approved, size/S, lgtm

#1230 Bump reconciler with fix to the upgrade pipeline
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#1233 Dry-run without kubeconfig
  cmd/kyma/deploy/cmd.go
  go.mod
  go.sum
Labels: size/L, approved, lgtm

#1234 Upgrade hydroform/function deps
  go.mod
  go.sum
Labels: size/L, approved, lgtm

#1236 bump to reconciler 69b52f4
  Makefile
  go.mod
  go.sum
Labels: size/XL, approved, lgtm

#1238 Bump 2.1.2
  .github/stale.yml
  CODEOWNERS
  Makefile
  cmd/kyma/deploy/cmd.go
  docs/OWNERS
  docs/gen-docs/kyma_deploy.md
  go.mod
  go.sum
  internal/config/config.go
Labels: area/documentation, size/XL, approved, lgtm

#1220 Support the `customRuntimeImage` field for the `config.yaml` and the `run function` method
  cmd/kyma/init/function/function.go
  cmd/kyma/init/function/function_test.go
  cmd/kyma/init/function/opts.go
  cmd/kyma/run/function/function.go
  docs/gen-docs/kyma_init_function.md
  go.mod
  go.sum
Labels: area/documentation, area/serverless, size/L, approved, lgtm

#1239 Fix Whitesource Scan vulnerabilities issues
  go.mod
  go.sum
Labels: size/L, approved, lgtm

#1241 Fix CVE vulnerable complain
  go.mod
  go.sum
Labels: size/L, approved, lgtm

#1243 bumped kyma version to 2.1.3
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: area/documentation, size/XS, approved, lgtm

#1244 Bump reconciler to fix wrong level logs
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#1231 Fix for local functions running from subfolders
  cmd/kyma/run/function/function.go
  go.mod
  go.sum
Labels: area/cli, approved, size/M, lgtm

#1246 Backport reconciler hotfix: fix show logs on init
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#1249 Removed deprecated kyma 1 commands and deps
  cmd/kyma/console/cmd.go
  cmd/kyma/console/opts.go
  cmd/kyma/create/system/system_test.go
  cmd/kyma/install/cmd.go
  cmd/kyma/install/opts.go
  cmd/kyma/kyma.go
  cmd/kyma/kyma_test.go
  cmd/kyma/provision/minikube/cfg_darwin.go
  cmd/kyma/provision/minikube/cfg_others.go
  cmd/kyma/provision/minikube/cfg_windows.go
  cmd/kyma/provision/minikube/cmd.go
  cmd/kyma/provision/minikube/cmd_test.go
  cmd/kyma/provision/minikube/opts.go
  cmd/kyma/upgrade/cmd.go
  cmd/kyma/upgrade/cmd_test.go
  cmd/kyma/upgrade/opts.go
  docs/gen-docs/kyma.md
  docs/gen-docs/kyma_console.md
  docs/gen-docs/kyma_install.md
  docs/gen-docs/kyma_provision.md
  docs/gen-docs/kyma_provision_minikube.md
  docs/gen-docs/kyma_upgrade.md
  go.mod
  go.sum
  internal/hosts/domains.go
  internal/hosts/hosts_others.go
  internal/hosts/hosts_windows.go
  internal/kube/client_test.go
  pkg/installation/cluster.go
  pkg/installation/cluster_test.go
  pkg/installation/installation.go
  pkg/installation/installation_test.go
  pkg/installation/mocks/Installer.go
  pkg/installation/mocks/Service.go
  pkg/installation/opts.go
  pkg/installation/service.go
  pkg/installation/service_test.go
  pkg/installation/upgrade.go
  pkg/installation/upgrade_test.go
  pkg/installation/utils.go
  pkg/installation/utils_test.go
Labels: area/documentation, approved, size/XXL, lgtm

#1250 bump to rec v0.0.0-20220421112831-c5dd1a4fa560
  go.mod
  go.sum
Labels: size/L, approved, lgtm

#1255 Update hydroform with latest gardener
  cmd/kyma/provision/gardener/aws/cmd_test.go
  cmd/kyma/provision/gardener/aws/template.go
  cmd/kyma/provision/gardener/az/cmd_test.go
  cmd/kyma/provision/gardener/az/template.go
  cmd/kyma/provision/gardener/gcp/cmd_test.go
  cmd/kyma/provision/gardener/gcp/template.go
  go.mod
  go.sum
Labels: approved, size/S, lgtm

#1252 Prepare for Github workflow
  CODEOWNERS
Labels: size/XS, approved, lgtm

#1257 Prow approval flow was disabled. Removing OWNERS files. They are not …
  OWNERS
  OWNERS_ALIASES
  docs/OWNERS
Labels: area/documentation, area/ci, size/M
