Repository kyma-project/cli, pull requests merged in 2023-08, with the labels that each got.

#1707 Enable type assertion linter
  .golangci.yml
  Makefile
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/enable/module/mock/mock_interactor.go
  cmd/kyma/alpha/list/module/module.go
  internal/cli/alpha/module/module.go
  internal/deploy/bootstrap.go
  internal/deploy/bootstrap_test.go
  internal/deploy/kyma.go
  pkg/errs/common.go
Labels: size/M, lgtm

#1720 Release 2.17.0
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1712 Remove Config Layer from ModuleTemplate
  pkg/module/kubebuilder/project.go
  pkg/module/resources.go
Labels: size/S, lgtm

#1725 Bump reconciler - PVC interceptor
  go.mod
  go.sum
Labels: kind/bug, size/XS, lgtm

#1738 sync main to 2.17
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/module_test.go
  cmd/kyma/alpha/create/module/testdata/clusterScopedCRD.yaml
  cmd/kyma/alpha/create/module/testdata/namespacedScopedCRD.yaml
  go.mod
  go.sum
  pkg/module/kubebuilder/project.go
  pkg/module/resources.go
  pkg/module/validation.go
Labels: size/XL, lgtm

#1737 Update reconciler to latest
  go.mod
  go.sum
Labels: size/L, lgtm

#1728 Update links for the domain change
  README.md
Labels: size/XS, lgtm

#1736 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: size/L, lgtm

#1740 Release 2.17.1
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
  docs/gen-docs/kyma_deploy.md
  go.mod
  go.sum
  internal/config/config.go
Labels: size/L, lgtm

#1743 Init Legacy flags by default
  cmd/kyma/alpha/create/module/module.go
  docs/gen-docs/kyma_alpha_create_module.md
Labels: size/XS, lgtm

#1746 Better User-Feedback: Fail the sec scan info step if error appears
  cmd/kyma/alpha/create/module/module.go
Labels: size/XS, lgtm

#1749 Add the option to override default namespace
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/moduleconfig.go
  cmd/kyma/alpha/create/module/moduleconfig_test.go
  cmd/kyma/alpha/create/module/opts.go
  docs/gen-docs/kyma_alpha_create_module.md
  pkg/module/template.go
  pkg/module/template_test.go
Labels: size/L, lgtm

#1753 Fix src nil pointer
  pkg/module/build.go
Labels: size/XS, lgtm
