Repository kyma-project/cli, pull requests merged in 2023-09, with the labels that each got.

#1757 revert go mod back
  cmd/kyma/alpha/enable/module/module.go
  cmd/kyma/alpha/enable/module/module_test.go
  go.mod
  go.sum
  pkg/docker/docker.go
  pkg/docker/docker_test.go
  pkg/docker/mocks/Client.go
Labels: size/XL, lgtm

#1759 Release 2.18.0
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1758 upgrade go mod and smoke test for alpha deploy
  .github/workflows/smoke-test.yml
  cmd/kyma/alpha/enable/module/module.go
  cmd/kyma/alpha/enable/module/module_test.go
  go.mod
  go.sum
  internal/deploy/bootstrap.go
  pkg/docker/docker.go
  pkg/docker/docker_test.go
  pkg/docker/mocks/Client.go
Labels: size/XL, lgtm

#1751 Allow create module for no git directory
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/opts.go
  internal/files/existingfile.txt
  internal/files/files.go
  internal/files/files_test.go
  internal/nice/nice.go
  pkg/module/build.go
  pkg/module/git/source.go
  pkg/module/gitsource/git.go
  pkg/module/gitsource/source.go
  pkg/module/template.go
Labels: size/XL, lgtm

#1762 Introduce flag to pass git remote
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/opts.go
  docs/gen-docs/kyma_alpha_create_module.md
  pkg/module/build.go
  pkg/module/def.go
  pkg/module/gitsource/git.go
  pkg/module/gitsource/git_test.go
  pkg/module/resources.go
Labels: size/L, lgtm

#1767 fix: Remove CustomStateCheck flags from the Module Command
  .github/workflows/pull-cli-lint.yml
  Makefile
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/moduleconfig.go
  cmd/kyma/alpha/create/module/moduleconfig_test.go
  cmd/kyma/alpha/create/module/opts.go
  docs/gen-docs/kyma_alpha_create_module.md
  pkg/module/custom_state_check.go
  pkg/module/custom_state_check_test.go
Labels: size/L, lgtm

#1770 Fix repoUrl for parent-child git structure
  internal/files/files.go
  pkg/module/build.go
  pkg/module/gitsource/git.go
  pkg/module/gitsource/git_test.go
Labels: size/M, lgtm

#1775 Do not remove `.git` if exists
  pkg/module/gitsource/git.go
  pkg/module/gitsource/git_test.go
  pkg/module/gitsource/source.go
Labels: size/M, lgtm

#1768 use ociblob instead of ocilocalblob for oci v2
  .github/workflows/test-e2e-create-module.yml
  .github/workflows/test-smoke.yml
  go.mod
  pkg/docker/docker_test.go
  pkg/module/build.go
  pkg/module/gitsource/git.go
  pkg/module/init.go
  pkg/module/layer.go
  pkg/module/remote.go
  pkg/module/resources.go
  pkg/module/template_test.go
  tests/e2e/Makefile
  tests/e2e/kyma_create_module_test.go
  tests/e2e/util.go
Labels: size/L, lgtm

#1778 fix default kyma to main
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1779 release 2.18.1
  .github/workflows/pull-cli-lint.yml
  .github/workflows/test-e2e-create-module.yml
  .github/workflows/test-smoke.yml
  Makefile
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/moduleconfig.go
  cmd/kyma/alpha/create/module/moduleconfig_test.go
  cmd/kyma/alpha/create/module/opts.go
  cmd/kyma/alpha/enable/module/module.go
  cmd/kyma/alpha/enable/module/module_test.go
  docs/gen-docs/kyma_alpha_create_module.md
  docs/gen-docs/kyma_deploy.md
  go.mod
  go.sum
  internal/config/config.go
  internal/deploy/bootstrap.go
  internal/files/existingfile.txt
  internal/files/files.go
  internal/files/files_test.go
  internal/nice/nice.go
  pkg/docker/docker.go
  pkg/docker/docker_test.go
  pkg/docker/mocks/Client.go
  pkg/module/build.go
  pkg/module/custom_state_check.go
  pkg/module/custom_state_check_test.go
  pkg/module/def.go
  pkg/module/git/source.go
  pkg/module/gitsource/git.go
  pkg/module/gitsource/git_test.go
  pkg/module/gitsource/source.go
  pkg/module/init.go
  pkg/module/layer.go
  pkg/module/remote.go
  pkg/module/resources.go
  pkg/module/template.go
  pkg/module/template_test.go
  tests/e2e/Makefile
  tests/e2e/kyma_create_module_test.go
  tests/e2e/util.go
Labels: size/XXL, lgtm

#1780 chore(infra): Adjust GitHub Action linters
  .github/dependabot.yml
  .github/workflows/lint-conventional-prs.yml
  .github/workflows/lint-golangci.yml
  .github/workflows/lint-markdown-links.yml
  .goreleaser.yml
  .mlc.config.json
Labels: size/M, lgtm

#1776 Updating the security scan labels according to the new fields in the security config files
  .github/workflows/test-e2e-create-module.yml
  pkg/module/security_scan.go
  tests/e2e/kyma_create_module_test.go
Labels: size/M, lgtm

#1785 test: Run GH Action tests also on release branches
  .github/workflows/lint-golangci.yml
  .github/workflows/test-e2e-create-module.yml
  .github/workflows/test-smoke.yml
Labels: size/M, lgtm

#1786 deps: Update reconciler version
  go.mod
  go.sum
Labels: size/XS, lgtm

#1791 chore(release): Release 2.18.2
  .github/dependabot.yml
  .github/workflows/lint-conventional-prs.yml
  .github/workflows/lint-golangci.yml
  .github/workflows/lint-markdown-links.yml
  .github/workflows/test-e2e-create-module.yml
  .github/workflows/test-smoke.yml
  .goreleaser.yml
  .mlc.config.json
  docs/gen-docs/kyma_deploy.md
  go.mod
  go.sum
  internal/config/config.go
  pkg/module/security_scan.go
  tests/e2e/kyma_create_module_test.go
Labels: size/L, lgtm
