Repository kyma-project/cli, pull requests merged in 2023-12, with the labels that each got.

#1880 chore(report): Adds a sprint commits report
  .github/workflows/report-sprint-commits.yml
Labels: size/S, lgtm, cla: yes

#1876 chore: Remove istio patching from legacy deploy
  cmd/kyma/deploy/cmd.go
  cmd/kyma/undeploy/cmd.go
  internal/deploy/istioctl/istio.go
  internal/deploy/istioctl/istio_test.go
  internal/deploy/istioctl/testdata/Chart.yaml
  internal/deploy/istioctl/testdata/corruptedChart.yaml
  internal/deploy/istioctl/testdata/istio_mock.tar
  internal/deploy/istioctl/testdata/istio_mock.tar.gz
  internal/deploy/istioctl/testdata/istio_mock.zip
Labels: size/XL, lgtm, cla: yes

#1881 chore: Reference lifecycle manager api module
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/module_test.go
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/cmd_test.go
  cmd/kyma/alpha/list/module/module.go
  go.mod
  go.sum
  internal/cli/alpha/module/module.go
  internal/deploy/kyma.go
  internal/deploy/module_templates.go
  internal/kustomize/kustomize_test.go
  pkg/module/template.go
  pkg/module/template_test.go
  tests/e2e/create_module/kyma_create_module_test.go
  tests/e2e/e2e_suite_test.go
Labels: size/XL, lgtm, cla: yes

#1885 Release 2.20.1
  .github/workflows/lint-conventional-prs.yml
  .github/workflows/lint-golangci.yml
  .github/workflows/report-sprint-commits.yml
  .github/workflows/test-e2e-create-module.yml
  .github/workflows/test-e2e.yml
  CODEOWNERS
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/module_test.go
  cmd/kyma/alpha/create/module/moduleconfig.go
  cmd/kyma/alpha/create/module/moduleconfig_test.go
  cmd/kyma/alpha/create/module/opts.go
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/cmd_test.go
  cmd/kyma/alpha/enable/module/mock/mock_interactor.go
  cmd/kyma/alpha/enable/module/module.go
  cmd/kyma/alpha/enable/module/module_test.go
  cmd/kyma/alpha/list/module/module.go
  cmd/kyma/alpha/verify/module/module.go
  cmd/kyma/deploy/cmd.go
  cmd/kyma/undeploy/cmd.go
  docs/gen-docs/kyma_deploy.md
  go.mod
  go.sum
  internal/cli/alpha/module/module.go
  internal/config/config.go
  internal/coredns/coredns.go
  internal/deploy/apply.go
  internal/deploy/istioctl/istio.go
  internal/deploy/istioctl/istio_test.go
  internal/deploy/istioctl/testdata/Chart.yaml
  internal/deploy/istioctl/testdata/corruptedChart.yaml
  internal/deploy/istioctl/testdata/istio_mock.tar
  internal/deploy/istioctl/testdata/istio_mock.tar.gz
  internal/deploy/istioctl/testdata/istio_mock.zip
  internal/deploy/kyma.go
  internal/deploy/module_templates.go
  internal/kube/mocks/KymaKube.go
  internal/kustomize/kustomize_test.go
  internal/nice/summary.go
  pkg/docker/docker.go
  pkg/module/custom_state_check.go
  pkg/module/mocks/OciRepoAccess.go
  pkg/module/oci_repo.go
  pkg/module/remote.go
  pkg/module/remote_test.go
  pkg/module/security_scan.go
  pkg/module/template.go
  pkg/module/template_test.go
  sec-scanners-config.yaml
  tests/e2e/create_module/kyma_create_module_same_version_test.go
  tests/e2e/create_module/kyma_create_module_test.go
  tests/e2e/deploy_enable_disable_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/util.go
Labels: size/XXL, lgtm, cla: yes

#1886 fix: Bump reconciler
  go.mod
  go.sum
Labels: size/M, lgtm, cla: yes

#1887 feat: Release 2.20.1
  docs/gen-docs/kyma_deploy.md
  go.mod
  go.sum
  internal/config/config.go
Labels: size/M, lgtm, cla: yes

#1891 chore(report): Adjusts the "Sprint Commits Test Suites" report to report E2E and Integration tests separately
  .github/workflows/report-sprint-commits.yml
Labels: size/XS, lgtm, cla: yes
