Repository kyma-project/cli, pull requests merged in 2023-05, with the labels that each got.

#1647 Release 2.13.2
  .goreleaser.yml
  cmd/kyma/alpha/create/module/module.go
  docs/gen-docs/kyma_deploy.md
  go.mod
  go.sum
  hack/release.sh
  internal/config/config.go
  pkg/module/resources.go
  pkg/module/template.go
Labels: size/L, lgtm

#1649 Change var name
  hack/release.sh
Labels: size/XS, lgtm

#1650 Add sync label to default Kyma and ModuleTemplate
  internal/deploy/kyma.go
  pkg/module/template.go
Labels: size/XS, lgtm

#1652 Revert "Add sync label to default Kyma and ModuleTemplate (#1650)"
  internal/deploy/kyma.go
  pkg/module/template.go
Labels: size/XS, lgtm

#1653 Get rid of Stable CLI
  Makefile
  README.md
  cmd/kyma/kyma.go
  hack/release.sh
  internal/cli/version.go
Labels: size/M, lgtm

#1664 Release CLI to 2.14
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1657 Remove module template managed-by and controller-name labels
  cmd/kyma/alpha/list/module/testdata/template_sample.yaml
  internal/kustomize/testdata/expected/manifest.yaml
  internal/kustomize/testdata/given/alpha/template.yaml
  pkg/module/template.go
Labels: size/XS, lgtm

#1666 Make v1beta2 default
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/cmd_test.go
  cmd/kyma/alpha/disable/module/module.go
  cmd/kyma/alpha/disable/module/module_test.go
  cmd/kyma/alpha/enable/module/mock/mock_interactor.go
  cmd/kyma/alpha/enable/module/module.go
  cmd/kyma/alpha/enable/module/module_test.go
  cmd/kyma/alpha/enable/module/opts.go
  cmd/kyma/alpha/list/module/module.go
  cmd/kyma/alpha/list/module/testdata/kyma_sample.yaml
  cmd/kyma/alpha/list/module/testdata/template_sample.yaml
  go.mod
  go.sum
  internal/cli/alpha/module/module.go
  internal/deploy/kyma.go
  internal/kustomize/testdata/expected/manifest.yaml
  internal/kustomize/testdata/given/alpha/template.yaml
  pkg/module/template.go
Labels: size/L, lgtm

#1660 add runtime labels and annotations of serverless function
  go.mod
  go.sum
Labels: size/XS, lgtm

#1665 Arm compiler
  Makefile
Labels: size/S, lgtm

#1672 Release 2.14.1
  Makefile
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/cmd_test.go
  cmd/kyma/alpha/disable/module/module.go
  cmd/kyma/alpha/disable/module/module_test.go
  cmd/kyma/alpha/enable/module/mock/mock_interactor.go
  cmd/kyma/alpha/enable/module/module.go
  cmd/kyma/alpha/enable/module/module_test.go
  cmd/kyma/alpha/enable/module/opts.go
  cmd/kyma/alpha/list/module/module.go
  cmd/kyma/alpha/list/module/testdata/kyma_sample.yaml
  cmd/kyma/alpha/list/module/testdata/template_sample.yaml
  docs/gen-docs/kyma_deploy.md
  go.mod
  go.sum
  internal/cli/alpha/module/module.go
  internal/config/config.go
  internal/deploy/apply.go
  internal/deploy/bootstrap.go
  internal/deploy/bootstrap_test.go
  internal/deploy/kyma.go
  internal/deploy/module_templates.go
  internal/kustomize/testdata/expected/manifest.yaml
  internal/kustomize/testdata/given/alpha/template.yaml
  internal/testdata/manifest.yaml
  internal/testdata/manifestInKcp.yaml
  pkg/module/template.go
Labels: size/XXL, lgtm

#1675 Release 2.14.3
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1676 update kyma dashboard image to artifact registry
  pkg/dashboard/dashboard.go
Labels: size/XS, lgtm
