Repository kyma-project/cli, pull requests merged in 2023-03, with the labels that each got.

#1564 fix: use insecure as hint on whether to append http:// or not
  pkg/module/remote.go
Labels: size/XS, lgtm

#1565 Deprecate nodejs14 runtime
  cmd/kyma/init/function/function.go
  cmd/kyma/init/function/function_test.go
  docs/gen-docs/kyma_init_function.md
Labels: area/cli, area/serverless, size/S, lgtm

#1542 Add new API subscription version
  cmd/kyma/apply/function/function.go
  cmd/kyma/init/function/function.go
  cmd/kyma/init/function/opts.go
  cmd/kyma/sync/function/function.go
  cmd/kyma/sync/function/opts.go
  docs/gen-docs/kyma_init_function.md
  docs/gen-docs/kyma_sync_function.md
  go.mod
  go.sum
Labels: area/cli, size/M, lgtm, go

#1566 internal/kube/client: Modify Watch Timeout Strategy
  internal/kube/client.go
Labels: size/S, lgtm

#1578 Update codeowners of the serverless commands
  CODEOWNERS
Labels: size/XS, lgtm

#1586 use jellyfish team as default code owner
  CODEOWNERS
Labels: size/XS, lgtm

#1584 Add custom resource policy flag to the enable module command
  cmd/kyma/alpha/enable/module/module.go
  cmd/kyma/alpha/enable/module/opts.go
  cmd/kyma/alpha/enable/module/opts_test.go
  docs/gen-docs/kyma_alpha_enable_module.md
Labels: size/M, lgtm

#1589 Introduce istio 1 17
  go.mod
  go.sum
Labels: size/XS, lgtm

#1583 cmd alpha enable module: Add Channel Input Validation
  cmd/kyma/alpha/disable/module/module.go
  cmd/kyma/alpha/enable/module/mock/mock_interactor.go
  cmd/kyma/alpha/enable/module/module.go
  cmd/kyma/alpha/enable/module/module_test.go
  go.mod
  go.sum
  internal/cli/alpha/module/module.go
Labels: size/L, lgtm

#1587 Use the Kyma global channel for disable module command
  cmd/kyma/alpha/disable/module/module.go
  cmd/kyma/alpha/disable/module/module_test.go
Labels: size/L, lgtm

#1590 Bump Reconciler with Istio Webhook fix
  go.mod
  go.sum
Labels: size/L, lgtm

#1591 release 2.12.0
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1599 Bump Garden Linux version
  cmd/gendocs/gendocs.go
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/alpha/disable/module/opts.go
  cmd/kyma/alpha/enable/module/opts.go
  cmd/kyma/alpha/list/module/module.go
  cmd/kyma/alpha/unpack/module/module.go
  cmd/kyma/deploy/opts.go
  cmd/kyma/import/certs/cmd.go
  cmd/kyma/provision/gardener/aws/cmd_test.go
  cmd/kyma/provision/gardener/aws/template.go
  cmd/kyma/provision/gardener/az/cmd_test.go
  cmd/kyma/provision/gardener/az/template.go
  cmd/kyma/provision/gardener/gcp/cmd_test.go
  cmd/kyma/provision/gardener/gcp/template.go
  cmd/kyma/provision/k3d/cmd.go
  hack/.golangci.yml
  hack/verify-lint.sh
  internal/cli/alpha/module/module.go
  internal/cli/finalizers_test.go
  internal/deploy/istioctl/istio.go
  internal/envtest/envtest.go
  internal/trust/trust_linux.go
  pkg/step/log.go
  pkg/step/mocks/step.go
  pkg/step/muted.go
  pkg/vscode/workspace_test.go
Labels: size/L, lgtm

#1606 Use lifecycle manager image from the Kustomization for Kyma alpha deploy command
  cmd/kyma/alpha/deploy/cmd.go
  docs/gen-docs/kyma_alpha_deploy.md
  internal/kustomize/kustomize.go
Labels: size/S, lgtm

#1608 Introduce sign process to create module
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/opts.go
  cmd/kyma/alpha/sign/module/module.go
  cmd/kyma/alpha/sign/module/opts.go
  cmd/kyma/alpha/verify/module/module.go
  cmd/kyma/alpha/verify/module/opts.go
  docs/gen-docs/kyma_alpha_create_module.md
  docs/gen-docs/kyma_alpha_sign_module.md
  docs/gen-docs/kyma_alpha_verify_module.md
  go.mod
  go.sum
  pkg/module/sign.go
Labels: size/L, lgtm

#1604 provision/k3d: Add "k3d-registry-arg" Flag
  cmd/kyma/provision/k3d/cmd.go
  cmd/kyma/provision/k3d/opts.go
  docs/gen-docs/kyma_provision_k3d.md
  internal/k3d/k3d.go
  internal/k3d/k3d_test.go
Labels: size/M, lgtm
