Repository kyma-project/cli, pull requests merged in 2023-06, with the labels that each got.

#1680 Bump versions to fix vulnerability issues
  go.mod
  go.sum
Labels: size/S, lgtm

#1679 Handle optional serverless dependencies in cli
  cmd/kyma/apply/function/function.go
  go.mod
  go.sum
Labels: size/M, lgtm

#1682 Bump reconciler lib for Istio 1.18 client update
  go.mod
  go.sum
Labels: size/M, lgtm

#1687 Fix NodePort conflict with internal docker registry
  go.mod
  go.sum
Labels: size/XS, lgtm

#1688 Use newest reconciler
  go.mod
  go.sum
Labels: size/XS, lgtm

#1691 Release 2.15.1
  cmd/kyma/apply/function/function.go
  docs/gen-docs/kyma_deploy.md
  go.mod
  go.sum
  internal/config/config.go
Labels: size/L, lgtm

#1690 Remove nodejs 14, deprecate nodejs16
  cmd/kyma/init/function/function.go
  cmd/kyma/run/function/function.go
  docs/gen-docs/kyma_init_function.md
  go.mod
  go.sum
Labels: size/S, lgtm
