Repository kyma-project/cli, pull requests merged in 2023-02, with the labels that each got.

#1506 Update reconciler to version 20230201142411
  go.mod
  go.sum
Labels: size/L, lgtm

#1507 Alpha list module updates and deploy to kyma system
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  cmd/kyma/alpha/list/module/module.go
  cmd/kyma/alpha/list/module/module_test.go
  cmd/kyma/alpha/list/module/testdata/kyma_sample.yaml
  cmd/kyma/alpha/list/module/testdata/template_sample.yaml
  docs/gen-docs/kyma_alpha_deploy.md
  docs/gen-docs/kyma_alpha_list_module.md
  internal/deploy/kyma.go
Labels: size/L, lgtm

#1509 fix kymaCR option
  cmd/kyma/alpha/deploy/cmd.go
Labels: size/XS, lgtm

#1512 Align CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#1515 enable dependabot library version updates
  .github/dependabot.yml
Labels: size/S, lgtm

#1521 Revert "gomod(deps): bump github.com/docker/cli from 20.10.21+incompatible to 23.0.0+incompatible"
  go.mod
  go.sum
Labels: size/XS, lgtm

#1530 Release 2.11.0
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1513 !feat: adapt lifecycle-manager only deployment
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/deploy/opts.go
  docs/gen-docs/kyma_alpha_deploy.md
  internal/deploy/bootstrap.go
  internal/deploy/cert_manager.go
  internal/deploy/kyma.go
  internal/kube/client.go
  internal/kustomize/kustomize.go
  internal/nice/summary.go
Labels: size/L, lgtm

#1535 chore: refactor SSA
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/deploy/cmd.go
  go.mod
  go.sum
  internal/deploy/bootstrap.go
  internal/deploy/cert_manager.go
  internal/deploy/kyma.go
  internal/kube/client.go
  internal/kube/kube.go
  internal/kube/mocks/KymaKube.go
  internal/kube/ssa.go
  pkg/module/validation.go
Labels: size/XL, lgtm

#1511 Improve managed runtime detection
  cmd/kyma/deploy/cmd.go
  cmd/kyma/undeploy/cmd.go
  internal/cli/managed.go
  internal/clusterinfo/clusterinfo.go
Labels: size/M, lgtm

#1536 fix: cli constructor for KubeClient
  internal/kube/client.go
Labels: size/S, lgtm

#1537 retry apply kyma
  internal/deploy/kyma.go
Labels: size/XS, lgtm

#1508 Add alpha module enable & disable commands
  cmd/kyma/alpha/alpha.go
  cmd/kyma/alpha/deploy/cmd.go
  cmd/kyma/alpha/disable/disable.go
  cmd/kyma/alpha/disable/module/module.go
  cmd/kyma/alpha/disable/module/opts.go
  cmd/kyma/alpha/enable/enable.go
  cmd/kyma/alpha/enable/module/module.go
  cmd/kyma/alpha/enable/module/opts.go
  cmd/kyma/alpha/list/module/module.go
  cmd/kyma/alpha/list/module/module_test.go
  cmd/kyma/alpha/list/module/opts.go
  docs/gen-docs/kyma_alpha.md
  docs/gen-docs/kyma_alpha_disable.md
  docs/gen-docs/kyma_alpha_disable_module.md
  docs/gen-docs/kyma_alpha_enable.md
  docs/gen-docs/kyma_alpha_enable_module.md
  docs/gen-docs/kyma_alpha_list_module.md
  go.mod
  internal/cli/alpha/module/module.go
  internal/cli/command.go
  internal/cli/defaults.go
Labels: size/XL, lgtm

#1546 fix: add retry on module template apply
  cmd/kyma/alpha/deploy/cmd.go
  internal/deploy/module_templates.go
Labels: size/M, lgtm

#1531 Security Scanners information in Module Template
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/opts.go
  docs/gen-docs/kyma_alpha_create_module.md
  pkg/module/remote.go
  pkg/module/security_scan.go
  pkg/module/template.go
Labels: size/L, lgtm

#1551 alpha create module: Improve Default CR Selection
  pkg/module/kubebuilder/project.go
Labels: size/M, lgtm

#1552 baseURL should not contains schema (https/http)
  pkg/module/build.go
  pkg/module/build_test.go
  pkg/module/remote.go
  pkg/module/sign.go
Labels: size/M, lgtm

#1557 Set provision k8s version to 1.25.6
  cmd/kyma/provision/cmd.go
  docs/gen-docs/kyma_provision_gardener_aws.md
  docs/gen-docs/kyma_provision_gardener_az.md
  docs/gen-docs/kyma_provision_gardener_gcp.md
  docs/gen-docs/kyma_provision_k3d.md
Labels: size/S, lgtm

#1558 Cli should not change operator's image
  .gitignore
  pkg/module/kubebuilder/project.go
Labels: size/S, lgtm
