Repository kyma-project/cli, pull requests merged in 2023-11, with the labels that each got.

#1821 chore: Release 2.20.0
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1831 update code owner
  .github/workflows/lint-golangci.yml
  .github/workflows/test-e2e-create-module.yml
  .github/workflows/test-e2e.yml
  CODEOWNERS
Labels: size/S, lgtm

#1832 stop print out password
  internal/nice/summary.go
Labels: size/XS, lgtm

#1830 chore(github): Adjust PR title linting config
  .github/workflows/lint-conventional-prs.yml
Labels: size/XS, lgtm

#1838 chore: Increase retry count for kustomize applying
  internal/deploy/apply.go
Labels: size/XS, lgtm

#1864 fix: Fix Zip Slip Vulnerability
  internal/deploy/istioctl/istio.go
  internal/deploy/istioctl/istio_test.go
Labels: size/L, lgtm

#1865 fix: Allow creating module for existing versions
  .github/workflows/test-e2e-create-module.yml
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/verify/module/module.go
  internal/kube/mocks/KymaKube.go
  pkg/module/mocks/OciRepoAccess.go
  pkg/module/oci_repo.go
  pkg/module/remote.go
  pkg/module/remote_test.go
  tests/e2e/create_module/kyma_create_module_same_version_test.go
  tests/e2e/create_module/kyma_create_module_test.go
  tests/e2e/util.go
Labels: size/XL, lgtm, cla: yes

#1866 feat: Introduce Mandatory Spec field for ModuleTemplate
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/moduleconfig.go
  cmd/kyma/alpha/create/module/moduleconfig_test.go
  cmd/kyma/alpha/enable/module/mock/mock_interactor.go
  cmd/kyma/alpha/enable/module/module.go
  cmd/kyma/alpha/enable/module/module_test.go
  go.mod
  go.sum
  internal/cli/alpha/module/module.go
  internal/deploy/kyma.go
  pkg/module/custom_state_check.go
  pkg/module/template.go
  pkg/module/template_test.go
  tests/e2e/create_module/kyma_create_module_test.go
  tests/e2e/deploy_enable_disable_test.go
  tests/e2e/util.go
Labels: size/XL, lgtm, cla: yes
