Repository kyma-project/cli, pull requests merged in 2023-01, with the labels that each got.

#1489 Read default CR
  cmd/kyma/alpha/create/module/module.go
  pkg/module/resources.go
Labels: size/S, lgtm

#1498 chore: bump machine image version to 576.12.0 stable
  cmd/kyma/provision/gardener/aws/cmd_test.go
  cmd/kyma/provision/gardener/aws/template.go
  cmd/kyma/provision/gardener/az/cmd_test.go
  cmd/kyma/provision/gardener/az/template.go
  cmd/kyma/provision/gardener/gcp/cmd_test.go
  cmd/kyma/provision/gardener/gcp/template.go
Labels: size/L, lgtm

#1499 chore: bump DefaultKyma2Version to 2.10.0
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: size/XS, lgtm

#1500 add enable-registry-cred flag to cli
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/opts.go
  docs/gen-docs/kyma_alpha_create_module.md
  pkg/module/template.go
Labels: size/M, lgtm

#1504 fix security vulnerabilities
  go.mod
  go.sum
Labels: size/M, lgtm

#1502 Add support for sha256-digest Component Name Mapping
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/opts.go
  cmd/kyma/alpha/sign/module/module.go
  cmd/kyma/alpha/sign/module/opts.go
  docs/gen-docs/kyma_alpha_create_module.md
  docs/gen-docs/kyma_alpha_sign_module.md
  pkg/module/build.go
  pkg/module/build_test.go
  pkg/module/def.go
  pkg/module/remote.go
  pkg/module/resources.go
  pkg/module/sign.go
Labels: size/L, lgtm

#1505 change kubeconfig mount path for dashboard
  pkg/dashboard/dashboard.go
Labels: size/XS, lgtm
