Repository kyma-project/cli, pull requests merged in 2024-04, with the labels that each got.

#2025 Add option to define owner of cluster during provisioning
  internal/cmd/provision/provision.go
Labels: size/XS, lgtm, cla: yes

#2023 add error handling to hana
  internal/cmd/hana/check.go
  internal/cmd/hana/credentials.go
  internal/cmd/hana/delete.go
  internal/cmd/hana/provision.go
  internal/kube/client.go
Labels: kind/feature, area/cli, size/L, lgtm, cla: yes

#2028 Fix secret name in hint msg
  internal/cmd/imageimport/imageimport.go
  internal/registry/config.go
  internal/registry/config_test.go
Labels: size/S, lgtm, cla: yes

#2030 Fix tests
  internal/btp/auth/credentials_test.go
  internal/btp/auth/xsuaa_test.go
  internal/btp/cis/provision_test.go
Labels: size/M, lgtm, cla: yes

#2034 Add Hana cluster mapping
  internal/btp/operator/gvk.go
  internal/cmd/hana/check.go
  internal/cmd/hana/hana.go
  internal/cmd/hana/map.go
  internal/cmd/hana/types.go
  internal/cmd/referenceinstance/referenceinstance.go
  internal/cmd/referenceinstance/resource.go
  internal/kube/unstructured.go
Labels: size/L, lgtm, cla: yes

#2037 better error wrapping
  internal/clierror/cli_error.go
  internal/clierror/cli_error_test.go
  internal/cmd/provision/provision.go
Labels: size/L, lgtm, cla: yes

#2040 Use standard error interface
  internal/btp/auth/credentials.go
  internal/btp/auth/xsuaa.go
  internal/btp/auth/xsuaa_test.go
  internal/btp/cis/provision.go
  internal/btp/cis/provision_test.go
  internal/clierror/cli_error.go
  internal/clierror/cli_error_test.go
  internal/cmd/hana/check.go
  internal/cmd/hana/credentials.go
  internal/cmd/hana/delete.go
  internal/cmd/hana/map.go
  internal/cmd/hana/provision.go
Labels: size/L, lgtm, cla: yes

#2039 Add error hints to kyma provision
  internal/btp/cis/provision.go
  internal/cmd/provision/provision.go
Labels: size/S, lgtm, cla: yes

#2047 Implement common kymaconfig struct
  internal/cmd/hana/check.go
  internal/cmd/hana/credentials.go
  internal/cmd/hana/delete.go
  internal/cmd/hana/hana.go
  internal/cmd/hana/map.go
  internal/cmd/hana/provision.go
  internal/cmd/imageimport/imageimport.go
  internal/cmd/kyma.go
  internal/cmd/referenceinstance/referenceinstance.go
  internal/cmdcommon/kymaconfig.go
Labels: area/cli, size/L, lgtm, kind/cleanup, cla: yes

#2048 Make code about kubeconfig more generic
  internal/cmd/hana/check.go
  internal/cmd/hana/credentials.go
  internal/cmd/hana/delete.go
  internal/cmd/hana/map.go
  internal/cmd/hana/provision.go
  internal/cmd/imageimport/imageimport.go
  internal/cmd/kyma.go
  internal/cmd/referenceinstance/referenceinstance.go
  internal/cmdcommon/kubeconfig.go
Labels: area/cli, size/L, lgtm, kind/cleanup, cla: yes

#2046 Better hana map hints
  internal/cmd/hana/check.go
  internal/cmd/hana/map.go
  internal/kube/service.go
Labels: size/L, lgtm, cla: yes

#2049 Hana map hints
  internal/cmd/hana/map.go
  internal/cmd/hana/provision.go
Labels: size/XS, lgtm, cla: yes

#2050 Mark the `kubeconfig` flag as non required
  internal/cmdcommon/kubeconfig.go
Labels: kind/feature, area/cli, size/XS, lgtm, cla: yes
