Repository kyma-project/cli, pull requests merged in 2024-06, with the labels that each got.

#2124 OIDC: allow retrieving kubeconfig from BTP
  internal/btp/cis/kubeconfig.go
  internal/cmd/oidc/oidc.go
Labels: size/L, lgtm, cla: yes

#2126 Add new catalog flag
  go.mod
  go.sum
  internal/cmd/kyma.go
  internal/cmd/modules/modules.go
Labels: kind/feature, size/M, lgtm, cla: yes

#2125 add json parameters to provision command
  internal/btp/cis/provision.go
  internal/cmd/provision/provision.go
Labels: size/M, lgtm, cla: yes

#2129 Add "managed" flag to "modules" command
  internal/cmd/kyma.go
  internal/cmd/modules/modules.go
Labels: size/L, lgtm, cla: yes

#2130 Add flag --installed to command modules
  internal/cmd/modules/modules.go
  internal/model/types.go
Labels: size/L, lgtm, cla: yes

#2131 Add transport layer that retries requests on error
  internal/registry/image.go
  internal/registry/portforward/retry.go
  internal/registry/portforward/retry_test.go
  internal/registry/portforward/transport.go
Labels: kind/bug, area/cli, size/L, lgtm, cla: yes

#2128 disable running markdown checker on pull and enable on push; standard…
  .github/workflows/markdown.yml
Labels: area/cli, area/ci, size/S, lgtm, kind/cleanup, cla: yes

#2137 add backoff to retry transport layer
  internal/registry/portforward/retry.go
Labels: kind/bug, area/cli, size/S, lgtm, cla: yes

#2139 Add a collective view for the module command
  go.mod
  go.sum
  internal/cmd/modules/modules.go
  internal/model/modules.go
  internal/model/types.go
Labels: size/L, lgtm, cla: yes

#2149 separate visualisation from getting data in command module
  internal/cmd/modules/modules.go
  internal/communitymodules/merge.go
  internal/communitymodules/modules.go
  internal/communitymodules/render.go
Labels: size/L, lgtm, cla: yes

#2147 Move v3 command prototypes into alpha command group
  internal/cmd/alpha/access/access.go
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/hana/check.go
  internal/cmd/alpha/hana/credentials.go
  internal/cmd/alpha/hana/delete.go
  internal/cmd/alpha/hana/hana.go
  internal/cmd/alpha/hana/map.go
  internal/cmd/alpha/hana/provision.go
  internal/cmd/alpha/hana/types.go
  internal/cmd/alpha/imageimport/imageimport.go
  internal/cmd/alpha/modules/modules.go
  internal/cmd/alpha/oidc/oidc.go
  internal/cmd/alpha/provision/provision.go
  internal/cmd/alpha/referenceinstance/referenceinstance.go
  internal/cmd/alpha/referenceinstance/resource.go
  internal/cmd/kyma.go
Labels: size/M, lgtm, cla: yes

#2150 Fix typo in handling errors
  internal/communitymodules/modules.go
Labels: size/XS, lgtm, cla: yes

#2154 test for modules catalog command
  internal/communitymodules/modules.go
  internal/communitymodules/modules_test.go
  internal/communitymodules/types.go
Labels: area/ci, lgtm, kind/chore, cla: yes

#2155 Add namespace flag to reference-instance comamnd
  internal/cmd/alpha/referenceinstance/referenceinstance.go
Labels: size/XS, lgtm, cla: yes

#2156 fix: Change deprecation notice output to stderr
  cmd/main.go
Labels: size/XS, lgtm, cla: yes

#2157 Allow flags even if required resource does not exist
  internal/communitymodules/modules.go
  internal/communitymodules/modules_test.go
  internal/communitymodules/render.go
Labels: kind/feature, area/cli, size/M, lgtm, cla: yes

#2148 Add unit tests
  .github/actions/rebase/action.yaml
  .github/workflows/unit-test.yaml
  Makefile
  internal/btp/auth/xsuaa_test.go
  internal/btp/cis/client_test.go
  internal/btp/cis/provision_test.go
Labels: size/M, lgtm, cla: yes

#2153 Add unstable release job
  .github/workflows/pre-release-release.yaml
  .github/workflows/pre-release-tag.yaml
  .gitignore
  .goreleaser-dev.yml
Labels: size/L, lgtm, cla: yes

#2151 Partial tests for Community Modules package
  internal/communitymodules/merge.go
  internal/communitymodules/merge_test.go
  internal/communitymodules/render_test.go
Labels: size/L, lgtm, area/tests, cla: yes

#2160 Fix pre-release trigger
  .github/workflows/pre-release-release.yaml
  .github/workflows/pre-release-tag.yaml
Labels: size/S, lgtm, cla: yes

#2159 Lint fixes
  internal/btp/cis/client.go
  internal/cmd/alpha/access/access.go
  internal/cmd/alpha/hana/check.go
  internal/cmd/alpha/hana/credentials.go
  internal/cmd/alpha/hana/delete.go
  internal/cmd/alpha/hana/map.go
  internal/cmd/alpha/hana/provision.go
  internal/cmd/alpha/imageimport/imageimport.go
  internal/cmd/alpha/modules/modules.go
  internal/cmd/alpha/oidc/oidc.go
  internal/cmd/kyma.go
  internal/communitymodules/render.go
  internal/kube/client.go
  internal/kube/fake/client.go
  internal/registry/config.go
  internal/registry/config_test.go
Labels: size/L, lgtm, cla: yes

#2161 Update pre-release message
  .goreleaser-dev.yml
Labels: size/XS, lgtm, cla: yes

#2146 restore go linter job
  .github/workflows/lint-golangci.yml
  .golangci.yml
  Makefile
  hack/tools.mk
Labels: size/M, lgtm, cla: yes
