Repository kyma-project/cli, pull requests merged in 2024-05, with the labels that each got.

#2072 Support DockerRegistry CR in the `image-import` command
  internal/cmd/imageimport/imageimport.go
  internal/kube/unstructured.go
  internal/registry/config.go
  internal/registry/config_test.go
  internal/registry/types.go
Labels: kind/feature, area/cli, size/L, lgtm, cla: yes

#2067 Add Kyma Access command to CLI
  go.mod
  go.sum
  internal/cmd/access/access.go
  internal/cmd/kyma.go
Labels: kind/feature, area/cli, size/L, lgtm, cla: yes

#2074 add dependabot definition
  .github/dependabot.yml
Labels: size/S, lgtm, cla: yes

#2076 Use clierrors package when handling Access command errors
  internal/cmd/access/access.go
Labels: size/S, lgtm, cla: yes

#2082 Add fancy errors for the `image-import` cmd
  internal/cmd/imageimport/imageimport.go
  internal/registry/config.go
  internal/registry/image.go
  internal/registry/image_test.go
Labels: area/cli, size/M, lgtm, kind/chore, cla: yes

#2084 Use the `clierror.Wrap` func in all possible cases
  go.mod
  go.sum
  internal/btp/auth/credentials.go
  internal/btp/auth/xsuaa.go
  internal/btp/cis/provision.go
  internal/clierror/error.go
  internal/clierror/error_test.go
  internal/clierror/wrap.go
  internal/cmd/hana/check.go
  internal/cmd/hana/credentials.go
  internal/cmd/hana/delete.go
  internal/cmd/hana/map.go
  internal/cmd/hana/provision.go
  internal/cmd/provision/provision.go
  internal/kube/client.go
  internal/kube/service.go
Labels: area/cli, size/L, lgtm, kind/chore, cla: yes

#2092 Get rid of modifiers in the `clierror` package
  internal/btp/auth/credentials.go
  internal/btp/auth/credentials_test.go
  internal/btp/auth/xsuaa.go
  internal/btp/auth/xsuaa_test.go
  internal/btp/cis/provision.go
  internal/btp/cis/provision_test.go
  internal/clierror/check.go
  internal/clierror/error.go
  internal/clierror/error_test.go
  internal/clierror/params.go
  internal/clierror/wrap.go
  internal/clierror/wrap_test.go
  internal/cmd/access/access.go
  internal/cmd/hana/check.go
  internal/cmd/hana/credentials.go
  internal/cmd/hana/delete.go
  internal/cmd/hana/map.go
  internal/cmd/hana/provision.go
  internal/cmd/imageimport/imageimport.go
  internal/cmd/provision/provision.go
  internal/cmd/referenceinstance/referenceinstance.go
  internal/cmdcommon/kubeconfig.go
  internal/kube/client.go
  internal/kube/service.go
  internal/registry/config.go
  internal/registry/config_test.go
  internal/registry/image.go
  internal/registry/image_test.go
Labels: area/cli, size/XL, lgtm, kind/cleanup, cla: yes

#2095 chore: Deprecate kyma-cli v2
  README.md
  cmd/main.go
Labels: area/cli, size/XS, lgtm, kind/chore, cla: yes

#2096 chore: Deprecate kyma-cli v2
  README.md
  cmd/main.go
Labels: area/cli, size/XS, lgtm, kind/chore, cla: yes

#2097 chore: Update the default `kyma-cli` version
  docs/gen-docs/kyma_deploy.md
  internal/config/config.go
Labels: area/cli, size/XS, lgtm, kind/chore, cla: yes

#2098 chore: Cherry-pick minor fixes from main
  CODEOWNERS
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/init/function/function.go
  cmd/kyma/init/function/function_test.go
  cmd/kyma/run/function/function.go
  docs/gen-docs/kyma_init_function.md
  go.mod
  go.sum
  pkg/module/oci_repo.go
Labels: area/cli, size/XL, lgtm, kind/chore, cla: yes

#2106 Add missing files and badges
  .golangci.yml
  .goreleaser.yml
  README.md
  sec-scanners-config.yaml
Labels: area/cli, size/M, lgtm, kind/chore, cla: yes

#2107 Rename the `LICENSE` file
  LICENCE
Labels: area/cli, size/XS, lgtm, kind/chore, cla: yes

#2108 Add missing license file
  LICENSES/Apache-2.0.txt
Labels: area/cli, size/M, lgtm, kind/chore, cla: yes

#2111 Fix codeowners
  CODEOWNERS
Labels: size/XS, lgtm, cla: yes

#2109 Update readme to include v3 command execution
  README.md
Labels: size/M, lgtm, cla: yes

#2113 Fix typo in kubeconfig flag help
  internal/cmdcommon/kubeconfig.go
Labels: size/XS, lgtm, cla: yes

#2116 Add OIDC command
  internal/cmd/kyma.go
  internal/cmd/oidc/oidc.go
Labels: size/L, lgtm, cla: yes

#2121 Move kubeconfig saving/printing to a common package
  internal/cmd/access/access.go
  internal/cmd/oidc/oidc.go
  internal/kube/config.go
Labels: size/M, lgtm, cla: yes

#2122 Allow users to provide OIDC token explicitly
  internal/cmd/oidc/oidc.go
Labels: size/S, lgtm, cla: yes

#2120 New Kyma Access CMD v2
  internal/cmd/access/access.go
  internal/kube/client.go
Labels: size/L, lgtm, cla: yes

#2123 OIDC: allow providing whole Kubeconfig
  internal/cmd/oidc/oidc.go
Labels: size/S, lgtm, cla: yes
