Repository kyma-project/cli, pull requests merged in 2024-07, with the labels that each got.

#2163 Fix used linter action version
  .github/workflows/lint-golangci.yml
Labels: size/XS, lgtm, cla: yes

#2162 Document Instructions how to install kyma@v3 binary
  README.md
  hack/get-kyma-v3-alpha.sh
Labels: area/documentation, size/M, lgtm, cla: yes

#2166 Change control-plane field to managed
  internal/communitymodules/modules.go
  internal/communitymodules/render.go
Labels: size/XS, lgtm, cla: yes

#2167 Document Instructions how to install kyma@v3 binary
  README.md
  hack/get-kyma-v3-alpha.sh
Labels: area/documentation, lgtm, cla: yes

#2164 add test for modules managed command
  internal/communitymodules/modules.go
  internal/communitymodules/modules_test.go
  internal/communitymodules/types.go
Labels: area/cli, size/L, lgtm, kind/chore, cla: yes

#2169 Update DockerRegistry CR types
  internal/registry/config.go
  internal/registry/config_test.go
  internal/registry/types.go
Labels: kind/bug, area/serverless, size/S, lgtm, cla: yes

#2165 Add deploy and undeploy managed commands
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/deploy/deploy.go
  internal/cmd/alpha/deploy/managed/managed.go
  internal/cmd/alpha/undeploy/managed/managed.go
  internal/cmd/alpha/undeploy/undeploy.go
  internal/communitymodules/modules.go
  internal/kyma/kyma.go
  internal/kyma/types.go
Labels: size/L, lgtm, cla: yes

#2170 add test for modules installed command
  internal/communitymodules/modules_test.go
Labels: area/cli, size/L, lgtm, kind/chore, cla: yes

#2171 fix finding latest version of module in command modules catalog
  go.mod
  internal/communitymodules/modules.go
  internal/communitymodules/modules_test.go
Labels: kind/bug, area/cli, size/L, lgtm, cla: yes

#2174 Cover the case when one of the repository fields is empty in Modules command
  internal/communitymodules/modules.go
  internal/communitymodules/modules_test.go
  internal/communitymodules/types.go
Labels: size/M, lgtm, cla: yes

#2177 tests for hana check
  internal/cmd/alpha/hana/check_test.go
Labels: area/cli, kind/missing-test, size/L, lgtm, cla: yes

#2173 modules render refactor
  internal/cmd/alpha/modules/modules.go
  internal/communitymodules/render.go
  internal/communitymodules/render_test.go
Labels: area/cli, size/L, lgtm, kind/cleanup, cla: yes

#2178 Add oidc test
  go.mod
  go.sum
  internal/cmd/alpha/oidc/oidc_test.go
Labels: size/L, lgtm, cla: yes

#2176 add deploy managed tests
  internal/cmd/alpha/deploy/managed/managed.go
  internal/cmd/alpha/deploy/managed/managed_test.go
Labels: size/L, lgtm, cla: yes

#2175 add undeploy managed tests
  internal/cmd/alpha/undeploy/managed/managed.go
  internal/cmd/alpha/undeploy/managed/managed_test.go
Labels: size/L, lgtm, cla: yes

#2182 Rename un-/deploy to remove/add
  internal/cmd/alpha/add/add.go
  internal/cmd/alpha/add/managed/managed.go
  internal/cmd/alpha/add/managed/managed_test.go
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/deploy/deploy.go
  internal/cmd/alpha/remove/managed/managed.go
  internal/cmd/alpha/remove/managed/managed_test.go
  internal/cmd/alpha/remove/undeploy.go
  internal/cmd/alpha/undeploy/undeploy.go
Labels: size/L, lgtm, cla: yes, kind/enhancement

#2181 simplify table view
  internal/communitymodules/render.go
Labels: size/XS, lgtm, cla: yes

#2184 Remove whitespace prefix
  internal/communitymodules/render.go
Labels: area/cli, size/XS, lgtm, kind/chore, cla: yes

#2185 Use the typed kyma CR
  internal/communitymodules/modules.go
  internal/communitymodules/modules_test.go
  internal/kyma/types.go
Labels: area/cli, size/L, lgtm, kind/chore, cla: yes

#2186 Replace managed with channel
  internal/communitymodules/merge.go
  internal/communitymodules/merge_test.go
  internal/communitymodules/modules.go
  internal/communitymodules/modules_test.go
  internal/communitymodules/render.go
  internal/communitymodules/render_test.go
Labels: kind/feature, area/cli, size/M, lgtm, cla: yes

#2187 Do not work on unstructured Kyma CR
  internal/cmd/alpha/add/managed/managed.go
  internal/cmd/alpha/add/managed/managed_test.go
  internal/cmd/alpha/remove/managed/managed.go
  internal/cmd/alpha/remove/managed/managed_test.go
  internal/communitymodules/modules.go
  internal/kyma/kyma.go
  internal/kyma/kyma_test.go
Labels: area/cli, size/L, lgtm, kind/chore, cla: yes

#2188 Move all operations on the Kubernetes resources under the `kube` pkg
  internal/btp/operator/gvk.go
  internal/btp/operator/gvr.go
  internal/cmd/alpha/add/managed/managed.go
  internal/cmd/alpha/add/managed/managed_test.go
  internal/cmd/alpha/hana/check.go
  internal/cmd/alpha/hana/check_test.go
  internal/cmd/alpha/hana/delete.go
  internal/cmd/alpha/hana/map.go
  internal/cmd/alpha/hana/provision.go
  internal/cmd/alpha/referenceinstance/referenceinstance.go
  internal/cmd/alpha/remove/managed/managed.go
  internal/cmd/alpha/remove/managed/managed_test.go
  internal/communitymodules/modules.go
  internal/kube/btp/service.go
  internal/kube/btp/types.go
  internal/kube/kyma/kyma.go
  internal/kube/kyma/kyma_test.go
  internal/kube/kyma/types.go
  internal/kube/unstructured.go
Labels: area/cli, size/L, lgtm, kind/chore, cla: yes

#2189 Replace unstructured types
  internal/cmd/alpha/hana/map.go
  internal/cmd/alpha/hana/provision.go
  internal/cmd/alpha/hana/types.go
  internal/cmd/alpha/referenceinstance/referenceinstance.go
  internal/kube/btp/types.go
Labels: area/cli, size/L, lgtm, kind/cleanup, cla: yes

#2190 Implement kyma client
  internal/cmd/alpha/add/managed/managed.go
  internal/cmd/alpha/add/managed/managed_test.go
  internal/cmd/alpha/remove/managed/managed.go
  internal/cmd/alpha/remove/managed/managed_test.go
  internal/communitymodules/modules.go
  internal/communitymodules/modules_test.go
  internal/kube/client.go
  internal/kube/fake/client.go
  internal/kube/kyma/kyma.go
  internal/kube/kyma/kyma_test.go
Labels: area/cli, size/XL, lgtm, kind/chore, cla: yes

#2191 Btp strict types
  internal/cmd/alpha/hana/check.go
  internal/cmd/alpha/hana/check_test.go
  internal/cmd/alpha/hana/map.go
  internal/cmd/alpha/hana/provision.go
  internal/kube/btp/service.go
  internal/kube/btp/types.go
Labels: area/cli, size/L, lgtm, kind/chore, cla: yes

#2194 Add missing tests for the `check` command
  internal/cmd/alpha/hana/check.go
  internal/cmd/alpha/hana/check_test.go
Labels: area/cli, size/M, lgtm, cla: yes, kind/enhancement

#2193 Cover btp package with tests
  internal/kube/btp/service_test.go
  internal/kube/btp/types.go
Labels: area/cli, size/L, lgtm, cla: yes, kind/enhancement

#2197 Alpha Add command for Kyma CLI
  go.mod
  go.sum
  internal/cmd/alpha/add/add.go
  internal/communitymodules/modules.go
  internal/communitymodules/modules_test.go
  internal/communitymodules/types.go
  internal/kube/client.go
  internal/kube/fake/client.go
  internal/kube/rootlessdynamic/client.go
Labels: kind/feature, area/cli, size/L, lgtm, cla: yes

#2200 Use discovery to check if resource is namespaced
  internal/cmd/alpha/add/add.go
  internal/kube/rootlessdynamic/client.go
Labels: kind/bug, area/cli, size/M, lgtm, cla: yes
