Repository kyma-project/cli, pull requests merged in 2024-12, with the labels that each got.

#2268 Improve `alpha module list` command UX
  internal/cmd/alpha/modules/modules.go
  internal/modules/modules.go
  internal/modules/modules_test.go
  internal/modules/render.go
  internal/modules/render_test.go
Labels: area/cli, size/M, lgtm, kind/cleanup, cla: yes

#2267 feat: Add dry-run flag to prevent pushing module template to registry
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/opts.go
  docs/gen-docs/kyma_alpha_create_module.md
  internal/resolve/resolve_test.go
Labels: size/S, cla: yes

#2270 Support basic cloud native buildpack for the `kyma alpha app push` command
  go.mod
  go.sum
  internal/cmd/alpha/app/push.go
  internal/cmdcommon/extension.go
  internal/cmdcommon/extension_types.go
  internal/pack/build.go
Labels: kind/feature, area/cli, size/XL, lgtm, cla: yes

#2273 Support args while building from dockerfile
  internal/cmd/alpha/app/push.go
  internal/cmdcommon/types/map.go
  internal/cmdcommon/types/map_test.go
  internal/dockerfile/build.go
Labels: kind/feature, area/cli, size/M, lgtm, cla: yes

#2275 Increase deploy limits
  internal/kube/resources/resources.go
Labels: area/cli, size/XS, lgtm, kind/chore, cla: yes

#2278 Enable `kyma alpha app push` cache
  internal/pack/build.go
Labels: area/cli, size/S, lgtm, cla: yes

#2281 Fake RootlessDynamic client
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/module/list.go
  internal/cmd/alpha/module/module.go
  internal/kube/resources/resources_test.go
  internal/kube/rootlessdynamic/fake.go
Labels: area/cli, size/L, lgtm, kind/cleanup, cla: yes

#2283 Add `module enable` command
  internal/cmd/alpha/module/enable.go
  internal/cmd/alpha/module/list.go
  internal/cmd/alpha/module/module.go
  internal/cmdcommon/extension_test.go
  internal/kube/fake/kube.go
  internal/kube/fake/kyma.go
  internal/kube/fake/rootlessdynamic.go
  internal/kube/kyma/kyma.go
  internal/kube/kyma/kyma_test.go
  internal/kube/kyma/types.go
  internal/kube/resources/resources_test.go
  internal/kube/rootlessdynamic/client.go
  internal/kubeconfig/kubeconfig_test.go
  internal/modules/enable.go
  internal/modules/enable_test.go
  internal/registry/config_test.go
Labels: kind/feature, area/cli, size/XL, lgtm, cla: yes

#2288 Hint user about wrong docker-registry configuration
  internal/cmd/alpha/app/push.go
Labels: area/cli, size/XS, cla: yes, kind/enhancement

#2282 Add `module disable` command
  internal/cmd/alpha/module/disable.go
  internal/cmd/alpha/module/module.go
  internal/cmdcommon/types/map_test.go
  internal/kube/fake/rootlessdynamic.go
  internal/kube/kyma/kyma.go
  internal/kube/kyma/kyma_test.go
  internal/kube/rootlessdynamic/client.go
  internal/kube/rootlessdynamic/client_test.go
  internal/modules/disable.go
  internal/modules/disable_test.go
Labels: kind/feature, area/cli, size/XL, lgtm, cla: yes

#2293 Improve error message about missing registry
  internal/cmd/alpha/app/push.go
  internal/cmd/alpha/registry/config/config.go
  internal/cmd/alpha/registry/imageimport/imageimport.go
  internal/registry/config.go
Labels: area/cli, size/S, lgtm, cla: yes, kind/enhancement

#2272 add STATE column to modules list
  internal/cmd/alpha/module/list.go
  internal/kube/kyma/types.go
  internal/kube/rootlessdynamic/fake.go
  internal/modules/list.go
  internal/modules/list_test.go
  internal/modules/render.go
  internal/modules/render_test.go
Labels: size/XL, cla: yes

#2298 Rename Enable/Disable to Add/Delete
  internal/cmd/alpha/module/add.go
  internal/cmd/alpha/module/delete.go
  internal/cmd/alpha/module/module.go
Labels: size/M, lgtm, cla: yes

#2297 Improve missing in-cluster registry hint suffix
  internal/cmd/alpha/module/add.go
  internal/registry/config.go
Labels: area/cli, size/XS, lgtm, cla: yes, kind/enhancement

#2302 Change hint msg after module commands renaming
  internal/registry/config.go
Labels: size/XS, lgtm, cla: yes
