Repository kyma-project/cli, pull requests merged in 2024-11, with the labels that each got.

#2233 Support coreCommands extensions
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/registry/imageimport/imageimport.go
  internal/cmd/alpha/registry/registry.go
  internal/cmdcommon/extension.go
  internal/cmdcommon/extension_test.go
  internal/cmdcommon/extension_types.go
Labels: kind/feature, area/cli, size/L, lgtm, cla: yes

#2234 Stop failing when cluster is down
  internal/cmd/alpha/hana/check.go
  internal/cmd/alpha/hana/credentials.go
  internal/cmd/alpha/hana/delete.go
  internal/cmd/alpha/hana/map.go
  internal/cmd/alpha/hana/provision.go
  internal/cmd/alpha/modules/modules.go
  internal/cmd/alpha/oidc/oidc.go
  internal/cmd/alpha/referenceinstance/referenceinstance.go
  internal/cmd/alpha/registry/config/config.go
  internal/cmd/alpha/registry/imageimport/imageimport.go
  internal/cmd/alpha/remove/managed/managed.go
  internal/cmd/alpha/remove/remove.go
  internal/cmdcommon/extension.go
  internal/cmdcommon/extension_test.go
  internal/cmdcommon/kubeconfig.go
  internal/cmdcommon/kymaconfig.go
  internal/kube/client.go
Labels: kind/bug, area/cli, size/L, lgtm, cla: yes

#2244 Guide user on how to extract extension error
  internal/cmdcommon/extension.go
Labels: area/cli, size/XS, lgtm, cla: yes, kind/enhancement

#2242 Added the new Hana Map command that fulfills the new CLI requirements
  internal/btp/hana/auth.go
  internal/btp/hana/hana.go
  internal/btp/hana/hana_test.go
  internal/btp/hana/map.go
  internal/btp/hana/map_test.go
  internal/btp/hana/types.go
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/hana/hana.go
  internal/cmd/alpha/hana/map.go
Labels: kind/feature, area/cli, lgtm

#2245 pin linter action
  .github/workflows/lint-golangci.yml
Labels: size/XS, cla: yes

#2246 Add app push command
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/app/app.go
  internal/cmd/alpha/app/push.go
  internal/kube/resources/resources.go
  internal/kube/resources/resources_test.go
Labels: size/L, lgtm, cla: yes

#2248 add istio injection flag
  internal/cmd/alpha/app/push.go
  internal/cmdcommon/types/nullableBool.go
  internal/cmdcommon/types/nullableBool_test.go
  internal/kube/resources/resources.go
  internal/kube/resources/resources_test.go
Labels: size/L, lgtm, cla: yes

#2249 Implement image building in the `kyma alpha app push` command
  go.mod
  go.sum
  internal/cmd/alpha/app/push.go
  internal/dockerfile/build.go
  internal/dockerfile/build_test.go
  internal/kube/resources/resources.go
  internal/kube/resources/resources_test.go
Labels: kind/feature, area/cli, size/XL, lgtm, cla: yes

#2250 Create service when pushing an application via `kyma alpha app push --containerport`
  internal/cmd/alpha/app/push.go
  internal/cmdcommon/types/nullablebool.go
  internal/cmdcommon/types/nullablebool_test.go
  internal/cmdcommon/types/nullableint.go
  internal/kube/resources/resources.go
  internal/kube/resources/resources_test.go
Labels: size/L, lgtm, cla: yes

#2255 Bump Go dependencies
  go.mod
  go.sum
Labels: size/M, lgtm, cla: yes

#2254 Add `--expose` flag to `kyma app push`
  go.mod
  go.sum
  internal/cmd/alpha/app/push.go
  internal/kube/client.go
  internal/kube/fake/client.go
  internal/kube/istio/istio.go
  internal/kube/resources/resources.go
  internal/kube/resources/resources_test.go
  internal/kube/rootlessdynamic/client.go
Labels: size/L, lgtm, cla: yes

#2261 List modules based on ModuleTemplates
  internal/cmd/alpha/modules/list.go
  internal/cmd/alpha/modules/modules.go
  internal/kube/kyma/kyma.go
  internal/kube/kyma/kyma_test.go
  internal/kube/kyma/types.go
  internal/modules/modules.go
  internal/modules/modules_test.go
  internal/modules/render.go
  internal/modules/render_test.go
Labels: size/XL, cla: yes

#2265 Remove old modules-related commands and code
  go.mod
  go.sum
  internal/cmd/alpha/add/add.go
  internal/cmd/alpha/add/managed/managed.go
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/remove/managed/managed.go
  internal/cmd/alpha/remove/remove.go
  internal/communitymodules/cluster/modules.go
  internal/communitymodules/cluster/modules_test.go
  internal/communitymodules/cluster/namespace.go
  internal/communitymodules/cluster/namespace_test.go
  internal/communitymodules/merge.go
  internal/communitymodules/merge_test.go
  internal/communitymodules/modules.go
  internal/communitymodules/modules_test.go
  internal/communitymodules/render.go
  internal/communitymodules/render_test.go
  internal/communitymodules/types.go
Labels: area/ci, size/XXL, lgtm, kind/cleanup, cla: yes

#2263 Implement `INSTALLED` and `MANAGED` headers for table view when listing modules
  internal/kube/kyma/kyma.go
  internal/kube/kyma/types.go
  internal/modules/modules.go
  internal/modules/modules_test.go
  internal/modules/render.go
  internal/modules/render_test.go
Labels: kind/feature, area/cli, size/L, lgtm, cla: yes

#2266 Remove `alpha modules` run execution
  internal/cmd/alpha/modules/modules.go
Labels: area/ci, size/XS, lgtm, kind/cleanup, cla: yes
