Repository kyma-project/cli, pull requests merged in 2024-01, with the labels that each got.

#1909 chore: Remove Module Validation from create module command
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/module_test.go
  internal/cli/setup/envtest/setup.go
  internal/envtest/envtest.go
  pkg/module/crd_reader.go
  pkg/module/def.go
  pkg/module/validation.go
  pkg/module/validation_test.go
Labels: size/XXL, lgtm, cla: yes

#1859 feat: Add Scaffold Command
  .github/workflows/test-e2e-create-scaffold.yml
  cmd/kyma/alpha/create/create.go
  cmd/kyma/alpha/create/module/moduleconfig.go
  cmd/kyma/alpha/create/scaffold/opts.go
  cmd/kyma/alpha/create/scaffold/scaffold.go
  docs/gen-docs/kyma_alpha_create.md
  docs/gen-docs/kyma_alpha_create_scaffold.md
  pkg/module/scaffold/default_cr.go
  pkg/module/scaffold/manifest.go
  pkg/module/scaffold/module_config.go
  pkg/module/scaffold/scaffold.go
  pkg/module/scaffold/security_config.go
  pkg/module/scaffold/utils.go
  pkg/module/scaffold/utils_test.go
  pkg/module/security_scan.go
  tests/e2e/Makefile
  tests/e2e/create_scaffold/scaffold_suite_test.go
  tests/e2e/create_scaffold/scaffold_test.go
Labels: size/XXL, lgtm, cla: yes

#1913 feat: Set 1.27.9 as default K8s Version
  cmd/kyma/provision/cmd.go
  cmd/kyma/provision/gardener/aws/cmd.go
  cmd/kyma/provision/gardener/gcp/cmd.go
  docs/gen-docs/kyma_provision_gardener_aws.md
  docs/gen-docs/kyma_provision_gardener_az.md
  docs/gen-docs/kyma_provision_gardener_gcp.md
  docs/gen-docs/kyma_provision_k3d.md
Labels: size/S, lgtm, cla: yes

#1922 fix: Invalid paths in generated module-config-file
  cmd/kyma/alpha/create/scaffold/opts.go
  cmd/kyma/alpha/create/scaffold/scaffold.go
  pkg/module/scaffold/default_cr.go
  pkg/module/scaffold/manifest.go
  pkg/module/scaffold/module_config.go
  pkg/module/scaffold/scaffold.go
  pkg/module/scaffold/security_config.go
Labels: size/M, lgtm, cla: yes

#1920 deps: Upgrade k8s to 1.29.1
  go.mod
  go.sum
Labels: size/M, lgtm, cla: yes

#1927 feat: Release 2.20.2
  .github/workflows/pull-cli-build.yaml
  .github/workflows/pull-cli-docs.yaml
  .github/workflows/pull-cli-unit-test.yaml
  .github/workflows/report-sprint-commits.yml
  .github/workflows/test-e2e-create-scaffold.yml
  cmd/kyma/alpha/create/create.go
  cmd/kyma/alpha/create/module/module.go
  cmd/kyma/alpha/create/module/module_test.go
  cmd/kyma/alpha/create/module/moduleconfig.go
  cmd/kyma/alpha/create/module/opts.go
  cmd/kyma/alpha/create/scaffold/opts.go
  cmd/kyma/alpha/create/scaffold/scaffold.go
  cmd/kyma/provision/cmd.go
  cmd/kyma/provision/gardener/aws/cmd.go
  cmd/kyma/provision/gardener/gcp/cmd.go
  docs/gen-docs/kyma_alpha_create.md
  docs/gen-docs/kyma_alpha_create_module.md
  docs/gen-docs/kyma_alpha_create_scaffold.md
  docs/gen-docs/kyma_provision_gardener_aws.md
  docs/gen-docs/kyma_provision_gardener_az.md
  docs/gen-docs/kyma_provision_gardener_gcp.md
  docs/gen-docs/kyma_provision_k3d.md
  go.mod
  go.sum
  internal/cli/setup/envtest/setup.go
  internal/envtest/envtest.go
  internal/k3d/k3d.go
  internal/net/net_test.go
  internal/version/compatibility.go
  pkg/module/crd_reader.go
  pkg/module/def.go
  pkg/module/scaffold/default_cr.go
  pkg/module/scaffold/manifest.go
  pkg/module/scaffold/module_config.go
  pkg/module/scaffold/scaffold.go
  pkg/module/scaffold/security_config.go
  pkg/module/scaffold/utils.go
  pkg/module/scaffold/utils_test.go
  pkg/module/security_scan.go
  pkg/module/tmp_files.go
  pkg/module/tmp_files_test.go
  pkg/module/validation.go
  pkg/module/validation_test.go
  prow/pre-cli-e2e.sh
  tests/e2e/Makefile
  tests/e2e/create_scaffold/scaffold_suite_test.go
  tests/e2e/create_scaffold/scaffold_test.go
Labels: size/XXL, lgtm, cla: yes

#1928 chore(deps): Bump github.com/opencontainers/image-spec
  go.mod
  go.sum
Labels: size/XS, lgtm, cla: yes
