Repository kyma-project/cli, pull requests merged in 2024-08, with the labels that each got.

#2201 Test the `kyma alpha add` command
  internal/cmd/alpha/add/add.go
  internal/communitymodules/cluster/modules.go
  internal/communitymodules/cluster/modules_test.go
  internal/communitymodules/cluster/namespace.go
  internal/communitymodules/cluster/namespace_test.go
  internal/kube/rootlessdynamic/client.go
  internal/kube/rootlessdynamic/client_test.go
Labels: size/XL, lgtm, cla: yes

#2203 Add tests to access command
  internal/cmd/alpha/access/access.go
  internal/kube/resources/resources.go
  internal/kube/resources/resources_test.go
  internal/kubeconfig/kubeconfig.go
  internal/kubeconfig/kubeconfig_test.go
Labels: size/XL, lgtm, cla: yes

#2204 Refactor and test the cluster pkg
  internal/cmd/alpha/add/add.go
  internal/communitymodules/cluster/modules.go
  internal/communitymodules/cluster/modules_test.go
  internal/communitymodules/modules.go
  internal/kube/client.go
  internal/kube/resources/unstructured.go
  internal/kube/resources/unstructured_test.go
  internal/kube/rootlessdynamic/client.go
Labels: area/cli, kind/missing-test, size/L, lgtm, cla: yes

#2207 refactor the `ApplySpecifiedModules` func
  internal/communitymodules/cluster/modules.go
  internal/communitymodules/cluster/modules_test.go
  internal/communitymodules/types.go
  internal/kube/rootlessdynamic/client.go
  internal/kube/rootlessdynamic/client_test.go
Labels: area/cli, kind/missing-test, size/L, lgtm, cla: yes

#2210 Download module manifest and cr manually from GitHub url
  internal/communitymodules/cluster/modules.go
  internal/communitymodules/cluster/modules_test.go
  internal/communitymodules/types.go
Labels: area/cli, size/L, lgtm, kind/cleanup, cla: yes

#2211 Change error from Clierror to regular in rootlessdynamic client
  internal/communitymodules/cluster/modules.go
  internal/communitymodules/cluster/modules_test.go
  internal/kube/rootlessdynamic/client.go
  internal/kube/rootlessdynamic/client_test.go
Labels: size/M, lgtm, cla: yes

#2212 Add command to remove modules
  go.mod
  go.sum
  internal/cmd/alpha/remove/remove.go
  internal/cmd/alpha/remove/undeploy.go
  internal/communitymodules/cluster/modules.go
  internal/communitymodules/cluster/modules_test.go
  internal/kube/rootlessdynamic/client.go
  internal/kube/rootlessdynamic/client_test.go
Labels: kind/feature, size/L, lgtm, cla: yes
