Repository kyma-project/cli, pull requests merged in 2024-03, with the labels that each got.

#1974 chore: Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm, cla: yes

#1977 v3: Refactor cis package
  internal/btp/auth/credentials.go
  internal/btp/auth/credentials_test.go
  internal/btp/auth/xsuaa.go
  internal/btp/auth/xsuaa_test.go
  internal/btp/cis/client.go
  internal/btp/cis/client_test.go
  internal/btp/cis/provision.go
  internal/btp/cis/provision_test.go
  internal/cmd/provision/provision.go
Labels: area/cli, size/M, lgtm, kind/cleanup, cla: yes

#1976 chore: Add Python 3.12 environment
  cmd/kyma/init/function/function.go
  cmd/kyma/run/function/function.go
  docs/gen-docs/kyma_init_function.md
Labels: size/S, lgtm, cla: yes

#1984 Implement kubernetes client
  internal/kube/client.go
  internal/kube/config.go
Labels: kind/feature, area/cli, size/M, lgtm, cla: yes

#1985 chore: Remove Nodejs16 environment
  cmd/kyma/init/function/function.go
  cmd/kyma/run/function/function.go
  docs/gen-docs/kyma_init_function.md
Labels: area/serverless, size/XS, lgtm, kind/chore, cla: yes

#1982 chore: Add Nodejs20 environment
  cmd/kyma/init/function/function.go
  cmd/kyma/run/function/function.go
  docs/gen-docs/kyma_init_function.md
Labels: area/serverless, size/XS, lgtm, kind/chore, cla: yes

#1998 fix: Bump hydroform
  go.mod
  go.sum
Labels: size/XS, lgtm, cla: yes

#2005 chore: Deprecate Nodejs18 environment
  cmd/kyma/init/function/function.go
  docs/gen-docs/kyma_init_function.md
Labels: size/XS, lgtm, cla: yes

#2003 fix: Security config ignored
  cmd/kyma/alpha/create/module/module.go
Labels: size/M, lgtm, cla: yes

#2006 chore: Make Nodejs20 default runtime
  cmd/kyma/init/function/function.go
  cmd/kyma/init/function/function_test.go
  docs/gen-docs/kyma_init_function.md
Labels: size/XS, lgtm, cla: yes

#2008 Test the `transport.go` file
  go.mod
  go.sum
  internal/registry/portforward/automock/connection.go
  internal/registry/portforward/automock/stream.go
  internal/registry/portforward/transport_mock.go
  internal/registry/portforward/transport_test.go
Labels: area/cli, kind/missing-test, size/L, lgtm, cla: yes

#1994 Propose error output format
  docs/contributor/ADR/001-error-output-format.md
Labels: kind/feature, area/cli, size/M, lgtm, cla: yes

#2002 Tests for registry/config.go
  go.mod
  go.sum
  internal/registry/config_test.go
Labels: size/L, lgtm, area/tests, cla: yes

#2009 Test the `image.go` file
  internal/registry/image.go
  internal/registry/image_test.go
  internal/registry/portforward/transport.go
Labels: area/cli, kind/missing-test, size/L, lgtm, cla: yes

#2010 add hana provision
  go.mod
  go.sum
  internal/cmd/hana/hana.go
  internal/cmd/hana/provision.go
  internal/cmd/kyma.go
  internal/kube/client.go
Labels: kind/feature, area/cli, size/L, lgtm, cla: yes

#2011 add creating bindings for hana
  internal/btp/operator/gvr.go
  internal/cmd/hana/provision.go
Labels: kind/feature, area/cli, size/L, lgtm, cla: yes

#2014 Change the example to use secret instead of service account
  internal/cmd/imageimport/imageimport.go
Labels: size/XS, lgtm, cla: yes

#2012 add print hana credentials command
  internal/cmd/hana/credentials.go
  internal/cmd/hana/hana.go
Labels: kind/feature, area/cli, size/M, lgtm, cla: yes

#2013 Implement better error handling
  internal/clierror/cli_error.go
  internal/clierror/cli_error_test.go
  internal/cmd/kyma.go
  internal/cmd/provision/provision.go
  main.go
Labels: size/L, lgtm, cla: yes

#2016 add command hana check
  internal/cmd/hana/check.go
  internal/cmd/hana/hana.go
Labels: kind/feature, area/cli, size/L, lgtm, cla: yes

#2017 add command hana delete
  internal/cmd/hana/delete.go
  internal/cmd/hana/hana.go
  internal/cmd/hana/provision.go
  internal/cmd/imageimport/imageimport.go
Labels: kind/feature, area/cli, size/L, lgtm, cla: yes

#2018 unify commands for hana
  internal/cmd/hana/check.go
  internal/cmd/hana/credentials.go
  internal/cmd/hana/delete.go
  internal/cmd/hana/provision.go
Labels: kind/feature, area/cli, size/L, lgtm, cla: yes

#2020 change default memory value for hana provision
  internal/cmd/hana/provision.go
Labels: kind/feature, area/cli, size/XS, lgtm, cla: yes

#2019 better error messages for BTP/CIS
  internal/btp/auth/credentials.go
  internal/btp/auth/xsuaa.go
  internal/btp/cis/provision.go
  internal/cmd/provision/provision.go
Labels: size/M, lgtm, cla: yes

#2021 add possibility to get only user or password from hana credentials
  internal/cmd/hana/credentials.go
Labels: kind/feature, area/cli, size/S, lgtm, cla: yes

#2022 Add reference-instance command
  internal/btp/operator/gvk.go
  internal/cmd/kyma.go
  internal/cmd/referenceinstance/referenceinstance.go
  internal/cmd/referenceinstance/resource.go
Labels: size/L, lgtm, cla: yes
