Repository kyma-project/cli, pull requests merged in 2024-09, with the labels that each got.

#2213 Close response body
  internal/communitymodules/cluster/modules.go
Labels: size/S, lgtm, cla: yes

#2215 Unify linter config
  .golangci.yaml
Labels: size/XS, lgtm, cla: yes

#2216 Lint tests
  .golangci.yaml
  internal/communitymodules/modules_test.go
  internal/kube/kyma/kyma_test.go
  internal/registry/portforward/transport_test.go
Labels: size/S, cla: yes

#2218 Cleanup linter excludes
  .golangci.yaml
  internal/cmd/alpha/hana/check_test.go
  internal/communitymodules/modules_test.go
Labels: size/M, lgtm, cla: yes

#2220 Registry config command
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/imageimport/imageimport.go
  internal/cmd/alpha/registry/config/config.go
  internal/cmd/alpha/registry/registry.go
  internal/registry/config.go
  internal/registry/config_test.go
  internal/registry/types.go
Labels: size/L, lgtm, cla: yes

#2222 Add test for 'GetExternalConfig'
  internal/registry/config_test.go
Labels: size/M, lgtm, cla: yes
