Repository kyma-project/cli, pull requests merged in 2024-02, with the labels that each got.

#1934 chore: Bump ocm library to v0.6.0
  go.mod
  go.sum
  pkg/module/blob/blob.go
  pkg/module/oci_repo.go
  pkg/module/remote.go
  pkg/module/resources.go
  pkg/module/security_scan.go
  pkg/module/sign.go
Labels: size/M, lgtm, cla: yes

#1947 feat: Release 2.20.3
  .github/workflows/test-e2e-create-module.yml
  cmd/kyma/alpha/add/add.go
  cmd/kyma/alpha/add/module/mock/mock_interactor.go
  cmd/kyma/alpha/add/module/module.go
  cmd/kyma/alpha/add/module/module_test.go
  cmd/kyma/alpha/add/module/opts.go
  cmd/kyma/alpha/add/module/opts_test.go
  cmd/kyma/alpha/alpha.go
  cmd/kyma/alpha/delete/delete.go
  cmd/kyma/alpha/delete/module/module.go
  cmd/kyma/alpha/delete/module/module_test.go
  cmd/kyma/alpha/delete/module/opts.go
  docs/gen-docs/kyma_alpha.md
  docs/gen-docs/kyma_alpha_add.md
  docs/gen-docs/kyma_alpha_add_module.md
  docs/gen-docs/kyma_alpha_delete.md
  docs/gen-docs/kyma_alpha_delete_module.md
  go.mod
  go.sum
  pkg/module/blob/blob.go
  pkg/module/oci_repo.go
  pkg/module/remote.go
  pkg/module/resources.go
  pkg/module/security_scan.go
  pkg/module/sign.go
  tests/e2e/create_module/kyma_create_module_test.go
Labels: size/L, lgtm, cla: yes

#1958 Init go project structure
  go.mod
  go.sum
  internal/btp/oauth.go
  internal/cmd/kyma.go
  internal/cmd/provision/provision.go
  main.go
Labels: kind/feature, area/cli, size/M, lgtm, cla: yes

#1959 Implement CIS auth logic
  internal/btp/credentials.go
  internal/btp/oauth.go
  internal/btp/xsuaa.go
  internal/cmd/kyma.go
  internal/cmd/provision/provision.go
  main.go
Labels: kind/feature, area/cli, size/L, lgtm, cla: yes

#1960 Test cis auth
  go.mod
  go.sum
  internal/btp/credentials_test.go
  internal/btp/xsuaa.go
  internal/btp/xsuaa_test.go
  internal/cmd/provision/provision.go
Labels: kind/feature, area/cli, size/L, lgtm, cla: yes

#1970 Improve the `XSUAA.go` file
  internal/btp/xsuaa.go
  internal/btp/xsuaa_test.go
Labels: area/cli, size/M, lgtm, kind/cleanup, cla: yes

#1969 Implement CIS client
  go.mod
  go.sum
  internal/btp/client.go
  internal/btp/client_test.go
Labels: kind/feature, area/cli, size/L, lgtm, cla: yes

#1971 chore: Bump `ocm` dependency to `v0.7.0`
  go.mod
  go.sum
  pkg/module/oci_repo.go
Labels: size/S, lgtm, cla: yes

#1964 Implement kyma provision
  internal/btp/provision.go
  internal/btp/provision_test.go
  internal/cmd/provision/provision.go
Labels: size/L, lgtm, cla: yes
