Repository kyma-project/cli, pull requests merged in 2024-10, with the labels that each got.

#2223 Use correct linter action version
  .github/workflows/markdown.yml
Labels: size/S, cla: yes

#2226 Get rid of pre-release action
  .github/workflows/pre-release-release.yaml
Labels: area/cli, area/ci, size/M, lgtm, kind/chore, cla: yes

#2227 Update nightly release description
  .goreleaser-dev.yml
Labels: area/cli, area/ci, size/XS, lgtm, kind/chore, cla: yes

#2229 Make the `--kubeconfig` frag persistent
  internal/cmd/alpha/access/access.go
  internal/cmd/alpha/add/add.go
  internal/cmd/alpha/add/managed/managed.go
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/hana/check.go
  internal/cmd/alpha/hana/check_test.go
  internal/cmd/alpha/hana/credentials.go
  internal/cmd/alpha/hana/delete.go
  internal/cmd/alpha/hana/map.go
  internal/cmd/alpha/hana/provision.go
  internal/cmd/alpha/imageimport/imageimport.go
  internal/cmd/alpha/modules/modules.go
  internal/cmd/alpha/oidc/oidc.go
  internal/cmd/alpha/referenceinstance/referenceinstance.go
  internal/cmd/alpha/registry/config/config.go
  internal/cmd/alpha/remove/managed/managed.go
  internal/cmd/alpha/remove/remove.go
  internal/cmd/kyma.go
  internal/cmdcommon/kubeconfig.go
  internal/cmdcommon/kymaconfig.go
  internal/communitymodules/modules.go
  internal/communitymodules/modules_test.go
  main.go
Labels: area/cli, size/L, lgtm, kind/cleanup, cla: yes

#2230 Resource extensions implementation
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/templates/explain.go
  internal/cmdcommon/extension.go
  internal/cmdcommon/extension_test.go
  internal/cmdcommon/extension_types.go
  internal/cmdcommon/kymaconfig.go
Labels: kind/feature, area/cli, size/L, lgtm, cla: yes
