Repository kyma-project/cli, pull requests merged in 2025-02, with the labels that each got.

#2343 Rework modules list
  internal/cmd/alpha/module/list.go
  internal/kube/fake/kyma.go
  internal/kube/kyma/kyma.go
  internal/kube/kyma/types.go
  internal/modules/list.go
  internal/modules/list_test.go
  internal/modules/render.go
  internal/modules/render_test.go
Labels: size/XL, lgtm, cla: yes

#2344 Replace render table lib
  go.mod
  go.sum
  internal/cmd/alpha/templates/get.go
  internal/cmd/alpha/templates/get_test.go
  internal/modules/list.go
  internal/modules/render.go
  internal/modules/render_test.go
  internal/render/table.go
Labels: area/cli, size/L, lgtm, kind/cleanup, cla: yes, kind/enhancement

#2345 Switch name flag to args for get template command
  internal/cmd/alpha/templates/args.go
  internal/cmd/alpha/templates/get.go
  internal/cmd/alpha/templates/get_test.go
  internal/cmd/alpha/templates/types/command.go
  internal/cmdcommon/extension.go
  internal/cmdcommon/extension_test.go
  internal/cmdcommon/extension_types.go
Labels: area/cli, size/M, lgtm, cla: yes, kind/enhancement

#2346 Switch name flag to args for delete template command
  internal/cmd/alpha/templates/args.go
  internal/cmd/alpha/templates/delete.go
  internal/cmd/alpha/templates/delete_test.go
  internal/cmd/alpha/templates/templates.go
  internal/cmdcommon/extension.go
Labels: area/cli, size/M, lgtm, cla: yes, kind/enhancement

#2347 Switch name flag to args for create template command
  internal/cmd/alpha/templates/create.go
  internal/cmd/alpha/templates/create_test.go
  internal/cmd/alpha/templates/templates.go
  internal/cmdcommon/extension.go
Labels: area/cli, size/M, cla: yes, kind/enhancement

#2354 Unify flags and commands descriptions
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/app/app.go
  internal/cmd/alpha/app/push.go
  internal/cmd/alpha/hana/hana.go
  internal/cmd/alpha/hana/map.go
  internal/cmd/alpha/module/add.go
  internal/cmd/alpha/module/catalog.go
  internal/cmd/alpha/module/delete.go
  internal/cmd/alpha/module/list.go
  internal/cmd/alpha/module/manage.go
  internal/cmd/alpha/module/module.go
  internal/cmd/alpha/module/unmanage.go
  internal/cmd/alpha/oidc/oidc.go
  internal/cmd/alpha/provision/provision.go
  internal/cmd/alpha/referenceinstance/referenceinstance.go
  internal/cmd/alpha/registry/config/config.go
  internal/cmd/alpha/registry/imageimport/imageimport.go
  internal/cmd/alpha/templates/create.go
  internal/cmd/alpha/templates/create_test.go
  internal/cmd/alpha/templates/delete.go
  internal/cmd/alpha/templates/delete_test.go
  internal/cmd/alpha/templates/get.go
  internal/cmd/alpha/templates/get_test.go
  internal/cmd/kyma.go
  internal/cmdcommon/extension.go
  internal/cmdcommon/kubeconfig.go
Labels: area/cli, size/L, kind/cleanup, cla: yes

#2358 Introduce the `.goreleaser.yml` file
  .goreleaser-dev.yml
  .goreleaser.yml
Labels: area/cli, size/M, lgtm, cla: yes, kind/enhancement

#2360 Minor fixes for docs generator
  gen-docs/main.go
  internal/cmd/kyma.go
  internal/cmdcommon/extension.go
Labels: area/cli, size/M, cla: yes, kind/enhancement

#2357 Improve installation instruction
  README.md
  hack/install_cli_nightly.sh
Labels: area/cli, size/M, lgtm, cla: yes, kind/enhancement

#2365 Add workflow that verifies possibility to build cli
  .github/workflows/pull.yaml
  go.mod
  go.sum
Labels: kind/bug, area/cli, area/ci, size/S, lgtm, cla: yes, kind/enhancement

#2364 Run lints and units on every PR
  .github/workflows/lint-golangci.yml
  .github/workflows/unit-test.yaml
Labels: area/ci, size/XS, lgtm, cla: yes, kind/enhancement

#2363 Improve docs generator
  gen-docs/main.go
  internal/cmd/alpha/access/access.go
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/app/app.go
  internal/cmd/alpha/app/push.go
  internal/cmd/alpha/hana/hana.go
  internal/cmd/alpha/hana/map.go
  internal/cmd/alpha/module/add.go
  internal/cmd/alpha/module/catalog.go
  internal/cmd/alpha/module/delete.go
  internal/cmd/alpha/module/list.go
  internal/cmd/alpha/module/manage.go
  internal/cmd/alpha/module/module.go
  internal/cmd/alpha/module/unmanage.go
  internal/cmd/alpha/oidc/oidc.go
  internal/cmd/alpha/provision/provision.go
  internal/cmd/alpha/referenceinstance/referenceinstance.go
  internal/cmd/alpha/registry/config/config.go
  internal/cmd/alpha/registry/imageimport/imageimport.go
  internal/cmd/alpha/templates/create.go
  internal/cmd/alpha/templates/create_test.go
  internal/cmd/alpha/templates/delete.go
  internal/cmd/alpha/templates/delete_test.go
  internal/cmd/alpha/templates/explain.go
  internal/cmd/alpha/templates/explain_test.go
  internal/cmd/alpha/templates/get.go
  internal/cmd/alpha/templates/get_test.go
  internal/cmd/kyma.go
  internal/cmdcommon/extension.go
Labels: area/cli, size/L, cla: yes, kind/enhancement

#2366 Sidebar generator
  docs/user/gen-docs/_sidebar.md
  gen-docs/main.go
Labels: area/cli, size/M, cla: yes, kind/enhancement

#2369 Generate docs
  docs/user/gen-docs/kyma.md
  docs/user/gen-docs/kyma_alpha.md
  docs/user/gen-docs/kyma_alpha_access.md
  docs/user/gen-docs/kyma_alpha_app.md
  docs/user/gen-docs/kyma_alpha_app_push.md
  docs/user/gen-docs/kyma_alpha_hana.md
  docs/user/gen-docs/kyma_alpha_hana_map.md
  docs/user/gen-docs/kyma_alpha_module.md
  docs/user/gen-docs/kyma_alpha_module_add.md
  docs/user/gen-docs/kyma_alpha_module_catalog.md
  docs/user/gen-docs/kyma_alpha_module_delete.md
  docs/user/gen-docs/kyma_alpha_module_list.md
  docs/user/gen-docs/kyma_alpha_module_manage.md
  docs/user/gen-docs/kyma_alpha_module_unmanage.md
  docs/user/gen-docs/kyma_alpha_oidc.md
  docs/user/gen-docs/kyma_alpha_provision.md
  docs/user/gen-docs/kyma_alpha_reference-instance.md
  docs/user/gen-docs/kyma_completion.md
  docs/user/gen-docs/kyma_completion_bash.md
  docs/user/gen-docs/kyma_completion_fish.md
  docs/user/gen-docs/kyma_completion_powershell.md
  docs/user/gen-docs/kyma_completion_zsh.md
Labels: area/documentation, area/cli, lgtm

#2367 Generate flags manually
  Makefile
  gen-docs/main.go
  internal/cmd/alpha/module/module.go
Labels: area/cli, size/M, cla: yes, kind/enhancement

#2368 Make the `.goreleaser.yml` more release oriented
  .goreleaser-dev.yml
  .goreleaser.yml
Labels: area/ci, size/S, cla: yes, kind/enhancement

#2373 Fix make_latest
  .goreleaser.yml
Labels: kind/bug, area/cli, area/ci, size/XS, lgtm, cla: yes

#2374 Fix nightly build link
  hack/install_cli_nightly.sh
Labels: area/documentation, size/XS, cla: yes, kind/enhancement

#2375 Warn about extension duplicate
  internal/cmdcommon/extension.go
  internal/cmdcommon/extension_test.go
  internal/cmdcommon/kymaconfig.go
Labels: area/cli, size/M, cla: yes, kind/enhancement

#2377 Fix nightly build link
  README.md
Labels: area/documentation, area/cli, size/XS, lgtm, cla: yes

#2376 Add the `--show-extensions-error` flag to root (`kyma`) command level
  docs/user/gen-docs/kyma.md
  docs/user/gen-docs/kyma_alpha.md
  docs/user/gen-docs/kyma_completion.md
  docs/user/gen-docs/kyma_completion_bash.md
  docs/user/gen-docs/kyma_completion_fish.md
  docs/user/gen-docs/kyma_completion_powershell.md
  docs/user/gen-docs/kyma_completion_zsh.md
  internal/cmd/kyma.go
  internal/cmdcommon/extension.go
  internal/cmdcommon/extension_test.go
  internal/cmdcommon/kymaconfig.go
Labels: area/documentation, area/cli, size/M, lgtm, cla: yes, kind/enhancement

#2379 Sidebar without indents
  docs/user/gen-docs/README.md
  docs/user/gen-docs/_sidebar.md
  docs/user/gen-docs/kyma_alpha.md
  docs/user/gen-docs/kyma_alpha_app.md
  docs/user/gen-docs/kyma_alpha_hana.md
  docs/user/gen-docs/kyma_alpha_module.md
  docs/user/gen-docs/kyma_completion.md
  docs/user/gen-docs/kyma_help.md
  gen-docs/main.go
Labels: area/documentation, area/cli, size/L, cla: yes, kind/enhancement

#2370 Add CLI description to the help.sap.com portal
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/tutorials/01-10-add-delete-modules.md
  docs/user/tutorials/01-11-manage-unmanage-modules.md
  docs/user/tutorials/README.md
Labels: size/L, lgtm, cla: yes

#2381 Warn `kyma-project.io` users about early stage of the cli
  docs/README.md
  docs/user/README.md
  docs/user/tutorials/01-10-add-delete-modules.md
  docs/user/tutorials/01-11-manage-unmanage-modules.md
Labels: area/documentation, area/cli, size/L, lgtm, cla: yes, kind/enhancement
