Repository kyma-project/cli, pull requests merged in 2025-03, with the labels that each got.

#2380 Add kyma alpha app push tutorial
  docs/user/tutorials/01-20-app-push-command-usage.md
Labels: size/M, lgtm, cla: yes

#2383 Adding the Running an Application tutorial to sidebar
  docs/user/_sidebar.md
Labels: size/XS

#2384 Implement the `kyma version` command
  .goreleaser.yml
  Makefile
  internal/cmd/kyma.go
  internal/cmd/version/version.go
Labels: kind/feature, area/cli, size/M, lgtm

#2385 Remove the old `.goreleaser-dev.yml` file
  .goreleaser-dev.yml
Labels: area/cli, size/M, kind/cleanup

#2391 Migrate sec scanners
  sec-scanners-config.yaml
Labels: size/S

#2394 Remove unnecessary config fields
  .goreleaser.yml
Labels: area/ci, size/XS, lgtm, kind/cleanup

#2393 Run builds on pull for every arch and os
  .github/workflows/pull.yaml
Labels: area/ci, size/XS, kind/enhancement

#2395 Always make minimalistic release
  .goreleaser.yml
Labels: area/ci, size/XS, kind/enhancement

#2399 Cherry pick 3.0
  .github/workflows/pull.yaml
  .goreleaser.yml
  Makefile
  internal/cmd/kyma.go
  internal/cmd/version/version.go
Labels: area/cli, area/ci, size/M, kind/enhancement

#2403 Return clierror.Error on any error
  main.go
Labels: area/cli, kind/enhancement

#2402 Implement the `kubeconfig generate` command
  docs/user/gen-docs/_sidebar.md
  docs/user/gen-docs/kyma.md
  docs/user/gen-docs/kyma_alpha.md
  docs/user/gen-docs/kyma_alpha_access.md
  docs/user/gen-docs/kyma_alpha_kubeconfig.md
  docs/user/gen-docs/kyma_alpha_kubeconfig_generate.md
  docs/user/gen-docs/kyma_version.md
  internal/cmd/alpha/access/access.go
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/kubeconfig/generate.go
  internal/cmd/alpha/kubeconfig/kubeconfig.go
  tests/btp/integration-test-btp.sh
  tests/k3d/integration-test-k3d.sh
Labels: kind/feature, area/cli, size/L

#2407 Build locally with version
  Makefile
Labels: area/cli, kind/enhancement

#2405 OIDC for the `kubeconfig generate` command
  docs/user/gen-docs/_sidebar.md
  docs/user/gen-docs/kyma_alpha.md
  docs/user/gen-docs/kyma_alpha_kubeconfig_generate.md
  docs/user/gen-docs/kyma_alpha_oidc.md
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/kubeconfig/generate.go
  internal/cmd/alpha/oidc/oidc.go
  internal/cmd/alpha/oidc/oidc_test.go
Labels: kind/feature, area/ci

#2406 Implement flags validation
  internal/cmd/alpha/app/push.go
  internal/cmd/alpha/hana/map.go
  internal/cmd/alpha/kubeconfig/generate.go
  internal/cmd/alpha/module/add.go
  internal/cmd/alpha/module/manage.go
  internal/cmd/alpha/provision/provision.go
  internal/cmd/alpha/referenceinstance/referenceinstance.go
  internal/cmd/alpha/templates/create.go
  internal/cmd/alpha/templates/get.go
  internal/cmdcommon/flags/validate.go
  internal/cmdcommon/flags/validate_test.go
Labels: area/cli, kind/enhancement

#2409 Add possibility to skip extensions fetching
  Makefile
  docs/user/gen-docs/kyma.md
  docs/user/gen-docs/kyma_alpha.md
  docs/user/gen-docs/kyma_alpha_app.md
  docs/user/gen-docs/kyma_alpha_app_push.md
  docs/user/gen-docs/kyma_alpha_hana.md
  docs/user/gen-docs/kyma_alpha_hana_map.md
  docs/user/gen-docs/kyma_alpha_kubeconfig.md
  docs/user/gen-docs/kyma_alpha_kubeconfig_generate.md
  docs/user/gen-docs/kyma_alpha_module.md
  docs/user/gen-docs/kyma_alpha_module_add.md
  docs/user/gen-docs/kyma_alpha_module_catalog.md
  docs/user/gen-docs/kyma_alpha_module_delete.md
  docs/user/gen-docs/kyma_alpha_module_list.md
  docs/user/gen-docs/kyma_alpha_module_manage.md
  docs/user/gen-docs/kyma_alpha_module_unmanage.md
  docs/user/gen-docs/kyma_alpha_provision.md
  docs/user/gen-docs/kyma_alpha_reference-instance.md
  docs/user/gen-docs/kyma_completion.md
  docs/user/gen-docs/kyma_completion_bash.md
  docs/user/gen-docs/kyma_completion_fish.md
  docs/user/gen-docs/kyma_completion_powershell.md
  docs/user/gen-docs/kyma_completion_zsh.md
  docs/user/gen-docs/kyma_help.md
  docs/user/gen-docs/kyma_version.md
  internal/cmd/kyma.go
  internal/cmdcommon/extension.go
Labels: area/documentation, area/cli, kind/cleanup, kind/enhancement

#2413 Add `--image-pull-secret` for the `app push` command
  docs/user/gen-docs/kyma_alpha_app_push.md
  internal/cmd/alpha/app/push.go
Labels: kind/feature, area/documentation, area/cli

#2412 Get rid of the `@v3` suffix
  .github/workflows/pull.yaml
  Makefile
  README.md
  docs/user/README.md
  docs/user/gen-docs/kyma_alpha_kubeconfig_generate.md
  docs/user/tutorials/01-10-add-delete-modules.md
  docs/user/tutorials/01-11-manage-unmanage-modules.md
  docs/user/tutorials/01-20-app-push-command-usage.md
  hack/install_cli_latest.sh
  hack/install_cli_nightly.sh
  internal/cmd/alpha/kubeconfig/generate.go
  tests/btp/integration-test-btp.sh
  tests/k3d/integration-test-k3d.sh
Labels: kind/bug, area/cli

#2416 Improve the `--image-pull-secret` description
  docs/user/gen-docs/kyma_alpha_app_push.md
  internal/cmd/alpha/app/push.go
Labels: area/documentation, area/cli

#2417 Update codeowners
  CODEOWNERS
Labels: area/ci, kind/enhancement

#2418 Update docs codeowners
  CODEOWNERS
Labels: area/ci, kind/enhancement

#2318 Implement Acceptance e2e tests for BTP user journey
  .github/actions/ensure-pack/action.yaml
  .github/workflows/btp-integration-tests.yml
  .github/workflows/pull.yaml
  .gitignore
  tests/btp/Makefile
  tests/btp/integration-test-btp.sh
  tests/btp/k8s-resources/custom-docker-registry.yaml
  tests/btp/k8s-resources/db/books-hdi-initjob-template.yaml
  tests/btp/k8s-resources/db/hana-hdi-binding.yaml
  tests/btp/k8s-resources/db/hana-hdi-instance.yaml
  tests/btp/k8s-resources/db/kustomization.yaml
  tests/btp/k8s-resources/exposed-docker-registry.yaml
  tests/btp/k8s-resources/object-store-binding.yaml
  tests/btp/kyma-cleanup.sh
  tests/btp/sample-http-db-nodejs/bookstore/package.json
  tests/btp/sample-http-db-nodejs/bookstore/src/app.js
  tests/btp/sample-http-db-nodejs/bookstore/src/hana.js
  tests/btp/sample-http-db-nodejs/hdi-deploy/package.json
  tests/btp/sample-http-db-nodejs/hdi-deploy/src/.hdiconfig
  tests/btp/sample-http-db-nodejs/hdi-deploy/src/tables/.hdinamespace
  tests/btp/sample-http-db-nodejs/hdi-deploy/src/tables/books.csv
  tests/btp/sample-http-db-nodejs/hdi-deploy/src/tables/books.hdbtable
  tests/btp/sample-http-db-nodejs/hdi-deploy/src/tables/books.hdbtabledata
  tests/btp/tf/main.tf
  tests/btp/tf/variables.tf
Labels: size/XL, cla: yes

#2431 Document how to install stable cli
  docs/user/README.md
  hack/install_cli_stable.sh
Labels: area/documentation, area/cli

#2432 Fix stable release script
  hack/install_cli_stable.sh
Labels: kind/bug, area/cli

#2438 Implement actionCommands functionality
  internal/cmd/alpha/alpha.go
  internal/cmd/alpha/function/init.go
  internal/cmd/alpha/templates/actions/function_init.go
  internal/cmd/alpha/templates/create.go
  internal/cmd/alpha/templates/delete.go
  internal/cmd/alpha/templates/parameters/set.go
  internal/cmd/alpha/templates/parameters/set_test.go
  internal/cmd/alpha/templates/types/action.go
  internal/cmd/alpha/templates/types/create.go
  internal/cmd/alpha/templates/types/flag.go
  internal/cmdcommon/extension.go
  internal/cmdcommon/extension_types.go
Labels: area/cli, area/serverless, kind/enhancement

#2435 Brew installation guide
  docs/user/README.md
Labels: area/documentation, area/cli
