Repository kyma-project/cli, pull requests merged in 2025-09, with the labels that each got.

#2563 Resolve cluster domain in e2e btp test
  .github/workflows/btp-integration-tests.yml
  tests/btp/Makefile
  tests/btp/integration-test-btp.sh
Labels: kind/bug

#2561 Multi thread module list
  internal/modules/list.go
  internal/modules/list_test.go
Labels: area/cli, kind/enhancement

#2570 Improve some of the error messages
  internal/btp/hana/hana.go
  internal/btp/hana/hana_test.go
  internal/cmd/alpha/hana/map.go
  internal/cmd/alpha/kubeconfig/generate.go
  internal/cmd/app/push.go
  internal/cmd/module/catalog.go
  internal/cmd/module/list.go
  internal/cmd/module/manage.go
  internal/cmdcommon/kubeconfig.go
  internal/dockerfile/build.go
  internal/dockerfile/build_test.go
  internal/extensions/actions/function_init.go
  internal/extensions/actions/registry_image-import.go
  internal/extensions/extensions.go
  internal/extensions/extensions_test.go
  internal/modules/disable.go
  internal/modules/disable_test.go
  internal/modules/enable.go
  internal/modules/enable_test.go
  internal/modules/list.go
  internal/modules/manage.go
  internal/modules/repo/moduletemplates.go
  internal/registry/config.go
  internal/registry/config_test.go
Labels: kind/enhancement

#2498 Update docs with no-alpha commands
  README.md
  docs/extensibility/README.md
  docs/extensibility/create-extension.md
  docs/user/tutorials/01-10-add-delete-modules.md
  docs/user/tutorials/01-11-manage-unmanage-modules.md
  docs/user/tutorials/01-20-app-push-command-usage.md
  docs/user/tutorials/01-30-image-import.md
Labels: area/documentation, area/cli

#2573 Move the `portforward` package to the internal level
  internal/portforward/automock/connection.go
  internal/portforward/automock/stream.go
  internal/portforward/dial.go
  internal/portforward/retry.go
  internal/portforward/retry_test.go
  internal/portforward/transport.go
  internal/portforward/transport_mock.go
  internal/portforward/transport_test.go
  internal/registry/image.go
  internal/registry/image_test.go
Labels: kind/cleanup

#2515 Update docs after moving the `app push` command out of the `alpha` group
  README.md
  docs/user/gen-docs/_sidebar.md
  docs/user/gen-docs/kyma.md
  docs/user/gen-docs/kyma_alpha.md
  docs/user/gen-docs/kyma_app.md
  docs/user/gen-docs/kyma_app_push.md
  docs/user/tutorials/01-20-app-push-command-usage.md
Labels: area/documentation

#2576 Ignore extension commands with wrong action name
  internal/extensions/commands.go
  internal/extensions/commands_test.go
  internal/extensions/extensions.go
  internal/extensions/types/types.go
  internal/extensions/types/types_test.go
Labels: kind/bug, kind/enhancement

#2578 Extract generic pod operations from registry pkg
  internal/kube/resources/pod.go
  internal/registry/config.go
  internal/registry/config_test.go
Labels: kind/cleanup

#2575 Improve registry config error message
  internal/registry/config.go
Labels: kind/enhancement

#2585 Implement the `call_files_to_save` action
  internal/cmd/kyma.go
  internal/extensions/actions/call_files_to_save.go
  internal/extensions/actions/common/configurator.go
  internal/extensions/actions/function_init.go
  internal/extensions/call/pod.go
  internal/extensions/call/response.go
  internal/portforward/request.go
Labels: kind/feature, area/cli

#2599 Support output message for the `call_files_to_save` action
  docs/extensibility/actions.md
  internal/extensions/actions/call_files_to_save.go
  internal/extensions/call/response.go
Labels: kind/enhancement

#2605 Make cluster-/role binding optional when generating kubeconfig
  docs/user/gen-docs/kyma_alpha_kubeconfig_generate.md
  internal/cmd/alpha/kubeconfig/generate.go
  internal/kube/resources/rbac.go
  internal/kube/resources/rbac_test.go
Labels: kind/enhancement

#2609 Cover case when flag has empty (not nil) default value
  internal/cmdcommon/types/map.go
  internal/cmdcommon/types/nullablebool.go
  internal/cmdcommon/types/nullableint.go
  internal/cmdcommon/types/nullablestring.go
  internal/extensions/commands_test.go
  internal/extensions/extensions_test.go
  internal/extensions/flags_test.go
  internal/extensions/parameters/parameters.go
  internal/extensions/parameters/parameters_test.go
  internal/extensions/parameters/types.go
  internal/extensions/types/types.go
Labels: kind/bug
